### DISCUSSION TITLE
SCSS vars

### DISCUSSION THREAD

**Discussion by JiDai** [vercel/next.js#10906] [Help] [answered]
Hi,

I just updated to 9.3 and I am testing.
I want to share variables between global styles and components. I don't which is the right way and how the CSS will be generated.

Here is the structure
```
├── components
│   └── Button.scss
├── styles
│   ├── _variables.scss
│   └── index.scss
```

And here is the file contents

```scss
// index.scss
@import "variables.scss";
```

```scss
// _variables.scss
$color: blue;
```

```scss
// Button.scss
@import ../styles/variables.scss

Button {
  color: $color
}
```

And I get the following error :

```
SassError: File to import not found or unreadable: ../styles/variables.
```

Thanks for help

**Comment by Timer** [comment, marked as answer]
Can you try the following instead:
```scss
// components/Button.scss
@import "../styles/_variables.scss";

Button {
  color: $color
}
```

Note the quotes around the import.

Also, your example imported `variables` and not `_variables`, but I assume this was a typo in your demo.
