### DISCUSSION TITLE
PORT from environment in doker-compose.yml

### DISCUSSION THREAD

**Discussion by chiqui3d** [vercel/next.js#11656] [Help] [answered]
It would be possible that Next.js in dev mode could obtain the `port `from the environment if it existed and was not indicated by the `-p`?

Example:

docker-compose.yml
```yml
client:
    environment:
      PORT: ${PORT_CLIENT}
      NODE_ENV: ${NODE_ENV}
```
package.json

`"dev": "next",`
