### DISCUSSION TITLE
Monorepo with 2 next apps CI cache

### DISCUSSION THREAD

**Discussion by felixmosh** [vercel/next.js#12117] [Help]
Hi all,

I've noticed that in CI (GitHub actions) I'm getting
`Warning: No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache`

From what I've understood, this section of the examples
```yml
uses: actions/cache@v1
with:
  path: ${{ github.workspace }}/.next/cache
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
```
builds cache only for one next app.

I've have a monorepo with 2 next apps (`packages/front`, `packages/admin`), how can I apply cache to my repo?

Thanx!

**Comment by hveveris** [comment]
I have the same question today, 272 days later

**Reply by felixmosh** [reply]
I've solved it already, 

```yml
- uses: actions/cache@v2
     with:
       path: ${{ github.workspace }}/packages/*/.next/cache
       key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}
```

`actions/cache` v2 supports multiple dir :]
