### DISCUSSION TITLE
NextJS rebuild periodically / "cronjob"

### DISCUSSION THREAD

**Discussion by josias-r** [vercel/next.js#12486] [Help] [answered]
I was looking into the API of a shop. They want you to import the products you create in that shop every day for example (and I think that's a conventional way of doing it) if you decide to create your own shop instead of using one of their services.

I was wondering if something like that is possible in NextJS?

I know that with methods like `getStaticPaths` I could use their API endpoint to build a NextJS powered webshop. But like I mentioned this would require the website to be rebuilt about every 24 hours or so.

Is there something like that possible with now and NextJS? Or are there other alternatives?

**Comment by brianlovin** [comment, marked as answer]
You can use GitHub actions to do this. Here's an example action running on a cron: https://github.com/specfm/design-details/blob/master/.github/workflows/deploy.yml

```yml
name: weekly episode deployment

on:
  schedule:
    - cron:  '30 12 * * 3'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-args: '--prod'
          now-org-id: ${{ secrets.ZEIT_ORG_ID }}
          now-project-id: ${{ secrets.ZEIT_PROJECT_ID}}
```

These secrets can be found after you link a project for the first time with `now`. This generates a `.now` directory in your project, which contains a `project.json` file with the `orgId` and `projectId` values. Then you'll add those as secrets in your repo settings (`https://github.com/{your repo url}/settings/secrets`). The `zeit-token` can be found in your Vercel project settings (https://vercel.com/account/tokens)
