### DISCUSSION TITLE
Running "next build" on ec2 is slow

### DISCUSSION THREAD

**Discussion by Nosherwan** [vercel/next.js#12855] [Help]
I am deploying a next js application on _ec2 t2.micro_ instance via docker.
_'next build'_ command takes a long time & I suspect with increasing page numbers it will probably stall as there is only 1 GB ram available on a t2.micro instance.
One possibility is that I run _'next build'_ on my local machine and then push _.next_ folder to the ec2 instance via git, that way I can skip the _'next build'_ step on the instance itself.

Is this is reasonable course of action or _'next build'_ should be run on the ec2 instance?

My docker file is as follows:
```yml
FROM node:10.15.3-alpine
RUN apk add --no-cache tzdata
ENV TZ Australia/Sydney
# Create app directory
WORKDIR /app

COPY package*.json /app/
# Installs everything from package.json
RUN npm install
# Will copy all files except node_modules
COPY . .
# Building app, (can this be done locally & push .next folder on instance)
RUN npm run build
# even though port is being exposed it will
# be overridden by docker-compose port
EXPOSE 3000 

CMD [ "npm", "start" ]
```

My relevant docker compose section is:
```yml
version: '3.2'
services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: my-web-app
    container_name: webapp
    ports:
      - 3000:3000
    volumes:
      # To sync file changes.
      - ./:/app
      # To not break node modules.
      - /app/node_modules
      # For next build.
      - /app/.next

    restart: unless-stopped
    networks:
      - app-network
```
Also as the ec2 instance deployment is production, please suggest any changes in the docker file that my not be required in prod, such as the volume creation.
