### DISCUSSION TITLE
Tailwindcss with SSR

### DISCUSSION THREAD

**Discussion by sambhav-gore** [vercel/next.js#12868] [Help] [answered]
I used the official example from here https://github.com/zeit/next.js/tree/canary/examples/with-tailwindcss 

You can see it deployed here - https://next-js-tailwind-ex.now.sh/

My Question is that I am unable to figure out how to do it correctly with SSR so that the initial response from server contains the styles within head (inline in the file).

@taylorbryant you have any tips for this may be ? Thank you for putting up the example btw and also for updating it to the latest updates from tailwindcss.

**Comment by cdock1029** [comment]
Do you have a link to your code that isn't working? The linked example seems to work fine, so isn't much help.

Did you import your `.css` in `_app.js` ? 

https://github.com/cdock1029/with-tailwind/blob/master/pages/_app.js

https://with-tailwind.cdock.now.sh/

**Reply by sambhav-gore** [reply]
no, I mean I want the server side response to come along with the css inline. As of now it loads css afterwards. so if you look at the network inspector, the styles are not part of the initial (very first response) : 

![tailwind](https://user-images.githubusercontent.com/11697969/81985134-23b9c900-9636-11ea-9c84-6d71c14d68e0.png)



For comparison, following is a what comes from Alligator io (what I am trying to achieve):

![alligator](https://user-images.githubusercontent.com/11697969/81985356-70050900-9636-11ea-9373-8f795c76c396.png)

I was able to do it with NextJS with JSS in an earlier project, but what I am not understanding is that how to combine the two approaches. It is for sure possible to extract the css from the tree but not sure how to go about in-lining that.

**Reply by cdock1029** [reply]
Ahh yes, my fault. Didn't pay attention to what you were saying.

**Comment by taylorbryant** [comment, marked as answer]
@sambhav-gore Thanks for the kind words!

I've actually never tried inlining CSS in the head in Next.js.

A quick search turned up these. Maybe they'll be helpful?
- https://www.npmjs.com/package/next-critical
- https://stackoverflow.com/questions/57057947/how-to-inline-css-in-the-head-tag-of-a-nextjs-project

**Reply by sambhav-gore** [reply]
thanks I will check them out in the weekend probably.

**Reply by zhe** [reply]
Thanks for pointing out.

**Comment by JamesSingleton** [comment]
So I too am running into this issue. I have a Header component that looks like this

```jsx
import Link from 'next/link';
import styles from "@/styles/Header.module.css";

const Header = () => (
  <div className="container mx-auto relative bg-white">
    <div className="max-w-7xl mx-auto ">
      <div className="flex justify-between items-center border-b-2 border-gray-200 py-6 md:justify-start md:space-x-10">
        <div className="lg:w-0 lg:flex-1">
          <Link href="/">
            <a className="flex">
              <span>Original Harvest</span>
            </a>
          </Link>
        </div>
        <div className="-mr-2 -my-2 md:hidden">
          <button
            type="button"
            className="inline-flex items-center justify-center p-2  text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out"
          >
            <svg
              className="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M4 6h16M4 12h16M4 18h16"
              />
            </svg>
          </button>
        </div>
        <nav className="hidden md:flex space-x-10">
          <Link href="/new-arrivals">
            <a className={styles.menuLink}>
              New Arrivals
            </a>
          </Link>
          <Link href="/products">
            <a className={styles.menuLink}>
              Shop by Benefit
            </a>
          </Link>

          <Link href="/learn">
            <a className={styles.menuLink}>
              Learn
            </a>
          </Link>
          <Link href="/sales">
            <a className={styles.menuLink}>
              Sale
            </a>
          </Link>
          <Link href="/about-us">
            <a className={styles.menuLink}>
              About Us
            </a>
          </Link>
        </nav>
        <div className="hidden md:flex items-center justify-end space-x-8 md:flex-1 lg:w-0">
          <a
            href="#"
            className="whitespace-no-wrap text-base leading-6 font-medium text-gray-700 hover:text-gray-900 focus:outline-none focus:text-gray-900"
          >
            Sign in
            </a>
          <span className="inline-flex  shadow-sm">
            <a
              href="#"
              className="whitespace-no-wrap rounded-sm inline-flex items-center justify-center px-4 py-2 border border-transparent text-white leading-6 font-medium bg-gray-900 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150"
            >
              Sign up
              </a>
          </span>
        </div>
      </div>
    </div>
  </div>
);

export default Header;
```
and my css file looks like
```css
.menuLink {
  color: red;
  @apply text-base leading-6 font-medium text-gray-700;

  &:hover {
    @apply text-gray-900;
  }

  &:focus {
    @apply text-gray-900 transition ease-in-out duration-150;
  }
}

.cta {
  @apply text-center uppercase text-white p-6 bg-black z-10 p-6 font-bold inline-block cursor-pointer;
}

.hero {
  @apply p-12 relative flex flex-col justify-center items-center overflow-hidden  mt-6 rounded-md relative;
  min-height: 400px;

  h1 {
    @apply p-6 text-white font-medium z-10 text-4xl font-bold text-center;
    background-color: #811A40;

    @screen md {
      @apply text-5xl;
    }
  }

  .cta {
    @apply mt-6;
    background-color: #B5A692;
  }
}

.heroImage {
  @apply w-full object-cover absolute z-0;
  height: 400px;
}
```

However, when looking at the network tab's preview I get the following which means that it is not SSRing with styles
![image](https://user-images.githubusercontent.com/21000200/89097183-85feac00-d391-11ea-9f85-eec6feeef0ed.png)


I have set my `NODE_ENV=production` run `yarn build` and `yarn start` and I still get this. I saw a thread somewhere that styles were not SSR'd during `yarn dev` so I just wanted to make sure.
