### DISCUSSION TITLE
Detect browser support for webp in css

### DISCUSSION THREAD

**Discussion by vks-pthibeault** [vercel/next.js#13632] [Help] [answered]
I'm trying to optimize my project's images and stylesheets. I've switched all the images in my js files to webp, but I'm struggling with those in my css. Is there any way to detect browser support for webp and serve the css images appropriately?

Thanks!

**Comment by rafaelalmeidatk** [comment, marked as answer]
It is not possible only with CSS. What you can do is detect if there is support for WEBP using JavaScript (I would look into Modernizr source code for this) and adding a class to the `body`, then you can write your CSS like this:
```css
.foo {
  background-image: url('/images/foo.jpg');
}

body.webp .foo {
  background-image: url('/images/foo.webp');
}
```

I haven't tested this approach myself but I can imagine this may cause some flicker in the images, I recommend trying to use `<picture>` as much as possible.
