### DISCUSSION TITLE
Hot reloading stops working after some time in components folder

### DISCUSSION THREAD

**Discussion by serendipity1004** [vercel/next.js#14447] [Help]
I am currently using docker compose for development. When working with docker compose with nextJS, hot reloading abruptly stops working after some time. It's totally random when it happens but it does not happen in the `pages` files. For me it's only been happening in components folder. What's even worse is that if I force reload by changing files in `pages` folder because they are still responsive, the changes in `components` folder is not reflected. Almost as if the server took a snapshot of previous version of the components. I am attaching .gif file to demonstrate the issue. I can provide any additional information. I am just attaching the .gif file because I have no idea where to look. 

When I put `//` in the file within components folder which I am 100% sure is imported in the index.tsx page, hot reload does not work. However, when I do the same action in the index.tsx page, hot reload works just fine.
![reloadbug](https://user-images.githubusercontent.com/20388249/85292997-afe1ca80-b4d7-11ea-9c00-281b2a669235.gif)

my docker compose file looks like below

```
version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./Nginx
    volumes:
      - ./Nginx/logs:/var/log/nginx
    ports:
      - '80:80'

  rest:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./RestApi
    volumes:
      - ./RestApi:/usr/app
    env_file:
      - common.env
    depends_on:
      - postgres

  postgres:
    build:
      dockerfile: dev.Dockerfile
      context: ./Postgresql
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - common.env
    volumes:
      - ./Postgresql/data:/var/lib/postgresql/data

  apollo:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./ApolloApi
    volumes:
      - ./ApolloApi:/usr/app
      - /usr/app/node_modules
    env_file:
      - common.env
    depends_on:
      - postgres

  next:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./NextFront
    volumes:
      - ./NextFront:/usr/app
      - /usr/app/node_modules
    env_file:
      - common.env
    ports:
      - 49153:49153
    depends_on:
      - postgres
```
