### DISCUSSION TITLE
Overriding Bootstrap styles

### DISCUSSION THREAD

**Discussion by matrixersp** [vercel/next.js#15019] [Help] [answered]
How do you guys override Bootstrap styles with CSS modules?
Say you have this selector in Bootstrap:
```css
.dropdown-menu > li > a {
  color: blue;
}
```
How do you override it with a CSS modules class without using `!important`?

**Comment by jamesmosier** [comment, marked as answer]
You should be able to do:

```css
.dropdownMenu > li > a {
  color: blue;
}
```

```html
<ul className={styles.dropdownMenu}>
  <li>
    <a>
```


---




If that doesn't work you could do:

```css
.dropdownMenu > .dropdownItem > .dropdownLink {
  color: blue;
}
```

```html
<ul className={styles.dropdownMenu}>
  <li className={styles.dropdownItem}>
    <a className={styles.dropdownLink}>
```
