### DISCUSSION TITLE
I need help with the configuration for my nextjs build i keep getting undefined:undefined

### DISCUSSION THREAD

**Discussion by ppot** [vercel/next.js#15887] [Help] [answered]
So i have a docker-compose file:
```
version: '3.8'

services:
  mysql:
    image: mysql:5.7.28
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: 
      - ".env"
    environment:
      MYSQL_HOST: localhost
    ports:
      - 3306:3306
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  api:
    image: ara_api
    env_file: 
      - ".env"
    build: .
    links:
      - mysql
      - ftp
    ports:
      - 8050:8050
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      NODE_ENV: development
      SYNC_CRON_ENABLED: "false"
      SYNC_CRON: "*/5 * * * *"
    volumes:
      - ../ara_api:/usr/src/app
    command: npm run dev

  webapp:
    image: ara_web
    build:
      context: .
      # args:
      #   NEXT_PUBLIC_API_URI: http://api:8050/api/v1
    volumes:
      - ../ara_web:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NEXT_PUBLIC_API_URI: http://api:8050/api/v1
     links:
      - api
    ports:
      - 3000:3000
    command: npm run start
```

There is no error or whatsoever. When using npm run dev. I can access my API_HOST_IP and API_HOST_PORT who are in my `next.config.js`

```
require('dotenv').config()

module.exports = {
  webpackDevMiddleware: config => {
    config.watchOptions = {
      poll: 1000,
      aggregateTimeout: 300,
    }
    
    return config
  },
  env: {
    NEXT_PUBLIC_API_URI: process.env.NEXT_PUBLIC_API_URI 
  },
  poweredByHeader: false
}
```

After the build and `docker-compose up`,

I can request my login and it make the request to my api:
```
export default async (req: NextApiRequest, res: NextApiResponse) => {
    const url = NEXT_PUBLIC_API_URI: process.env.NEXT_PUBLIC_API_URI + '/auth/login';
    try {
   ....
```

But the `NEXT_PUBLIC_API_URI `  stay undefined. 

I tried adding args in compose and arg in Dockerfile. no success. 
```
ARG NEXT_PUBLIC_API_URI
ENV NEXT_PUBLIC_API_URI $NEXT_PUBLIC_API_URI
```
