### DISCUSSION TITLE
How to add font ttf file in nextjs

### DISCUSSION THREAD

**Discussion by Shankhadeep1234** [vercel/next.js#16257] [Help]
**I am new to Nextjs. I wanna add my custom fonts to my project. I am totally confused about how to do that(my fonts are in "public/fonts/"). my global.css file is this**-

//global.css
`html,
body {
  padding: 0;
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
}

a {
  color: inherit;
  text-decoration: none;
}

* {
  box-sizing: border-box;
}

@font-face {
  font-family: "Avenir";
  src: url("../public/fonts/AvenirNextRoundedStd-Demi.ttf");
  src: url("../public/fonts/AvenirNextRoundedStd-MedIt.ttf");
  src: url("../public/fonts/AvenirNextRoundedStd-Reg.ttf");
}`

//next.config.js
`
const withCSS = require("@zeit/next-css");
module.exports = withCSS({
  /* config options here */
});`

**Comment by jamesmosier** [comment]
You can reference files in the [`public` folder](https://nextjs.org/docs/basic-features/static-file-serving) directly without referencing the path itself:

```css
@font-face {
  font-family: "Avenir";
  src: url("/fonts/AvenirNextRoundedStd-Demi.ttf");
  src: url("/fonts/AvenirNextRoundedStd-MedIt.ttf");
  src: url("/fonts/AvenirNextRoundedStd-Reg.ttf");
}
```

Also you should consider removing `@zeit/next-css`. Next now has built in CSS support that is a much more comprehensive solution and recommended.

**Reply by davidgaspardev** [reply]
To ensure that the correct font styles are applied when different weights or styles are specified in your CSS, it's important to define each variant of the "Avenir" font family with its own @font-face rule. This includes specifying distinct font-weight and font-style properties where applicable. Here is an example of how you can configure this for the "Avenir" font:

```css
@font-face {
  font-family: "Avenir";
  src: url("/fonts/AvenirNextRoundedStd-Demi.ttf");
  font-weight: 600; /* Demi is generally considered as semi-bold or demi-bold */
}

@font-face {
  font-family: "Avenir";
  src: url("/fonts/AvenirNextRoundedStd-MedIt.ttf");
  font-weight: 500; /* Medium Italic - slightly bolder than normal */
  font-style: italic; /* Specifies that this font style is italic */
}

@font-face {
  font-family: "Avenir";
  src: url("/fonts/AvenirNextRoundedStd-Reg.ttf");
  font-weight: normal; /* Regular weight, typically 400 */
}
```

**Comment by clxrityy** [comment]
You can also use [`next/font/local`](https://nextjs.org/docs/app/building-your-application/optimizing/fonts#local-fonts) which seems to be the most optimal for me:

```ts
// fonts/index.ts
// fonts/myFont.ttf
import localFont from "next/font/local";

export const myFont = localFont({
    src: "myFont.ttf",
    display: "swap",
    variable: "--font-my-font",
});
```

```tsx
// app/layout.tsx
import "./globals.css";
import { myFont } from "@/fonts";

export default function RootLayout({
/* ... */
}) {
  return (
    <html lang="en">
      <body className={`${venite.variable}`}>
        {/* ... */}
      </body>
    </html>
  );
}
```

```css
/* app/globals.css */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  .my-font {
    font-family: var(--font-my-font);

    @apply tracking-wide;
  }
}
```

> **Note**: I've found it works better to keep the `.ttf` file *not* in `public/` for some reason?
