### DISCUSSION TITLE
create-next-app hot reloading not working in docker for mac

### DISCUSSION THREAD

**Discussion by ghost** [vercel/next.js#16331] [Help]
in docker for mac nodemon doesn't work unless you do --legacy-watch. it appears to have the same problem with create-next-app. how can I add --legacy-watch?

**Comment by jamesmosier** [comment]
do you happen to have a reproduction for this? I have a Next app that uses Docker (on a Mac) with nodemon and Next and changes to my server are reloaded and my Next.js app components are hot reloaded (via Fast Refresh). I also have apps that just run `next dev` in my Docker container and hot reloading (Fast Refresh) works fine too.

**Reply by ghost** [reply]
> do you happen to have a reproduction for this? I have a Next app that uses Docker (on a Mac) with nodemon and Next and changes to my server are reloaded and my Next.js app components are hot reloaded (via Fast Refresh). I also have apps that just run `next dev` in my Docker container and hot reloading (Fast Refresh) works fine too.

are you using bind mounts? I believe the issue only occurs with bind mounts on nodemon.

**Reply by jamesmosier** [reply]
Yep:

```yaml
  dashboard:
    container_name: dashboard
    image: dashboard:latest
    build:
      context: ./dashboard
      dockerfile: Dockerfile-dev
    stop_grace_period: 2s
    env_file: ./dashboard/.env
    expose:
      - '3000'
    volumes:
      - type: bind
        source: ./dashboard/server
        target: /app/server
      - type: bind
        source: ./dashboard/src
        target: /app/src
    depends_on:
      - nginx
```
