### DISCUSSION TITLE
Why does importing CSS modules in `_document.js` not work?

### DISCUSSION THREAD

**Discussion by jensmeindertsma** [vercel/next.js#16726] [Help] [answered]
```css
// styles.module.css
.link {
  color: green;
}
```
```js
// _document.js
import styles from "../styles.module.css";

...

<body>
  <a className={styles.link}>A link</a>
  <Main />
  <NextScript />
</body>

....

```

The styles are not applied to the element. It is given a scoped className, but this className doesn't contain the styles. Is this intended?
