### DISCUSSION TITLE
Semantic UI icons woff, woff2 and ttf request URL's not pointing to the correct CDN url

### DISCUSSION THREAD

**Discussion by phillystafford** [vercel/next.js#17359] [Help]
# Bug report

## Describe the bug

My `JS` and `CSS` assets are being served correctly from my CDN. 

The icons from `semantic-ui-css` are available on the same CDN URL as the `CSS` and `JS` files but when the browser requests them, the request `URL` is missing part of the CDN URL so the request fails with a `403`.

This is due to relative path in the CSS. Is there anyway to solve this?

Successful request URL to CSS file on CDN: 
`https://mycdn.com/v1.0/_next/static/css/07c3a312ffcabba5385f.css`

Unsuccessful request URL to icon woff file: 
`https://mycdn.com/_next/static/media/icons.38c6d8bab26db77d8c806813e1497763.woff2`

BUT, the woff file is actually available on the CDN here:
`https://mycdn.com/v1.0/_next/static/media/icons.38c6d8bab26db77d8c806813e1497763.woff2` 

## To Reproduce

**_I can share a staging environment privately with someone if it will help resolve the issue_**

In `_app.js`  I am importing the css:
import 'semantic-ui-css/semantic.min.css';
In `next.config.js` in my `publicRuntimeConfig` I am setting a cdn url:
CDN_URL = 'https://mycdn.com/v1.0';
In my custom `server.js` I am setting the prefix:
`app.setAssetPrefix(CDN_URL);`
On the frontend then my CSS correctly gets loaded over the CDN:
https://mycdn.com/v1.0/_next/static/css/07c3a312ffcabba5385f.css
But the `@font-face` declaration in this `CSS` has a relative path resulting in this URL:
https://mycdn.com/_next/static/media/icons.38c6d8bab26db77d8c806813e1497763.woff2
This is what the declaration looks like from the unminified version:

```css
@font-face {
  font-family: 'Icons';
  src: url('./themes/default/assets/fonts/icons.eot');
  src: url('./themes/default/assets/fonts/icons.eot?#iefix')
      format('embedded-opentype'),
    url('./themes/default/assets/fonts/icons.woff2') format('woff2'),
    url('./themes/default/assets/fonts/icons.woff') format('woff'),
    url('./themes/default/assets/fonts/icons.ttf') format('truetype'),
    url('./themes/default/assets/fonts/icons.svg#icons') format('svg');
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-decoration: inherit;
  text-transform: none;
}
```
The output when look at the actual CSS file is:
```css
@font-face {
  font-family: Icons;
  src: url(/_next/static/media/icons.a01e3f2d6c83dc3aee175e2482b3f777.eot);
  src: url(/_next/static/media/icons.a01e3f2d6c83dc3aee175e2482b3f777.eot?#iefix)
      format('embedded-opentype'),
    url(/_next/static/media/icons.38c6d8bab26db77d8c806813e1497763.woff2)
      format('woff2'),
    url(/_next/static/media/icons.425399f81e4ce7cbd967685402ba0260.woff)
      format('woff'),
    url(/_next/static/media/icons.c656b8caa454ed19b9a2ef7f4f5b8fea.ttf)
      format('truetype'),
    url(/_next/static/media/icons.62d9dae4e0040e81c980950003df0e07.svg#icons)
      format('svg');
  font-style: normal;
  font-weight: 400;
  font-variant: normal;
  text-decoration: inherit;
  text-transform: none;
}
```

## Expected behavior

The request for the`semantic-ui-css` icons will point tot he correct path on the CDN. 

## System information

- Version of Next.js: 9.4.4
- Version of Node.js: 10.15.3

## Additional context

I can provide a staging server to help debug the issue
