### DISCUSSION TITLE
Disable hashing of CSS class names referencing third party/external class names in CSS modules

### DISCUSSION THREAD

**Discussion by qcz** [vercel/next.js#18198] [Help]
Is there any way to disable hashing of certain class names in CSS modules? Or the only way to do this is to use a non-hashed, global CSS?

I'm using the BlueprintJS library and want to style a BlueprintJS component used in one of my components.
The BlueprintJS <Icon> component generates a span with the class name `bp3-icon`, which I want to style in one of my components.

myComponent.module.css:
```scss
.pageTitle { // This should be hashed as usual
	.bp3-icon { // This references a BlueprintJS classname, so it should not be hashed as it won't work
		background-color: red;
	}
}
```

**Comment by surjithctly** [comment]
If its coming from blueprintjs, why do you write here? may be you can overwrite by another class? 

eg: `class="bp3-icon myicon"`

```css
.pageTitle { 
	.myicon {
		background-color: red;
	}
}
```

I'm also a beginner :) You may wait for what others are saying.

**Reply by qcz** [reply]
@surjithctly It does not have anything to do with BlueprintJS in particularly, it is just a simple example. You are right, in this case I can use a custom class using the className property of the Icon component which solves this case.

**However** you usually can't override specific class names used deeply in custom components. Take an external component which renders the following layout:
```html
<div className="custom-control">
    <div className="inner-div">
    </div>
</div>
```
Even if the component allows you to add a custom class name for the outer div, you cannot style the inner div of that component in a Nextjs CSS module, as far as I know, because of the hashing.

**Reply by surjithctly** [reply]
I'm sure there must be some option to whitelist some class names. Let's wait for an expert reply :)

**Comment by sjahan** [comment]
I am not sure whether you still need an answer, but I think what you need is `:global`.

```scss
.pageTitle { // This should be hashed as usual
	:global.bp3-icon { // This references a BlueprintJS classname, so it should not be hashed as it won't work
		background-color: red;
	}
}
```

**Reply by tobiolalusi** [reply]
There is supposed to be a whitespace between `:global` and the class.

**Reply by influxofenergy** [reply]
worked for me, for those who need to style children:

```css
.pageTitle {
	:global & .bp3-icon { // applies style to .bp3-icon inside .pageTitle, referenced from global scope initially so that hashing is not applied to .bp3-icon
		background-color: red;
	}
}
```
