### DISCUSSION TITLE
Cannot find module '.next/server/pages/_error.js'

### DISCUSSION THREAD

**Discussion by kumarabhirup** [vercel/next.js#18844] [Help]
# Bug report

## Describe the bug
I am running Next.js in Lerna Monorepo using pm2 on an Nginx server on a DigitalOcean Droplet. I am deploying using GitHub Actions.

When the GitHub Actions run: `yarn install`, 
the already built and running Next.js app starts showing "Internal Server Error".

When `yarn install` and `yarn build` is successfully completed, Next.js app works all well back again.

I want zero-downtime deployment but looks like an error is breaking the build.

So I checked the `pm2 logs`, ran `yarn install && yarn build` using GitHub Actions, and refreshed Next.js app with "Internal Server Error". After following the above steps, I got the below error.
```
1|next  | Error: Cannot find module '/root/actions-runner/_work/propagateAt/propagateAt/packages/frontend/.next/server/pages/_error.js'
1|next  | Require stack:
1|next  | - /root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/require.js
1|next  | - /root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/load-components.js
1|next  | - /root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/api-utils.js
1|next  | - /root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/next-server.js
1|next  | - /root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/server/next.js
1|next  | - /root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/server/lib/start-server.js
1|next  | - /root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/cli/next-start.js
1|next  | - /root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/bin/next
1|next  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
1|next  |     at Function.Module._load (internal/modules/cjs/loader.js:898:27)
1|next  |     at Module.require (internal/modules/cjs/loader.js:1089:19)
1|next  |     at require (internal/modules/cjs/helpers.js:73:18)
1|next  |     at requirePage (/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/require.js:1:1184)
1|next  |     at loadComponents (/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/load-components.js:1:771)
1|next  |     at Server.findPageComponents (/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/next-server.js:57:296)
1|next  |     at Server.renderErrorToHTML (/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/next-server.js:108:120)
1|next  |     at async Server.renderToHTML (/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/next-server.js:107:1094)
1|next  |     at async Server.render (/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/next-server.js:55:236)
1|next  |     at async Object.fn (/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/next-server.js:40:264)
1|next  |     at async Router.execute (/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/router.js:23:67)
1|next  |     at async Server.run (/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/next-server.js:49:656)
1|next  |     at async Server.handleRequest (/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/next-server.js:20:388) {
1|next  |   code: 'MODULE_NOT_FOUND',
1|next  |   requireStack: [
1|next  |     '/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/require.js',
1|next  |     '/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/load-components.js',
1|next  |     '/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/api-utils.js',
1|next  |     '/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/next-server/server/next-server.js',
1|next  |     '/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/server/next.js',
1|next  |     '/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/server/lib/start-server.js',
1|next  |     '/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/cli/next-start.js',
1|next  |     '/root/actions-runner/_work/propagateAt/propagateAt/node_modules/next/dist/bin/next'
1|next  |   ]
1|next  | }
```

Well, I don't see the above error if I run `yarn install && yarn build` manually by SSHing in the server. The error only comes when GitHub Actions run the commands.

## To Reproduce

1. **GitHub Actions File:**
```yml
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.13]

    steps:
      - uses: actions/checkout@v2
      # - name: Set ENV variables
      #   run: for v in `cat ../../../propagate.env` ; do echo "::set-env name=${v%%=*}::${v##*=}" ; done
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: sudo swapoff -a; sudo swapon -a
      # - run: source ../../../propagate.sh
      # - run: echo $PROPAGATE_DB_USERNAME # make sure it works
      - run: cp ../../../propagate-frontend.env packages/frontend/.env
      - run: cp ../../../propagate-backend.env packages/backend/.env
      # - run: export NODE_OPTIONS="--max_old_space_size=131072"
      - run: export NODE_OPTIONS="--max_old_space_size=131072" && yarn install --frozen-lockfile
      # - run: export NODE_OPTIONS="--max_old_space_size=131072" && yarn lint
      # - run: export NODE_OPTIONS="--max_old_space_size=131072" && yarn test:ci
      - run: export NODE_OPTIONS="--max_old_space_size=131072" && yarn build
      # - run: cp /var/www/kb.propagate.at/html packages/docs/build
      - run: mv /var/www/kb.propagate.at/html /var/www/kb.propagate.at/temp && pwd && mv packages/docs/build /var/www/kb.propagate.at/html && rm -rf /var/www/kb.propagate.at/temp
      - run: pm2 reload all
        env:
          CI: true
```

2. **Next.js app package.json**
```json
{
  "name": "frontend",
  "version": "1.0.0",
  "scripts": {
    "dev": "next",
    "dev:pm2": "pm2 start yarn --name \"next\" -- run dev",
    "build": "next build",
    "start": "NODE_ENV=production next start",
    "start:pm2": "NODE_ENV=production pm2 start yarn --name \"next\" -- start -p 3000",
    "type-check": "tsc",
    "lint": "eslint . --ext js,jsx,ts,tsx",
    "lint:fix": "eslint . --fix --ext js,jsx,ts,tsx",
    "test": "NODE_ENV=test jest --passWithNoTests --watch",
    "test:ci": "NODE_ENV=test jest --passWithNoTests"
  },
  "dependencies": {
    "@apollo/client": "^3.1.1",
    "@apollo/react-hooks": "^3.1.4",
    "@sentry/browser": "^5.15.4",
    "@stripe/react-stripe-js": "^1.1.2",
    "@stripe/stripe-js": "^1.9.0",
    "@zeit/next-source-maps": "^0.0.3",
    "apollo-boost": "^0.4.7",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link": "^1.2.14",
    "apollo-link-context": "^1.0.20",
    "apollo-link-error": "^1.1.13",
    "apollo-link-http": "^1.5.17",
    "apollo-link-persisted-queries": "^0.2.2",
    "apollo-link-state": "^0.4.2",
    "apollo-link-ws": "^1.0.20",
    "apollo-utilities": "^1.3.4",
    "csvtojson": "^2.0.10",
    "dotenv": "^8.2.0",
    "draft-js": "^0.11.7",
    "draftjs-to-html": "^0.9.1",
    "escape-html": "^1.0.3",
    "formik": "^2.1.4",
    "framer-motion": "^1.10.2",
    "graphql-tag": "^2.10.3",
    "html-to-draftjs": "1.4.0",
    "immutable": "3.7.6",
    "is-valid-email": "^0.0.5",
    "isomorphic-unfetch": "^3.0.0",
    "jest": "^25.2.1",
    "moment": "^2.26.0",
    "next": "^9.4.2",
    "next-with-apollo": "^5.0.0",
    "nookies": "^2.4.0",
    "nprogress": "^0.2.0",
    "path": "^0.12.7",
    "phone": "^2.4.15",
    "pluralize": "^8.0.0",
    "prop-types": "^15.7.2",
    "query-string": "^6.12.1",
    "react": "^16.13.1",
    "react-content-loader": "^5.0.4",
    "react-copy-to-clipboard": "^5.0.2",
    "react-credit-cards": "^0.8.3",
    "react-dom": "^16.13.1",
    "react-draft-wysiwyg": "^1.14.5",
    "react-google-login": "^5.1.21",
    "react-google-recaptcha": "^2.1.0",
    "react-grid-system": "^7.1.1",
    "react-notifications-component": "^2.4.0",
    "react-scroll": "^1.7.16",
    "react-social-login": "^3.4.6",
    "react-spring": "^8.0.27",
    "react-table": "^7.0.4",
    "react-youtube": "^7.11.2",
    "reactjs-popup": "^1.5.0",
    "recharts": "^1.8.5",
    "styled-components": "^5.0.1",
    "styled-system": "^5.1.5",
    "subscriptions-transport-ws": "^0.9.17",
    "universal-cookie": "^4.0.3"
  },
  "devDependencies": {
    "@types/node": "^12.12.21",
    "@types/react": "^16.9.16",
    "@types/react-dom": "^16.9.4",
    "@types/styled-components": "^5.0.1",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-typescript-prettier": "^2.1.0",
    "globby": "^11.0.1",
    "pm2": "^4.4.0",
    "prettier": "^2.0.5",
    "typescript": "3.7.3"
  },
  "license": "ISC"
}
```

3. **Next.js Config:**
```js
require('dotenv').config()

const withSourceMaps = require('@zeit/next-source-maps')

module.exports = withSourceMaps({
  env: {
    PROPAGATEAT_GA_TRACKING_ID: process.env.PROPAGATEAT_GA_TRACKING_ID,
    // many more...
  },
  webpackDevMiddleware: config => {
    config.watchOptions = {
      poll: 1000,
      aggregateTimeout: 300,
    }
    
    return config
  },
  webpack: (config, { isServer }) => {
    if (isServer) {
      require('./scripts/generateSitemap')
    }

    return config
  }
})
```

4. **Nginx Site Conf**
```
server {
    listen 80;
    listen [::]:80;
    server_name propagate.at www.propagate.at;
    return 301 https://$server_name$request_uri;
}

server {
        root /var/www/propagate.at/html;
        index index.html index.htm index.nginx-debian.html;
        server_name propagate.at www.propagate.at;
        proxy_buffers 16 32k;

    proxy_buffer_size 64k;
    proxy_busy_buffers_size 128k;
    proxy_cache_bypass $http_pragma $http_authorization;
    proxy_connect_timeout 59s;
    proxy_hide_header X-Powered-By;
    proxy_http_version 1.1;
    proxy_ignore_headers Cache-Control Expires;
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504 http_404;
    proxy_no_cache $http_pragma $http_authorization;
    proxy_pass_header Set-Cookie;
    proxy_read_timeout 600;
    # re-write redirects to http as to https, example: /home
    proxy_redirect off;
    proxy_send_timeout 600;
    proxy_temp_file_write_size 64k;
    proxy_set_header Accept-Encoding '';
    proxy_set_header Cookie $http_cookie;
    proxy_set_header Host $host;
    proxy_set_header Proxy '';
    proxy_set_header Referer $http_referer;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Original-Request $request_uri;

        access_log /var/log/nginx/propagate.at_access.log;
        error_log /var/log/nginx/propagate.at_error.log;

        # http://localhost:3000 is the Next.js app
        location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_ssl_server_name on;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect http:// https://;
        }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl default_server; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/propagate.at/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/propagate.at/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

> `http://localhost:3000` in the Nginx config is for the Next.js app.

## Expected behavior

I was expecting zero-downtime deployment but that ain't happening due to the above Next.js error.

## System information

- OS: Ubuntu v18.04.3 LTS
- Version of Next.js: v9.4.2
- Version of Node.js: v14.4.0

## Additional context

This is really weird, would love to get some guidance! 👍
