### DISCUSSION TITLE
Get `next/image` working with CSS Grid Full Bleed Layout?

### DISCUSSION THREAD

**Discussion by deadcoder0904** [vercel/next.js#18947] [Help] [answered]
I'm trying to follow this tutorial → https://joshwcomeau.com/css/full-bleed/

Here's the TL;DR:

```css
.grid--wrapper {
	display: grid;
	grid-template-columns: 1fr min(65ch, calc(100% - 64px)) 1fr;
	column-gap: 32px;
}

.grid--wrapper > *,
.header {
	grid-column: 2;
}

.full-bleed {
	width: 100%;
	grid-column: 1 / -1;
}
```

It follows Medium-like design with images bleeding towards the edges of the browser.

And it has a `full-bleed` class for Image:

```css
.full-bleed {
	width: 100%;
	grid-column: 1 / -1;
}
```

I am really not sure how to make my `next/image` work with this kind of stuff?

My `Img.tsx` file looks like:

```tsx
import Image from 'next/image'
type ImageProps = any

export const Img = ({ className = '', ...props }: ImageProps) => (
	<Image className={`${className} full-bleed`} width="100%" {...props} />
)
```

And my `components/mdx/index.ts` looks like:

```ts
import { H1 } from '@/components/mdx/H1'
import { H2 } from '@/components/mdx/H2'
import { H3 } from '@/components/mdx/H3'
import { H4 } from '@/components/mdx/H4'
import { H5 } from '@/components/mdx/H5'
import { H6 } from '@/components/mdx/H6'
import { Img } from '@/components/mdx/Img'
import { Pre } from '@/components/mdx/Pre'
import { PreCode } from '@/components/mdx/PreCode'
import { P } from './P'

export const MDXComponents = {
	h1: H1,
	h2: H2,
	h3: H3,
	h4: H4,
	h5: H5,
	h6: H6,
	p: P,
	img: Img,
	pre: Pre,
	'pre.code': PreCode,
}
```

My `.mdx` files contain normal HTML `img` tags which will use `Img` component as written above (which internally uses `next/image`)

How do I get full-bleed layout when I don't have a height? I can't even get `layout="fill"` to work properly. It just overlaps images on top of each other.

Any ideas???

**Comment by deadcoder0904** [comment]
Can anyone answer this one?

It works fine when I use `img`

`next/image` fucks it up :(

**Reply by jensmeindertsma** [reply]
Have you tried wrapping the Next image component in a div and style that?

**Reply by deadcoder0904** [reply]
@jensmeindertsma doesn't work. I changed https://codesandbox.io/s/tailwind-blog-css-grid-ougks?file=/src/components/Post.js to use

```js
const mdxComponents = {
  img: ({ className = "", ...props }) => (
    <div className="full-bleed"><Image className={`${className}`} {...props} /></div>
  ),
  ...
}
```

instead of

```js
const mdxComponents = {
  img: ({ className = "", ...props }) => (
    <Image className={`${className} full-bleed`} {...props} />
  ),
  ...
}
```

And the result was the same so I changed it back :)

**Reply by jensmeindertsma** [reply]
Where are you defining the full-bleed class?

**Reply by deadcoder0904** [reply]
@jensmeindertsma inside `tailwind.css` → https://codesandbox.io/s/tailwind-blog-css-grid-ougks?file=/src/css/tailwind.css

**Reply by gtodd876** [reply]
I noticed that you have the `width` prop in the new next <Image> component set to 100% but it has to be a string or number as a pixel value.

I'm in the same position as you trying to use the new Image component in a css grid layout with images set to 100% so the ratio is maintained and the images scale based on screen width. I've been experimenting using layout=fill and all the object-fit and object-position values and so far I can't emulate the behavior of the picture element with image at 100%....even with a wrapping parent div set to `position:relative` since Next.js is using absolute positioning under the hood with this component. I'll update the thread if I figure out something that works.

**Reply by deadcoder0904** [reply]
@gtodd876 thanks for the tip about `width`. I'll also update this thread if something works but currently, I am just using the normal `img` tag to make the full-bleed layout work 🎉

**Reply by Dibitybopty** [reply]
Have you guys had any luck with this? My grid layout looks pretty awful with next image, seems like the only solution so far is to go back to using img.

Edit: Thought it best I'd show the difference between the next image and normal img.
https://i.imgur.com/tSOvANE.png

The first image is next's image, and the others regular.

**Reply by gtodd876** [reply]
Yes, I did for my use case. I ended up going with the intrinsic layout and setting width and height to the dimensions of the native photo to provide the aspect ratio. This gave me the same behavior as before. Intrinsic allows the image to shrink within the container but not scale up beyond the native resolution of the image.
material design grid example: 

```jsx
<div classname="mdc-layout-grid__cell mdc-layout-grid__cell--span-8-tablet mdc-layout-grid__cell--span-6-desktop>
  <Image
    src="./example.png"
    alt="example"
    width={632}
    height={500}
  />
</div>
```
Looks like from the images you shared for your use case the aspect ratio of the native photo has a longer width than height. Also looks you want to fit them into squares so might be best to around with the values in `objectPosition` with something like this:
```jsx
<Image
  layout="fill"
  objectFit="cover"
  objectPosition="15% center"
/>
```
for the object position prop/attribute your passing in a string that has the x-axis and y-axis offsets separated by a space. In the example above I'm moving the image 15% to the left and centering on the y-axis. To find the right values for `objectPosition` I like to inspect the image and enter the objectPosition values "0% 0%" in the styles dev tools then when the cursor is on each "0%" you can use the arrow keys on your keyboard to quickly raise or lower than values to dial in the perfect combo.

**Reply by Dibitybopty** [reply]
That's awesome, thanks Todd. You're absolutely right I was using intrinsic, changing to layout='fill' has fixed the issue. Thanks also for the position tip!

**Reply by deadcoder0904** [reply]
ha I still don't have a solution to this problem

**Comment by deadcoder0904** [comment, marked as answer]
I found an answer thanks to https://dev.to/tanahmed/next-image-make-image-fill-available-space-272o

All I had to do was change my markup to:

```tsx
import Image, { ImageProps } from 'next/image'

export const Img = ({ className = '', ...props }: ImageProps) => (
	<div className="unset-img full-bleed">
		<Image className={`${className} custom-img`} layout="fill" {...props} />
	</div>
)
```

And change my CSS to:

```css
.grid--wrapper {
	display: grid;
	grid-template-columns: 1fr min(65ch, calc(100% - 64px)) 1fr;
	column-gap: 32px;
}

.grid--wrapper > *,
.header {
	grid-column: 2;
}

.full-bleed {
	width: 100%;
	grid-column: 1 / -1;
}

.half-bleed {
	width: 75%;
	margin-left: auto;
	margin-right: auto;
	grid-column: 1 / -1;
}

.wrapper {
	width: min(60ch, calc(100% - 64px));
}

.custom-img {
	object-fit: contain;
	width: 100% !important;
	position: relative !important;
	height: unset !important;
}

.unset-img {
	width: 100%;
}
.unset-img > div {
	position: unset !important;
}
```
