### DISCUSSION TITLE
Shared ISR cache

### DISCUSSION THREAD

**Discussion by itome** [vercel/next.js#19589] [Help] [answered]
# Feature request
Currently nextjs seems to store ISR page and data cache in memory.
https://github.com/vercel/next.js/blob/9f07d2dcfb9f59a1446d19b94ced64ea4cb55d4d/packages/next/next-server/server/next-server.ts#L1370

When deploying nextjs server on multiple server, ISR cache is stored per instance.
I think it's more efficient to keep the cache out ex) Redis, memcached

## Describe the solution you'd like
Configurable ISR cache (in-memory / redis / memcached etc)

## Describe alternatives you've considered
Custom cache middleware which has get/set funcitons.

**Comment by jamesarosen** [comment]
This is important when deploying and rolling-back applications. 

In the Incremental Static Regeneration docs, [§ISR: Not Just Caching](https://vercel.com/docs/concepts/next.js/incremental-static-regeneration#isr:-not-just-caching) says

> ISR is designed to persist your generated pages between deployments. This means you are able to rollback instantly and not lose your previously generated pages.

but I don't see how that would work when running Next.js in something like EC2 or Heroku. There's no file storage that would persist across deployments.

https://github.com/reboxer/next-storage-provider aims to solve the problem, but notes that the APIs it uses are not stable and it isn't recommended for production use.

**Comment by stigkj** [comment]
The "proper" way to do this in Next.js is, as far as I know, to have a caching CDN in front. This means you won't have to share the ISR cache as it is already cached at the CDN layer.

**Comment by jamesarosen** [comment]
> The "proper" way to do this in Next.js is, as far as I know, to have a caching CDN in front

This is, in theory, an excellent approach. Unfortunately, it's very difficult to do with Next.js's current ISR implementation.

The problem is that you have two competing goals:


### Support Deploys & Rollbacks
We want to cache `.json` files "forever" so they're available after deploys and rollbacks. ("Forever" just means long enough that all the stale clients go away. Let's say it's 1 week, or 604800 seconds.) We can do this with the following:
```
Cache-Control: public, max-age=0, s-maxage=604800
```
This tells browsers not to cache the files (`max-age=0`), but tells the CDN to cache for 1 week (`s-maxage=604800`).


### Keep the Site Fresh
The reason Next.js incrementally rebuilds the site every so often is that upstream data changes over time. We want the site to reflect these changes. Caching the site in the CDN is no good if you're showing yesterday's headlines or out-of-stock inventory. For this, we want a short cache lifetime (TTL). Let's say it's fine for the site to be 5 minutes out-of-date:
```
Cache-Control: public, max-age=0, s-maxage=300
```

### The Conflict
If we use a short TTL like `s-maxage=300` then the `.json` files will fall out of cache after 5 minutes. Stale clients will get 404s for the files that are no longer available in either the CDN or in origin.

### Active Purging

CDNs like Fastly and Cloudflare solve this problem by using an "active purge" strategy. Next.js would use long TTLs like `s-maxage=604800` and then notify the CDN that the content has expired whenever it writes a rebuild. The files from previous deploys wouldn't get rebuilt, so they wouldn't get purged.

But as far as I know, Next.js doesn't have a hook that we could use to send a purge notification.

**Comment by jamesarosen** [comment]
As an aside, you might think that the `stale-if-error` or `stale-while-revalidate` cache-control directives might help here. Sadly, they do not.

`stale-if-error` only kicks in if the upstream server returns a 5xx response. In this case, the Next.js server is running and responding. It's just returning a 404 for the `.json` resources that are now gone.

`stale-while-revalidate` tells the downstream cache (the CDN) to kick off an upstream request for the `.json` resource and, while that request is pending, serve a stale response for any requests. So for whatever amount of time it takes the CDN to contact Next.js and get a 404 back, it'll serve stale responses, which I guess helps a _tiny bit_, but we're talking less than a second.

**Reply by stigkj** [reply]
Not sure I understand why you would get a 404 here. I.e.
  1. I request `.../product/1` and it is served from the Next.js app and cached in the CDN
  2. The page is rebuilt on a new deploy
  3. I request `.../product/1` and it is servced from CDN
  4. The page is marked as stale in the CDN
  5. I request `.../product/1` and it is served from the Next.js app and cached in the CDN
 
By using `stale-while-revalidate` the 5. step would become:
 - I request `.../product/1` and it is served from CDN as stale 
 - The CDN will fetch the content from the Next.js app and cache it ready for the next request

What am I missing here?

**Comment by jamesarosen** [comment]
Try it this way:

1. You deploy v1 to origin. It generates links like `/_next/data/wqa5wSjJBslSs5Sr6fqtc/products/1` (where `wqa5wSjJBslSs5Sr6fqtc` is a hash for version 1)
2. User loads the page, causing a fetch for `/_next/data/wqa5wSjJBslSs5Sr6fqtc/products/1` and CDN caches it
3. You deploy v2 to origin. It generates links like `/_next/data/ds2fqtc45SjJNn7rT9aSS/products/1` (where `ds2fqtc45SjJNn7rT9aSS` is a hash for version 2)
4. Without reloading, user navigates to a new page, which causes a fetch for `/_next/data/wqa5wSjJBslSs5Sr6fqtc/products/2`. That either wasn't cached in the CDN or has since expired. The CDN makes an upstream request to origin, but origin has data with the hash `ds2fqtc45SjJNn7rT9aSS`, not `wqa5wSjJBslSs5Sr6fqtc`, so it returns a 404.

I think what you're missing is that `.../product/1` in your step 1 and `.../product/1` in your step 5 are actually different URLs because of the version hashing.

**Reply by stigkj** [reply]
Aaah...I did not realize you were talking about stale clients 😜

**Reply by stigkj** [reply]
I guess it can also be handled on the client, i.e. reload the page when a 404 is returned. But as far as I know there is no such API to support that in Next.js

**Reply by stigkj** [reply]
I wonder how Vercel does this...

**Reply by jamesarosen** [reply]
> I guess it can also be handled on the client

I don't think my application code has access to the XHR/fetch that Next.js uses to get the precompiled JSON, but if Next.js were to emit an event, I could hook into that. That's definitely an option.

**Comment by leerob** [comment]
Hey! We now have some documentation about this.

https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#self-hosting-isr

**Reply by ash1425** [reply]
Thank you. This looks quite abstract though. Do we have little detailed explanation on how to self host isr ?
Details like which is the directory to be shared ? is it whole .next ?

**Reply by shadiramadan** [reply]
Yes, some extra details are much needed on that page!
Definitely feels like FOSS is second-class when it comes to any documentation around scaling Next.js without Vercel.
Which specific `.next` subdirectories are safe to share between NextJS pods (which might even have different code versions)?  Only the `cache/` folder?  What about `server/pages/`?

**Reply by shadiramadan** [reply]
Is the whole `.next/` folder safe?

**Reply by SaschaVanEssen** [reply]
I am wondering the same. @ash1425 @shadiramadan did you try with the whole `.next` folder and did it work?

**Reply by ash1425** [reply]
We ultimately decided to not worry about sharing .next across instances. We now invalidate cache whenever new content is published by visiting all affected urls on all instances.
We have automated this flow with our CMS, whenever new content is published, related paths are invalidated on all instances on AWS using their private IP address. We run a lambda to achieve this task.

**Reply by nicholas-c** [reply]
@ash1425 Just for some clarity, you're running NextJS in K8's instances, and then using the lambda to ping each one and clear it's individual cache?

How come this was the chosen solution over a shared cache? 😄 We're starting to explore these solutions right now!

**Reply by philipplaeubli** [reply]
@nicholas-c we have some experience with running Next.js in K8 (OpenShift) and use the shared volume approach - this works, although it would be much easier for us if the ISR cache could be configured (storage location). We have the additional restriction that our docker images are running in read-only mode, so we had to find a solution anyway in order to get ISR to work.

**Reply by ash1425** [reply]
Apologies for missing an important detail. We have nextjs11. We use ECS fargate and not k8s. With ECS fargate, mount sharing is bit complicated and s3 is not an option there hence the workaround of hitting affected urls to rebuild new version of them.

With nextjs12 onwards, we can also invalidate urls using specific api instead of hitting urls for that purpose.

**Reply by mavr1k** [reply]
> @nicholas-c we have some experience with running Next.js in K8 (OpenShift) and use the shared volume approach - this works

Hey @philipplaeubli! Which directories did you shared across pods?

I'm currently trying to have a shared and persistent ISR cache across pods, but struggling how I should to initiate persistent volume from the rocker image and which folders I should to share.

**Reply by themagickoala** [reply]
@mavr1k I'm also in this boat right now. Our API layer is just a proxy to an external service, so we don't have the context of which pages to revalidate. To get around this, we're running a MQ subscriber to pick up events telling us what needs revalidating, which then posts to a generic revalidate endpoint within our app. However, we either need to share the cache between pods somehow, or make sure we bust the cache on each pod.

Did you get this to work in the end? @philipplaeubli  are you able to share your solution? @leerob is there a timeline on when customising the shared ISR cache (e.g. file storage location, or even an external service like Redis) might be considered? I know the Vercel platform is your priority, but the rest of us could really do with more clarity on this use case!

**Reply by mavr1k** [reply]
Hi @themagickoala, eventually I was able to successfully run that. The `.next` folder has been mounted in a PV between pods, and everything is functioning now.

Here is the k8s deployment example:
```yaml
# next.js client app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      initContainers:
        - name: init
          image: client
          imagePullPolicy: Never
          command: ["sh", "-c", "if [ -z \"$(ls -A /data)\" ]; then cp -r /app/.next/** /data; echo 'empty'; else echo 'PV is already initialized'; fi"]
          volumeMounts:
            - name: client-data
              mountPath: /data
      containers:
        - name: client
          image: client
          imagePullPolicy: Never
          resources: {}
          env:
            - name: APP_PORT
              value: "3000"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: client-data
              mountPath: /app/.next
      volumes:
        - name: client-data
          persistentVolumeClaim:
            claimName: client-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
```

> Our API layer is just a proxy to an external service, so we don't have the context of which pages to revalidate.

Handling that situation can be quite challenging. Perhaps the simplest solution would be to implement a basic ISR (revalidation timeout). Alternatively, you could consider creating a separate revalidation service that periodically checks and compares content from the API you are utilizing.

I have decided to simplify the solution by not incorporating PV. Therefore, SSR will be the primary approach used on my end.
