### DISCUSSION TITLE
How can I import SCSS file into component without CSS Modules?

### DISCUSSION THREAD

**Discussion by emelyanov-dev** [vercel/next.js#20400] [Help]
I don't want to use CSS Modules and global styles.

Example:
```
/components/
  | - Button/
       | - Button.scss
       | - Button.js
```
```js
// Button.js
import React from 'react';

import './Button.scss';

....
<button className="Button"></button>
```

**Comment by jserrao** [comment]
The [Next CSS docs](https://nextjs.org/docs/basic-features/built-in-css-support) are pretty clear. You treat the CSS file as an import and your class names become properties you can use in your JSX ([Sass works out of the box in the same way](https://nextjs.org/docs/basic-features/built-in-css-support#sass-support)): 

```css
/*
You do not need to worry about .error {} colliding with any other `.css` or
`.module.css` files!
*/
.error {
  color: white;
  background-color: red;
}
```

```jsx
import styles from './Button.module.scss'

export function Button() {
  return (
    <button
      type="button"
      // Note how the "error" class is accessed as a property on the imported
      // `styles` object.
      className={styles.error}
    >
      Destroy
    </button>
  )
}
```
