### DISCUSSION TITLE
cm-wordpress example - FetchError: invalid json response body at http://localhost:8000/graphql reason: Unexpected token < in JSON at position 0

### DISCUSSION THREAD

**Discussion by andrewabril** [vercel/next.js#20691] [Help] [answered]
Hi,

I'm using the cms-wordpress example here, https://github.com/vercel/next.js/tree/canary/examples/cms-wordpress. I'm trying to get it working with my own Wordpress instance and am getting the error, `FetchError: invalid json response body at http://localhost:8000/graphql reason: Unexpected token < in JSON at position 0`. 

The only file I've changed in the next.js project is removing `.env.local.example` and adding `.env.local` with this variable, `WORDPRESS_API_URL=http://localhost:8000/graphql`.

My Wordpress instance is running through a Docker container using the docker compose file below. The GraphQL plugin is activated and the endpoint is from the GraphQL settings. What could be the issue?

```
version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: xxxxx
       MYSQL_DATABASE: xxxxx
       MYSQL_USER: xxxxx
       MYSQL_PASSWORD: xxxxx
   wordpress:
     depends_on:
       - db
     volumes:
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: xxxxx
       WORDPRESS_DB_PASSWORD: xxxxx
       WORDPRESS_DB_NAME: xxxxx
volumes:
    db_data: {}
```

Thanks!

**Comment by andrewabril** [comment, marked as answer]
For anyone who has this problem, I had to comment out the variables property of the body when querying the Wordpress graphql endpoint until I added the JWT authentication piece.

```
const res = await fetch(API_URL, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      query,
      // variables,
    }),
  })
```

**Comment by kznkv-skillup** [comment]
Hi, I have same problem `FetchError: invalid json response body at http://domain.com/graphql reason: Unexpected token < in JSON at position 0 `. Maybe someone knows the solution?

**Reply by Crelloc** [reply]
**You are receiving that error because your browser cannot access that url.**

I first tested on localhost with a wordpress docker container.  The code works as is (no editing any files except for .env.local).

Be sure to have docker and docker-compose installed on your system:

https://docs.docker.com/compose/install/

The following are two files that you need to properly set up wordpress container (**stack.yml and uploads.ini**) 
### Contents of uploads.in: https://stackoverflow.com/questions/42983276/wordpress-docker-wont-increase-upload-limit

```
file_uploads = On
memory_limit = 500M
upload_max_filesize = 500M
post_max_size = 500M
max_execution_time = 600
```


### Contents of stack.yml:

```
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html # Full wordpress project
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db:
```
### Run Wordpress

`docker-compose -f stack.yml up`

**And then run your nextjs app with the updated .env.local file and install the wpgraphql plugin as described in [README](https://github.com/vercel/next.js/tree/canary/examples/cms-wordpress) directions**


This should work and you should also be able to access the graphql route:

 http://localhost:8080/graphql
