### DISCUSSION TITLE
How to configure Vercel to deploy for a Github release instead of a push to master branch

### DISCUSSION THREAD

**Discussion by thesobercoder** [vercel/next.js#20905] [Help] [answered]
I couldn't find any documentation around how to only deploy to Vercel for let's say production when I create a release instead of push to master. This is important for me because I'm using a monorepo and I most definitely don't want to deploy for all pushes to the master branch.

**Comment by leerob** [comment, marked as answer]
This wouldn't be supported by the native GitHub integration, but you could use the [Vercel CLI](https://vercel.com/docs/cli) directly as part of a GitHub Action (or similar) to deploy when releasing.

**Reply by thesobercoder** [reply]
Thanks! Is there an example implementation I can refer to?

**Reply by beeinger** [reply]
An example would be very much appreciated!

**Comment by dinesh-gamage** [comment]
I am not using GitHub integration, I am using GitHub actions. I am posting this for anyone who comes across this issue in the future. I've included a sample GitHub action below.
```
name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  release:
    types: [published]
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

```
