### DISCUSSION TITLE
Include browserlist with custom webpack config in next.config.js

### DISCUSSION THREAD

**Discussion by ghost** [vercel/next.js#21429] [Help] [answered]
Hello, following the docs [Customizing Target Browsers](https://nextjs.org/docs/advanced-features/customizing-postcss-config#customizing-target-browsers) I added: `"browserslist": [">0.3%", "not ie 11", "not op_mini all"]` to package JSON.

`npx browserslist ">0.3%, not ie 11, not op_mini all"` yields:
```
and_chr 87
and_uc 12.12
chrome 87
chrome 86
chrome 85
edge 87
firefox 84
firefox 83
ios_saf 14.0-14.3
ios_saf 13.4-13.7
ios_saf 13.3
ios_saf 12.2-12.4
opera 72
safari 14
safari 13.1
samsung 13.0
samsung 12.0
```

With this information and the `browserlist` key set up, I wasn't expecting some prefixes on the build folder (out) of my static site. The one that stands out is `-moz-calc()`, which is old and not necessary anymore.

Example:
```css
/* input */
.contain {
    max-width: calc((9 * 75 / 16 * 1rem) + (8 * 20 / 16 * 1rem));
    margin: 0 auto;
}
/*output*/
.contain {
    max-width: -moz-calc((9 * 75/16 * 1rem) + (8 * 20/16 * 1rem));
    max-width: calc((9 * 75 / 16 * 1rem) + (8 * 20 / 16 * 1rem));
    margin: 0 auto;
}
```

My package.json:
```json
{
"browserslist": [">0.3%", "not ie 11", "not op_mini all"],
  "devDependencies": {
    "@types/node": "^14.14.21",
    "@types/react": "^17.0.0",
    "typescript": "^4.1.3"
  },
  "dependencies": {
    "@prefresh/next": "^1.3.0",
    "next": "^10.0.5",
    "next-plugin-preact": "^3.0.3",
    "preact": "^10.5.10",
    "preact-render-to-string": "^5.1.12",
    "react": "npm:@preact/compat@0.0.4",
    "react-dom": "npm:@preact/compat@0.0.4",
    "react-icons": "^4.1.0",
    "react-ssr-prepass": "npm:preact-ssr-prepass@^1.1.2"
  },
}
```
