### DISCUSSION TITLE
After build NextJS project with css.modules, styles set after composes does not work

### DISCUSSION THREAD

**Discussion by stovv** [vercel/next.js#21455] [Help]
I have class CommonContainer in styles/Containers.module.css
```css
.CommonContainer {
    max-width: 1440px;
    margin: 0 auto 72px auto;
    padding-left: 80px;
    padding-right: 80px;
}
```
And I compose it to another class
```css
.topPostContainer {
    composes: CommonContainer from "../../styles/Containers.module.css";
    margin-top: 56px;
}
```

But after NextJS building "margin-top: 56px;" not sets into component with .topPostContainer In safari console I view
![](https://i.stack.imgur.com/Rdz9M.png)
This only happens after the project has been built.

In developer mode I have
![](https://i.stack.imgur.com/1vzXH.png)

What could go wrong and how to fix it? Maybe someone has encountered something like this
