### DISCUSSION TITLE
Multiple layouts in NextJS or conditional css import

### DISCUSSION THREAD

**Discussion by PlopTheReal** [vercel/next.js#22136] [Help]
I’m working on moving legacy app to Nextjs. The app has two layouts: public and admin part. Every layout has it’s own css files. Because of the nextjs restrictions when you can import css only in custom _app.js file I can’t split layouts. I don’t want to include admin css to the public layout and vice versa and the modules solution will be a problem as I have quite large CSS with a bunch of rules that aren't pure. 

I'm importing the public css such as 
```
import '../styles/public.scss';
```
Then for the admin layout I've tried to add the CSS manually like:
```
{this.props.admin && <link rel="stylesheet" href="admin.css" />}
```
But the admin styles are placed after the public styles within the header.
What can I do in this scenario? Also is there is a way to customize the placement of the styles from webpack?

**Comment by meliborn** [comment]
Absolutely the same case. I thought it's very common case when you have admin and public part with different css, but I still can't find a solution :(

**Reply by jwugit** [reply]
Try either the built in module CSS/scss to limit it to your layout component.

Or use styled components also works

**Reply by meliborn** [reply]
There are no components, it's just a big css file with global rules which I need to include only in admin part (url starts from /admin)

**Reply by eyalcohen4** [reply]
Have you found a workaround?

**Reply by vikasg603** [reply]
This is a common case scenario, and there must be a solution for it with an internal css loader.
There is a solution using styled-jsx, but then again, as it creates internal CSS rather than external CSS files, it will be not good from caching point of view.

**Reply by Noitidart** [reply]
Did anyone find a solution yet? I was thinking of using react-frame but it's a work-around https://swiftcarrot.dev/react-frame

**Reply by ppyrzanowski** [reply]
It would be nice if we could have multiple global.css and specify multiple global contexts where it does a complete full page reload when switching between global contexts. [Multi-zones](https://nextjs.org/docs/advanced-features/multi-zones) could help but not sure about the reusability of components between "zones".

**Comment by mizdra** [comment]
In my opinion, the following three features are needed to make this work.

1. process Global CSS with css-loader, but not automatically insert it into the head element
    - Import CSS files from `_app.js` with an import statement to take advantage of Next.js' built-in CSS optimization
    - However, it does not automatically insert it into the head element.
2. Insert Global CSS at runtime
    - Allow the user to decide which stylesheet to insert based on runtime information
    - Probably use the Head component of `next/head` and the link tag.
3. Provide a way to get the URL of the built CSS file at runtime
    - Normally, CSS file names change frequently due to Cache Busting
    - On the other hand, if you don't know the name of the file, you cannot embed the stylesheet in a link tag.

Example (NOTE: This code is from my imagination and is not official):
```tsx
import { useRouter } from 'next/router';

// The D mode in https://github.com/webpack/webpack/issues/14893
// But, this mode is not implemented yet.
const commonSheetUrl = new URL('../styles/common/global.css', import.meta.resolve);
const adminSheetUrl = new URL('../styles/admin/global.css', import.meta.resolve);

function App({ Component, pageProps }) {
  const { asPath } = useRouter();
  const isAdmin = asPath === '/admin';
  return (
    <>
      <Head>
        {!isAdmin && <link rel="preload" href={commonSheetUrl} as="style" />}
        {!isAdmin && <link rel="stylesheet" href={commonSheetUrl} />}
        {isAdmin && <link rel="preload" href={adminSheetUrl} as="style" />}
        {isAdmin && <link rel="stylesheet" href={adminSheetUrl} />}
      </Head>
      <Component {...pageProps} />
    </>
  );
}
```

My gut feeling is that it would be difficult to solve this problem with a user-side workaround, and it appears that improvements to the Next.js build system are needed.

**Comment by mizdra** [comment]
Loading unnecessary style sheets cannot be avoided, but the style sheets can be scoped to minimize their impact. Depending on the use case, this workaround may be available.

```tsx
// pages/_document.tsx

import Document, { Html, Head, Main, NextScript, DocumentContext, DocumentInitialProps } from 'next/document';
import { ReactElement } from 'react';

type MyDocumentProps = {
  theme: 'common' | 'admin';
};
type MyDocumentInitialProps = MyDocumentProps & DocumentInitialProps;

export default class MyDocument extends Document<MyDocumentProps> {
  static async getInitialProps(ctx: DocumentContext): Promise<MyDocumentInitialProps> {
    const initialProps = await Document.getInitialProps(ctx);
    const pathname = ctx.req?.pathname;
    const theme = pathname === '/admin' ? 'admin' : 'common';
    return { ...initialProps, theme };
  }

  render(): ReactElement {
    return (
      <Html data-theme={this.props.theme}>
        <Head />
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}
```

```tsx
// pages/_app.tsx
import '../styles/common/global.scss';
import '../styles/admin/global.scss';

function App({ Component, pageProps }) {
  // ...
}
```

```scss
// styles/common/global.scss

// NOTE: The level of detail has been increased from 1 to 11
// because of the combination of attribute selectors and element selectors.
// This may result in unexpected style overrides.
[data-theme='common'] {
  body {
    background: 'blue';
  }
}

// You can use `:where` to reduce the level of detail.
// NOTE, however, that this is not supported in Safari 13.x and below.
// ref: https://developer.mozilla.org/en-US/docs/Web/CSS/:where
// :where([data-theme='common']) {
//   body {
//     background: 'blue';
//   }
// }
```

```scss
// styles/admin/global.scss

// NOTE: The level of detail has been increased from 1 to 11
// because of the combination of attribute selectors and element selectors.
// This may result in unexpected style overrides.
[data-theme='admin'] {
  body {
    background: 'red';
  }
}

// You can use `:where` to reduce the level of detail.
// NOTE, however, that this is not supported in Safari 13.x and below.
// ref: https://developer.mozilla.org/en-US/docs/Web/CSS/:where
// :where([data-theme='admin']) {
//   body {
//     background: 'red';
//   }
// }
```
