### DISCUSSION TITLE
How to use Global Styles with SCSS?

### DISCUSSION THREAD

**Discussion by wiktoriavh** [vercel/next.js#22371] [Help] [answered]
Hello!

I first had the problem, that I could not use un-pure selectors in Scoped styling, so I discovered this Discussion in here (https://github.com/vercel/next.js/discussions/17089), which said to use global styles. The example that was provided uses CSS and JS, I use SCSS and TSX.

My `_app.tsx` looks like this:
```ts
import "../components/SCSS/variables/AllVariables.module.scss";

export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />
}
```
> I have tried both `AllVariables.module.scss` and `AllVariables.scss`, both do not work.

And the Stylesheet I am importing looks like this:
```scss
@use "./breakpoints" as *;
@use "./changeable-settings" as *;
@use "./fixed-settings-color" as *;
@use "./fixed-settings-font" as *;
@use "./fixed-settings-grid" as *;
@use "./headings" as *;
@use "./zindex" as *;
```

I first tried to just import all the styles inside the `_app.tsx` file, but that didn't work. So I put them all inside a stylesheet, thinking that maybe I can only import one stylesheet inside the TSX file. But that doesn't work either!
Here are some examples of what the styles I am using in my stylesheet look like:
```scss
$sm: 600px; // tablet
$md: 900px; // laptop
$lg: 1200px; // desktop
$xl: 1500px; // large desktop
$xxl: 3000px; // 4K desktop
```
```scss
:root {
  /* [Font Settings] */
  --xs-font-size: 0.6rem;
  --sm-font-size: 0.8rem;
  --reg-font-size: 1rem;
  --md-font-size: 1.2rem;
  --lg-font-size: 1.4rem;
  --xl-font-size: 1.6rem;
}
```

**What am I doing wrong?** According to the discussion I linked above, it should work. And according to [this documentation](https://nextjs.org/docs/basic-features/built-in-css-support#sass-support), SCSS should work fine. My Scoped Styles work perfectly. I did install `sass`.
