### DISCUSSION TITLE
warn  - No build cache found. Please configure build caching for faster rebuilds

### DISCUSSION THREAD

**Discussion by shahinghasemi** [vercel/next.js#22492] [Help]
Hello, When I execute CI pipeline for `Next.js` it warns me with this message: 
`warn  - No build cache found. Please configure build caching for faster rebuilds`
 I want to cache `Next.js` build stuff so improve build time for the next time, I used `drone` for CI pipeline and this is the pipeline:

```
kind: pipeline
type: docker
name: NIGHTLY-FRONTEND-BUILDS
workspace:
  base: /projects/
  path: lernito-exam/
steps:
  - name: Build project and story book
    image: node:14
    pull: always
    volumes:
      - name: npm-cache
        path: /npm-cache
      - name: next-cache
        path: /.next/cache
    environment:
      NODE_CONFIG_ENV: drone
    commands:
      - npm config set cache /npm-cache --global
      - npm run drone:ci -- frontend
trigger:
  branch:
    - master
  event:
    - push
    - pull_request
volumes:
  - name: npm-cache
    host:
      path: /npm-cache
  - name: next-cache
    host:
      path: /next-cache
```
However it doesn't work(cache) and don't know why.
