### DISCUSSION TITLE
Kubernetes - multiple pods

### DISCUSSION THREAD

**Discussion by eglaost** [vercel/next.js#23017] [Help] [answered]
Hi,
Does ISR works with kubernetes and multiple pods?
In our tests every request (after the given revalidation period) hits a different pods. As a result if page build is not initiated for the specific pods the returned static page is the one with the old content. Example:

Let's assume a revalidation period of 5 seconds.
Old Content = X
New Content = Y

Lets say each page request is done 5 seconds after the previous one.

First page request -> Pod 1 -> Next.js serves X and builds new static page with content Y.
Second page request -> Pod 1 -> Next.js serves Y
Third page request -> Pod 2 ->  Next.js serves X and builds new static page with content Y.

So in this case the user will see content X, after 5 seconds Content Y and after 5 seconds content X again.

We have also tried to mount an external volume so that all pods share the same build directory

Is there a workaround? Which is the best practice when working with multiple pods?

Thanks

**Comment by sherifabdlnaby** [comment]
I believe that there's no way around this but to have a common block store that NextJS servers saves the last version of the page in, and this is the one that gets served. You won't be able to achieve syncing between the multiple replicas. (not with some sophisticated distributed systems algorithms which is overkill)

**Comment by sherifabdlnaby** [comment]
I am interested in knowing about how people have approached this problem

**Comment by VinayaSathyanarayana** [comment]
An example to use a common storage mechanism will be helpful.

**Comment by pekkai-solteq** [comment]
Problematic thing with this is that Next uses in-memory caching for storing the statically rendered page and only after that looks for updates on the disk. So even if we have horizontally scaled a bunch of pods with a shared build folder, the revalidation would only effectively update the content on a single node (unless the cache is full of course).

See: https://github.com/vercel/next.js/blob/canary/packages/next/next-server/server/incremental-cache.ts#L115-L122

Would be pretty convenient to be able to disable the LRUCache altogether, so that the pods would always read directly from the disk.

**Comment by pekkai-solteq** [comment]
I created a new RFC related to this, see https://github.com/vercel/next.js/discussions/26247

**Comment by PsyGik** [comment]
> We have also tried to mount an external volume so that all pods share the same build directory

Do you mind sharing how you did this please?

**Comment by jarre1987** [comment]
I'm interested too

**Comment by realmunk** [comment]
Any updates here? Would be nice with a best practice recipe.

**Comment by a-pedroso** [comment]
Any news on this topic? 
Thanks

**Comment by philwolstenholme** [comment]
Is this any help: https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration#self-hosting-isr ?

You can disable the ISR memory cache, but there's a warning:

> You might need to consider a race condition between multiple pods trying to update the cache at the same time, depending on how your shared mount is configured.

**Comment by a-pedroso** [comment]
I manage to make this work but only for the full `/app` folder mapped to a volume mount. 

So, 1st, as @philwolstenholme mentioned, we need to disable ISR memory cache by adding the following code in the `next.config.js` 
This makes next.js rely only on the filesystem when getting static files.
```
  experimental: {
    // Defaults to 50MB
    isrMemoryCacheSize: 0,
  },
```

Next, we need to use a shared filesystem to map and use a volume mount for our docker container. 
Since we are using revalidation we need a file system that supports ReadWriteManyaccess. 
Since I'm using Azure, we use File Share from Storage Account (the only that I found it works with ReadWriteMany, correct me if I'm wrong)

For this we use the CSI (Container Storage Interface) in k8s.

To enable it in the cluster you need to run 
```shell
az aks update -n CLUSTER-NAME -g RESOURCE-GROUP-NAME --enable-file-driver
```
ref: https://learn.microsoft.com/en-us/azure/aks/csi-storage-drivers#enable-csi-storage-drivers-on-an-existing-cluster

Next, we need to create a Persistent Volume Claim.
We use the approach to create it dynamically. 
ref: https://learn.microsoft.com/en-us/azure/aks/azure-files-csi#dynamically-create-azure-files-pvs-by-using-the-built-in-storage-classes

So, using the out-of-box azurefile-csi Storage Class (check documentation above), we can have the following k8s manifest:

``` 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: my-namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi
```
And apply it 
```shell
kubectl apply -f my-pvc.yml
```
This will create for you a storage account under the node resource group of the k8s cluster connected to this PVC.

With this in place, all that is missing is to add the volume and container volume mount to make this file share as the central place for our files. 

deployment.yml as follows:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui
  namespace: my-namespace
  labels:
    app: app-ui
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app-ui
  template:
    metadata:
      labels:
        app: app-ui
    spec:
      containers:
        - name: app-ui
          image: uggregistry.azurecr.io/app-ui:v1.0.0
          ports:
            - containerPort: 3000
          volumeMounts:
          - name: persistent-storage
            mountPath: /app
            subPath: v1.0.0
          env:
            - name: CONTENTFUL_SPACE_ID
              valueFrom:
                secretKeyRef:
                  name: app-env
                  key: CONTENTFUL_SPACE_ID
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: my-pvc
      imagePullSecrets:
        - name: docker-registry-main
      restartPolicy: Always
```
Please note that the contents of the `/v1.0.0` folder inside azure file share should be uploaded to it before applying this deployment. If not the container `/app` will be empty. The contents of this folder are the same as the `next build` command output. Or, if you're using the standalone output as me, you need to upload it accordingly just like the dockerfile steps (ref: https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile#L50)

Cheers 🍻

**Reply by mavr1k** [reply]
What is the `/app` folder here? 🤔
I'm trying now to have shared `.next/cache` and `.next/server/pages` now but receiving a lot of 404 😭

**Reply by a-pedroso** [reply]
@mavr1k below you can find my updated working k8s deployment.
Note that I'm mapping to the PVC the `.next` folder only. 
the `/app` is the folder created in the docker container that contains your app code. But I'm no longer using it that way. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ui
  namespace: my-namespace
  labels:
    app: app-ui
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app-ui
  template:
    metadata:
      labels:
        app: app-ui
    spec:
      containers:
        - name: app-ui
          image: uggregistry.azurecr.io/app-ui:{{VERSION}}
          ports:
            - containerPort: 3000
          volumeMounts:
          - name: persistent-storage
            mountPath: /app/.next
            subPath: "{{VERSION}}/.next"
          env:
            - name: CONTENTFUL_SPACE_ID
              valueFrom:
                secretKeyRef:
                  name: app-env
                  key: CONTENTFUL_SPACE_ID
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: my-pvc
      imagePullSecrets:
        - name: docker-registry-main
      restartPolicy: Always
```
Hope that helps
Cheers
