### DISCUSSION TITLE
Semicolon being stripped from last CSS declaration

### DISCUSSION THREAD

**Discussion by kinetifex** [vercel/next.js#23595] [Help]
### What version of Next.js are you using?

10.0.6

### What version of Node.js are you using?

14.15.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start

### Describe the Bug

Semicolon is removed from last declaration. This causes issues with additional parsing by postcss processing.

This was noticed in upgrading a Next.js app to v10 using built-in CSS support. Worked previously with v9 and `next-css` plugin.

### Expected Behavior

The last semicolon of a CSS block should remain.

### To Reproduce

Install and configure [webpack-rtl-plugin](https://www.npmjs.com/package/webpack-rtl-plugin) for the app.

Input CSS:
```css
.example {
    float: left;
    color: red /*!rtl:blue*/;
    border-color: green /*!rtl:yellow*/;
}
```

Output:
```css
.example {
    float: right;
    color: blue;
    border-color: green
}
```

Notice the last directive is not handled due to the missing semicolon.

Expected:
```css
.example {
    float: right;
    color: blue;
    border-color: yellow;
}
```

Not retaining the last semicolon causes issues with additional `postcss` processing, such as with [webpack-rtl-plugin](https://www.npmjs.com/package/webpack-rtl-plugin). With this plugin in particular, [value directives](https://rtlcss.com/learn/usage-guide/value-directives/#Example) are to be described as comments in the declaration. Because the semicolon is missing, they are not parsed as part of the declaration.
