### DISCUSSION TITLE
[FEATURE] Support tsconfig alias paths from css and scss url("")

### DISCUSSION THREAD

**Discussion by MaxmaxmaximusAWS** [vercel/next.js#24132] [Ideas]
### Describe the feature you'd like to request

Please add automatic support tsconfig alias paths from css and scss url("")

### Describe the solution you'd like

```js
import styles from 'Menu.module.scss'
```

```scss
.menu {
  background-image: url("@res/images/menu.png")
}
```

### Describe alternatives you've considered

```js
import styles from 'Menu.module.scss'
```

```scss
.menu {
  background-image: url("../../../res/images/menu.png")
}
```
