### DISCUSSION TITLE
Can't use partial function in SCSS module with next.js, need help.

### DISCUSSION THREAD

**Discussion by TsengTofu** [vercel/next.js#25183] [Help]
Hello, I'm new to next.js.
### **What I Want To Do But FAILED:**
**`@use`** is not working fine.
It only work fine when type: `"@use ‘theme.scss’ as *;"`
But this can't use "**namespace**" function and lose the meaning of using **`@use`** to import other stylesheets.
I don't know where I did wrong.
[Reference about @use](https://www.liquidlight.co.uk/blog/use-and-import-rules-in-scss/)

### **Works Fine Part (current):**
1. Use `[componentName].module.scss` with `componentName.js`.
```
import { style } from '..../[componentName].module.scss';
const componentName = (props) => {
  return (
    <div className={style.className in ..../[componentName].module.scss}>
       ....
    </div>
  )
} 
```
2. import `[theme].scss` to `_app.js` (where next.js can be imported some library style). 
3. import `[theme].scss` to other `[componentName].module.scss`, then `[componentName].module.scss` could get the `colorVariable` or some other `@mixin` to use.

### **[next.js version: 10.0.4]**
File `next.config.js` setting below:
```
module.exports = {
  distDir: 'build',
  webpack: (config) => {
    config.module.rules.push({
      test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 8192,
          publicPath: '/build/static/',
          outputPath: 'static/',
          name: '[name].[ext]',
        },
      },
    });
    return config;
  },
};

```

**Comment by wwwdepot** [comment]
You are doing it right if you don't want namespace with `@use` https://sass-lang.com/documentation/at-rules/use

**Reply by TsengTofu** [reply]
@wwwdepot  Thank you for replying me.
I need the function: @namspace, but in my project is not working, and can't figure out why.
In my project:

Define the variable and @mixin in the `theme.scss` file.
```scss
// theme.scss
@mixin FontSetting($font_size, $font_weight, $line_height, $letter_spacing){
  font-family: 'Noto Sans TC';
  font-size: $font_size;
  font-weight: $font_weight;
  line-height: $line_height;
  letter-spacing: $letter_spacing;
}
```
```scss
// _card.module.scss
// This line will work fine - @use './theme.scss' as *;
// This line won't work, but don't know why - @use './theme.scss';
.tooltip {
  background: $tooltip_color;
  @include FontSetting(12px, normal, 1.5, 0.05em);
}
```

 **Expected result - I don't need to type full path of the scss file to use, all I need to type is "the file name, checkout the example below:** 
```scss
// _button.scss
$radius: 0.5rem;
@mixin buttonSmall {
    border-radius: $radius;
    padding: 1rem;
}
```
```scss
// _box.scss
@use 'button';
.boxButton {
    @include button.buttonSmall;
    margin: 1rem + button.$radius;
}
```

Please help if you figure out why, thank you.

**Reply by wwwdepot** [reply]
`@use` automatically set a namespace, to use it without namespace, you have to define it as `@use "<url>" as *`

```scss
// common.scss
$radius: 3px;

@mixin rounded {
  border-radius: $radius;
}

@mixin FontSetting($font_size, $font_weight, $line_height, $letter_spacing) {
  font-family: "Noto Sans TC";
  font-size: $font_size;
  font-weight: $font_weight;
  line-height: $line_height;
  letter-spacing: $letter_spacing;
}

```
### (1) Normal usage

```scss
// style.module.scss
@use './common';

.button {
  @include common.rounded;
  @include common.FontSetting(12px, normal, 1.5, 0.05em);
  padding: 5px + common.$radius;
}
```

### (2) Using `@use '' as *` aka _without_ namespace

> You can even load a module without a namespace by writing `@use "<url>" as *`. We recommend you only do this for stylesheets written by you, though; otherwise, they may introduce new members that cause name conflicts!
> - https://sass-lang.com/documentation/at-rules/use



```scss
// style.module.scss
@use './common' as *;

.button {
  @include rounded;
  @include FontSetting(12px, normal, 1.5, 0.05em);
  padding: 5px + $radius;
}
```
