### DISCUSSION TITLE
PostCSS nesting with CSS variables isn't working in Tailwind CSS & Next.js

### DISCUSSION THREAD

**Discussion by deadcoder0904** [vercel/next.js#25222] [Help] [answered]
I am trying to use PostCSS nesting with CSS variables but it doesn't convert CSS variables at all.

Instead it shows `Invalid property value` in the DOM for CSS Variables.

My `tailwind.css` file contains a bunch of CSS variables:

# tailwind.css

```css
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';

@layer base {
  :root {
    --font-mono: 'Fira Mono, monospace';

    --text-1: '12px';
    --text-2: '14px';

    --colors-black: 'rgba(19, 19, 21, 1)';
    --colors-white: 'rgba(255, 255, 255, 1)';
    --colors-gray: 'rgba(128, 128, 128, 1)';
    --colors-blue: 'rgba(3, 136, 252, 1)';
    --colors-red: 'rgba(249, 16, 74, 1)';
    --colors-yellow: 'rgba(255, 221, 0, 1)';
    --colors-pink: 'rgba(232, 141, 163, 1)';
    --colors-turq: 'rgba(0, 245, 196, 1)';
    --colors-orange: 'rgba(255, 135, 31, 1)';

    --space-1: '4px';
    --space-2: '8px';
    --space-3: '16px';

    --radii-1: '2px';
    --radii-2: '4px';
  }

  pre {
    --background: 'hsla(206 12% 89.5% / 5%)';
    --text: var('--colors-white');
    --syntax1: var('--colors-orange');
    --syntax2: var('--colors-turq');
    --syntax3: var('--colors-pink');
    --syntax4: var('--colors-pink');
    --comment: var('--colors-gray');
    --removed: var('--colors-red');
    --added: var('--colors-turq');

    box-sizing: 'border-box';
    padding: var('--space-3');
    overflow: 'auto';
    font-family: var('--font-mono');
    font-size: var('--text-2');
    line-height: var('--space-3');
    whitespace: 'pre';
    background-color: var('--background');
    color: var('--text');

    '& > code': {
      display: 'block';
    }

    '.token.parameter': {
      color: var('--text');
    }

    '.token.tag, .token.class-name, .token.selector, .token.selector .class, .token.function': {
      color: var('--syntax1');
    }

    '.token.attr-value, .token.class, .token.string, .token.number, .token.unit, .token.color': {
      color: var('--syntax2');
    }

    '.token.attr-name, .token.keyword, .token.rule, .token.operator, .token.pseudo-class, .token.important': {
      color: var('--syntax3');
    }

    '.token.punctuation, .token.module, .token.property': {
      color: var('--syntax4');
    }

    '.token.comment': {
      color: var('--comment');
    }

    '.token.atapply .token:not(.rule):not(.important)': {
      color: 'inherit';
    }

    '.language-shell .token:not(.comment)': {
      color: 'inherit';
    }

    '.language-css .token.function': {
      color: 'inherit';
    }

    '.token.deleted:not(.prefix), .token.inserted:not(.prefix)': {
      display: 'block';
      px: '$4';
      mx: '-$4';
    }

    '.token.deleted:not(.prefix)': {
      color: var('--removed');
    }

    '.token.inserted:not(.prefix)': {
      color: var('--added');
    }

    '.token.deleted.prefix, .token.inserted.prefix': {
      userselect: 'none';
    }
  }
}
```

My PostCSS Config contains [postcss-preset-env](https://github.com/csstools/postcss-preset-env/) already which should support for CSS nesting. I also installed [postcss-nested](https://github.com/postcss/postcss-nested) & [postcss-css-variables](https://www.npmjs.com/package/postcss-css-variables), just in case.

# postcss.config.js

```js
module.exports = {
  plugins: [
    'postcss-import',
    'tailwindcss',
    'postcss-flexbugs-fixes',
    'postcss-nested',
    'postcss-css-variables',
    [
      'postcss-preset-env',
      {
        autoprefixer: {
          flexbox: 'no-2009',
        },
        stage: 3,
        features: {
          'custom-properties': false,
          'nesting-rules': true,
        },
      },
    ],
  ],
}
```

Reproduction here → https://github.com/deadcoder0904/postcss-tailwind-next-bug

Run the app & check the DOM to see the CSS variables in the Styles panel which shows `Invalid property value`.

How can I get CSS variables to work with Tailwind CSS?

**Comment by bobarros** [comment]
Hi, @deadcoder0904 

I had no problem running your code. I also tested with Chrome, Firefox, and Edge.

This is the element result that I get from your code:

```jsx
pre {
    box-sizing: border-box;
    padding: 16px;
    overflow: auto;
    font-family: 'Fira Mono, monospace';
    font-size: 14px;
    line-height: 16px;
    white-space: pre;
    background-color: hsla(206 12% 89.5% / 5%);
    color: rgba(255, 255, 255, 1);
}
```

Maybe deleting node_modules and installing again will solve it.
I'm using yarn 1.22.10 and node v14.15.4.

**Reply by deadcoder0904** [reply]
@bobaaaaa I just pushed a little fix by removing quotes around it. However, I get another error now:

> error - ./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[2].oneOf[6].use[2]!./src/styles/index.css
Error: Expected a pseudo-class or pseudo-element.

This only happens when I add the following to CSS:

```css
& > code: {
	display: block;
}

.token.parameter: {
	color: var(--text);
}
```

I tried both adding & removing quotes but it still gives me the same error.

I commented each rule at a time & it still gives those error which makes me think nesting isn't working.

**Reply by bobarros** [reply]
I thought it was the quotes, but decided to test hahaha
I will check the new problem and let you know in a minute

**Reply by deadcoder0904** [reply]
Sorry I pinged the wrong person @bobaaaaa

@bobarros just try uncommenting code from `tailwind.css` to see the error → https://github.com/deadcoder0904/postcss-tailwind-next-bug/blob/main/pages/styles/tailwind.css#L51-L110

**Reply by bobarros** [reply]
You should eliminate ':' from 'code:'

**Reply by deadcoder0904** [reply]
Oh damn. I just again used objects notation from CSS-in-JS. Thank you for the smart quick fix :)

**Comment by deadcoder0904** [comment, marked as answer]
The complete solution was to remove quotes & object notation in CSS. I copied the whole thing from CSS-in-JS but forgot to remove quotes & object notation aka `:`

# tailwind.css

```css
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';

@layer base {
  :root {
    --font-mono: 'Fira Mono, monospace';

    --text-1: 12px;
    --text-2: 14px;

    --colors-black: rgba(19, 19, 21, 1);
    --colors-white: rgba(255, 255, 255, 1);
    --colors-gray: rgba(128, 128, 128, 1);
    --colors-blue: rgba(3, 136, 252, 1);
    --colors-red: rgba(249, 16, 74, 1);
    --colors-yellow: rgba(255, 221, 0, 1);
    --colors-pink: rgba(232, 141, 163, 1);
    --colors-turq: rgba(0, 245, 196, 1);
    --colors-orange: rgba(255, 135, 31, 1);

    --space-1: 4px;
    --space-2: 8px;
    --space-3: 16px;

    --radii-1: 2px;
    --radii-2: 4px;
  }

  pre {
    --background: hsla(206 12% 89.5% / 5%);
    --text: var(--colors-white);
    --syntax1: var(--colors-orange);
    --syntax2: var(--colors-turq);
    --syntax3: var(--colors-pink);
    --syntax4: var(--colors-pink);
    --comment: var(--colors-gray);
    --removed: var(--colors-red);
    --added: var(--colors-turq);

    box-sizing: border-box;
    padding: var(--space-3);
    overflow: auto;
    font-family: var(--font-mono);
    font-size: var(--text-2);
    line-height: var(--space-3);
    white-space: pre;
    background-color: var(--background);
    color: var(--text);

    & > code {
      display: block;
    }

    .token.parameter {
      color: var(--text);
    }

    .token.tag,
    .token.class-name,
    .token.selector,
    .token.selector .class,
    .token.function {
      color: var(--syntax1);
    }

    .token.attr-value,
    .token.class,
    .token.string,
    .token.number,
    .token.unit,
    .token.color {
      color: var(--syntax2);
    }

    .token.attr-name,
    .token.keyword,
    .token.rule,
    .token.operator,
    .token.pseudo-class,
    .token.important {
      color: var(--syntax3);
    }

    .token.punctuation,
    .token.module,
    .token.property {
      color: var(--syntax4);
    }

    .token.comment {
      color: var(--comment);
    }

    .token.atapply .token:not(.rule):not(.important) {
      color: inherit;
    }

    .language-shell .token:not(.comment) {
      color: inherit;
    }

    .language-css .token.function {
      color: inherit;
    }

    .token.deleted:not(.prefix),
    .token.inserted:not(.prefix) {
      display: block;
      px: $4;
      mx: -$4;
    }

    .token.deleted:not(.prefix) {
      color: var(--removed);
    }

    .token.inserted:not(.prefix) {
      color: var(--added);
    }

    .token.deleted.prefix,
    .token.inserted.prefix {
      userselect: none;
    }
  }
}
```
