### DISCUSSION TITLE
next.js css loader not working appropriate

### DISCUSSION THREAD

**Discussion by astroplex** [vercel/next.js#25306] [Help]
next.js included css loader compile css like this.

how can I fix this.

```css
// before
:root {
   --rgb-color: 0, 244, 244;
}
```
```css
// after
:root {
   --rgb-color: 0, #244, #244;
}
```
