### DISCUSSION TITLE
Prepended SCSS mixins with CSS variables not working

### DISCUSSION THREAD

**Discussion by ferdiamg** [vercel/next.js#25782] [Help]
Dear NextJS community,

I've got the following next.config.js setup
```js
module.exports = (phase, {defaultConfig}) => {
  if ('sassOptions' in defaultConfig) {
      defaultConfig['sassOptions'] = {
          includePaths: ['./styles'],
          prependData: `@import "styles/mixins.scss";`,
      }
  }
  return defaultConfig;
}
```
and while for e.g. this mixin works flawlessly within my xyz.module.scss
```scss
@mixin panelBoxShadow() {
  box-shadow: 0 2px 7px 0 rgba(0,0,0,0.11);
}

// used in module.scss like
@include buttonBoxShadow();
```
this mixin doesn't work at all
```scss
@mixin maxWidth($value) {
  @media (max-width: $value) {
    @content
  }
}

// used in module.scss like
@include maxWidth(var(--tablet)) {
    padding-right: 0;
    padding-bottom: 1rem;
}
```

Anyone got an idea on how to get this working? I don't want to go back to importing the mixins.scss in every file that uses them..
