### DISCUSSION TITLE
How to use globally defined keyframes in CSS modules?

### DISCUSSION THREAD

**Discussion by brc-dd** [vercel/next.js#25803] [Help]
I have some code in a `module.(s)css` file like this:

```scss
.foo {
  // ...
  animation-name: bounce;
  // or maybe its shorthand
  // ...
}

// @keyframe bounce is defined in some
// global stylesheet not in this module file
```

But using it like `className={styles.foo}` in JSX/TSX is hashing `bounce` also; and since no keyframe with the hashed name exist, the animation is not being applied at all.

As a workaround, I can use `:global` aside every selector using animation, but is it possible to do something like [`postcss-icss-keyframes`](https://github.com/css-modules/postcss-icss-keyframes#using-globally-defined-keyframes) does? It doesn't replace animation name if the css module does not contain `@keyframes` or `@value` definitions with the same name.

---

Repo to reproduce this: [@brc-dd/nextjs-cssloader-animation-issue](https://github.com/brc-dd/nextjs-cssloader-animation-issue)
