### DISCUSSION TITLE
help me, sass variable does not compile

### DISCUSSION THREAD

**Discussion by ppbl** [vercel/next.js#26251] [Help] [answered]
**I have the following scss file on my page**

```scss
// theme.scss
@use './variable' as *;
:root {
  --color-background: #f7f7f7;
  --color-card-background: #fff;
  --color-border: #e0e0e0;
  --color-theme: $color-theme;
  --color-theme-1: $color-theme-1;
  --color-rise: $color-rise;
  --color-rise-1: $color-rise-1;
  --color-fall: $color-fall;
  --color-fall-1: $color-fall-1;
}
```

```scss
// variable.scss
$color-theme: #df2d45;
$color-theme-1: fade($color-theme, 10%);
$color-rise: #df2d45;
$color-rise-1: fade($color-rise, 8%);
$color-fall: #0cab38; 
$color-fall-1: fade($color-fall, 8%);
```

**I introduced in the _page.tsx file**

```tsx
import '../styles/globals.css'
import './theme.scss'

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default MyApp
```

**The scss variable is expected to compile successfully, but the result is**

![9C503A3D-8E8B-42B8-B278-7198E3607795](https://user-images.githubusercontent.com/33046279/122362905-184c7600-cf8b-11eb-940b-2311fdc1e902.png)

😅   Thanks, does anyone know what's going on？
