### DISCUSSION TITLE
Running Next is development mode from within a docker container

### DISCUSSION THREAD

**Discussion by dextermb** [vercel/next.js#27111] [Help] [answered]
Hi all

I have a need to be able to install dependencies from within a Docker container, and then be able to run `next dev` from within the Docker container but exposed to the host.

I have a custom Docker image that installs node modules:
```Dockerfile
FROM node:lts

WORKDIR /var/www/html
COPY . .

RUN yarn install
EXPOSE 8080

# Keep container alive
CMD ["tail", "-F", "/dev/null"]
```

I'm also exposing the port through Docker compose:
```yml
# ...

js:
    build: ./frontend
    ports:
        - "8080:8080"
    volumes:
        - ./frontend:/var/www/html

# ...
```

Then when I go into the container via:
```bash
docker exec -it <container> bash
```

Once inside running:
```bash
next dev -p 8080
```

I'm able to access the website via `http://localhost:8080` but whenever changes are made the `EventSource` "fails" even though the request succeeds in the network tab.

![image](https://user-images.githubusercontent.com/6137789/125301822-43747c00-e323-11eb-828c-b6a79144765f.png)

> EventSource failed loading: GET "http://localhost:8080/_next/webpack-hmr?page=/".

---

Any ideas on what might be the solution to this?
