### DISCUSSION TITLE
import or switch css dynamically?

### DISCUSSION THREAD

**Discussion by sqveeze** [vercel/next.js#27854] [Help]
Hello,

We have a legacy website written in PHP and has dark mode support via different css files:

theme-light.css
theme-dark.css

We are moving this site to NextJS in three phase. In the first we will not creating much components, we just copy and paste the html code into the nextjs pages + few js for the functions to work.
In the first phase we would like to keep the current light / dark theme but we aren't ready to rewrite the whole css files into a theme like mantine or chakra ui. Is there's any way to swap the two css file until we rewrite the whole css into a design system?

Google doesn't give any useful result, only for CRA. Also tried to create two components which import the light or dark css, but next doesn't allow to import css anywhere in the code other than _app.tsx

**Comment by morganfeeney** [comment]
You could let it be down to user preference, ie using custom properties and `@media`, e.g.

```css
body {
 background: var(--body-bg-color);
}

--black: black;
--white: white;

--body-bg-color: var(--white);

@media (prefers-color-scheme: dark) {
 --body-bg-color: var(--black);
}
```

This kind of global CSS is ideally placed in `_app.tsx`
