### DISCUSSION TITLE
Fast refresh not working when using Docker

### DISCUSSION THREAD

**Discussion by stackerito** [vercel/next.js#28220] [Help]
I am using WSL2 + Ubuntu 20.04 as the host.
I saw these posts from Stack Overflow, but trying the fixes there didn't work either: https://stackoverflow.com/questions/54126848/why-nextjs-using-docker-container-did-not-reload-after-changed-code-for-dev-envi And https://stackoverflow.com/questions/65359786/hot-reload-stopped-working-after-adjusting-environment-for-work-requirements

This is my `docker-compose.yml`:
```
    node:
        build:
            context: ./nextjs
            dockerfile: Dockerfile
        container_name: nextjs
        command: ["dev"]
        volumes:
            - ./nextjs:/var/www/html
        ports:
            - "3000:3000"
            - "49153:49153"
    
        networks:
            - laravel
```
And this is my Dockerfile:
```
    FROM node:alpine
    
    #Creates directories
    RUN mkdir -p /usr/src/app
    
    #Sets an environment variable
    ENV PORT 3000
    
    #Sets the working directory for any RUN, CMD, ENTRYPOINT, COPY, and ADD commands
    WORKDIR /usr/src/app
    
    #Copy new files or directories into the filesystem of the container
    COPY package.json /usr/src/app
    COPY package-lock.json /usr/src/app
    
    #Execute commands in a new layer on top of the current image and commit the results
    RUN npm install
    
    ##Copy new files or directories into the filesystem of the container
    COPY . /usr/src/app
    
    #Informs container runtime that the container listens on the specified network ports at runtime
    EXPOSE 3000
    EXPOSE 49153
    
    
    #Allows you to configure a container that will run as an executable
    ENTRYPOINT ["npm", "run"]
```
As you can see even exposing the port didn't help. Is the issue related to the second post I linked here with the WSL2 issues? Or bad `docker-compose.yml` and `Dockerfile` configuration?
