### DISCUSSION TITLE
Sharing variables between SASS and Javascript through :export directive no longer works because of global CSS restriction

### DISCUSSION THREAD

**Discussion by Lillebo** [vercel/next.js#28690] [Ideas]
### Describe the feature you'd like to request

It should be (and was) possible to import variables from SASS to Javascript through `sass-loader` and [the :export directive](https://www.bluematador.com/blog/how-to-share-variables-between-js-and-sass):

```scss
// tokens.scss
$red: #ff0000;
$green: #00ff00;

:export {
    red: $red;
    green: $green;
}
```

```typescript
// my-component.ts
import tokens from 'tokens.scss';

console.log(tokens.red); //outputs: "#ff0000"
```

But this is no longer possible in NextJS 11 because of the restriction of global CSS imports outside of `_app`.

### Describe the solution you'd like

Preferably I'd like a solution where importing CSS from any page or component is allowed again, but I'm open to suggestions.

### Describe alternatives you've considered

-
