### DISCUSSION TITLE
Azure Static Web App

### DISCUSSION THREAD

**Discussion by abcdeepakr** [vercel/next.js#29482] [Help]
I was deploying a Static Web App using Azure, my Code sits in Azure DevOps, The build command runs perfectly, however once the build is complete I get this error

`Failed to find a default file in the app artifacts folder (.next). Valid default files: index.html,Index.html.`

This is how my YAML file looks like

```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: "/" 
      api_location: "api"
      output_location: "/.next"
    env:
      azure_static_web_apps_api_token: $(deployment_token)
```

I've tried to set the output_location to "out", "/", "dist" none of them worked.

Any luck with this issue, thanks in advance :)
