### DISCUSSION TITLE
SCSS background image url seems to not work exactly like it did in v11 when using v12?

### DISCUSSION THREAD

**Discussion by chris-erickson** [vercel/next.js#30492] [Help]
We're doing something like this to style a header, and the image isn't showing up, and the CSS is slightly different

```scss
.header {
    background-image: radial-gradient(
            to top left,
            rgba(150, 55, 226, 1) 0%,
            rgba(150, 55, 226, 0) 100%
        ),
        radial-gradient(
            to bottom right,
            rgba(0, 146, 255, 1) 0%,
            rgba(0, 146, 255, 0) 100%
        ),
        linear-gradient(rgba(16, 19, 68, 0), rgba(16, 19, 68, 0.5)),
        url('../images/hero.jpg');  # <<<<<<===== This!
}
```
Next 11 Output:
![image (1)](https://user-images.githubusercontent.com/3322287/139152540-b0ff5197-8485-4740-8445-68e2d8b4fd6b.png)

Next 12 Output (image is blank, all other CSS appears to be working ok):
![image](https://user-images.githubusercontent.com/3322287/139152546-6656973b-da3b-4792-aa21-ac695024f753.png)

It seems that middle one is missing (got me why the other two are invalid to Chrome.. but hasn't been an issue for us..??

Same result with the new `swcMinify` option on or off, or with a .babelrc file in place (or not).
