### DISCUSSION TITLE
How to reference global css class name from css module?

### DISCUSSION THREAD

**Discussion by YuriGor** [vercel/next.js#31122] [Help] [answered]
Hi all, I am using UI framework and I want to override default css class of component from this framework.
e.g. I want to write scss module for my customized button and override internal button element
which has global class name `lib-button-label`:
```scss
.myButton { // I will assign this class name to component
  .lib-button-label { // this is class name of internal component element
    background: red;
  }
}
```
But next.js generates css with both `myButton` and `lib-button-label` class names appended by some suffixes to make them scoped.
Is there any syntax to prevent nextjs do this for particular class name?
something like this
```scss
// declare lib-button-label class as global so it will be left as is
@global .lib-button-label;
.myButton {
  .lib-button-label { 
    background: red;
  }
}
```

**Comment by YuriGor** [comment, marked as answer]
Ok, found this:
https://github.com/css-modules/css-modules#exceptions
So in example above it looks like: 
```scss
.myButton {
  global: .lib-button-label { 
    background: red;
  }
}
```
And it works, thanks for help :smile:
