### DISCUSSION TITLE
Pass environment variables at run time in docker compose

### DISCUSSION THREAD

**Discussion by dMaisnam** [vercel/next.js#31207] [Help] [answered]
I am working on dockerizing a nextjs frontend app where my backend api url is fetched over http.
```
version: "3.7"
services:
  app:
    container_name: frontend
    build:
      context: .
      args:
        - API_URL=http://path-to-backend-api-url/api
        - NEXT_PUBLIC_CLIENT_API_URL=http://path-to-backend-api-url/api
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
  nginx:
    depends_on: 
      - app
    container_name: frontend-nginx
    build: ./nginx
    ports:
      - "8080:8080"
```
Then I access these environment vars in my `Dockerfile` and was able to successfully build the container. But I assume they are not accessible in the container run time as I observe the `NEXT_PUBLIC_CLIENT_API_URL` returns `undefined` when trying to fetch data.
How can I access them during the container run time? Any help is much appreciated. Thanks.

EDIT: changed question title and updated code and body

**Comment by dMaisnam** [comment]
I don't know if this was responsible but including my environment variables both in build `args` and `environment` of `docker-compose.yml` file like 
```    
build:
    context: .
    args:
      - API_URL=http://path-to-backend-api-url/api
      - NEXT_PUBLIC_CLIENT_API_URL=http://path-to-backend-api-url/api
    environment:
      - NODE_ENV=production
      - API_URL=http://path-to-backend-api-url/api
      - NEXT_PUBLIC_CLIENT_API_URL=http://path-to-backend-api-url/api
...
```
and accessing these args in my `Dockerfile` made my app run for now.
I am open to more elegant solutions/suggestions for passing environment variables
