### DISCUSSION TITLE
.next/cache in production

### DISCUSSION THREAD

**Discussion by capJavert** [vercel/next.js#31395] [Help] [answered]
Is `.next/cache` folder needed in production for production server and build to work? 

It has a substantial size so not uploading into into Docker image would be great save of space.

**Comment by thibautsabot** [comment, marked as answer]
Hello.

You do not need `.next/cache` to run your application !
This folder is used for build caching purposes to speed up the build process but is not a requirement to run in production.

**Reply by xs-nayeem** [reply]
Is there any way to delete cache folder using any command? or is there any config I am missing?

**Reply by lyczos** [reply]
As a workaround in the workflow process, I'm excluding `.next/cache` from artifacts upload to decrease the docker image size.
```yaml
      - uses: actions/upload-artifact@v4
        with:
          name: next-${{ github.sha }}
          path: |
            !.next/cache
            .next
 ```
