### DISCUSSION TITLE
Next.js + PM2 Set up

### DISCUSSION THREAD

**Discussion by ShawnCentra** [vercel/next.js#31461] [Help]
Hey guys. I tried running Next.js + Forever but the start up time for the web pages was extremely slow and I wasn't sure why. Decided to install pm2 and give that a shot. 

Is there a good set up/resource for running a next.js production build with PM2?

**Comment by nicosh** [comment]
Build the app : `npm run build`  
Launch pm2 deamon:  `pm2 start npm --name "myApp" -- start`
Then use `pm2 reload` when you need to (for example for updating your app after a git pull)
```
pm2 stop yourAppProcessId
git pull 
npm run build
pm2 reload yourAppProcessId
```

if you want to setup CI/CD with github here an example of action : 

```
name: CI/CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: [self-hosted, myServer]
    steps:
      - uses: actions/checkout@v2
        with:
          clean: true
      - name: Install dependencies for production
        run: npm install
      - name: Build the app
        if: success()
        run: npm run build
      - name: Restart the process
        if: success()
        run: pm2 reload yourProcessId
```
