### DISCUSSION TITLE
Unable to retrieve AWS Container Variables as process.env

### DISCUSSION THREAD

**Discussion by kanhaiya007** [vercel/next.js#31727] [Help]
My NextJS app hosted on aws (Using EC2 and ECS), I have added couple of variables with NEXT_PUBLIC... as well as simple. I am unable to fetch those as `process.env.NAME`. Can someone please quickly help me with that?

**Comment by detrumi** [comment]
We have the same problem with Application Settings on Azure, they should be passed as environment variables but are not picked up by NextJS.

**Comment by hari7priya** [comment]
This is required. Please help. NEXT_PUBLIC_VAR_NAME is available in printenv list of values in the container instance. However, NextJS App always shows console.log(process.env.NEXT_PUBLIC_VAR_NAME) as undefined.

**Comment by ajaymahadeven** [comment]
# Troubleshooting Issues with Placing  License Key in Next-JS

## Problem Description
When trying to integrate the ag-Grid license key into our software, we encountered an issue where the environment variables were not accessed correctly. This issue became evident when attempting to console.log the environment variables, and they appeared as undefined.

## Solution Overview
We resolved the problem by following these steps:

### 1. Use NEXT_PUBLIC Prefix
We utilized the NEXT_PUBLIC prefix when defining environment variables. This prefix is crucial for ensuring proper access to the variables on the client side.

### 2. Assign Environment Variables to Variables
To ensure that the environment variables were correctly passed through, we assigned them to variables in our code. For example:

```javascript
const key = process.env.NEXT_PUBLIC_VAR_NAME;
```

This step helps in accessing the variables in a more reliable manner.

### 3. Utilize Client-Side Rendering
In our case, since we were working with client-side rendering, we made use of "use client" to ensure that the environment variables were accessible in the client-side code.

### 4. Verify Folder Location
It's essential to ensure that the .env files are placed in the correct folder location. In our setup, these files were placed in the following directories: .envs/.local/.nextjs.

### 5. Follow Proper .env Format
We followed the proper .env format as specified in the Next.js documentation. This format is crucial for correctly defining and accessing environment variables.

You can find more information on configuring environment variables in Next.js in the [official documentation](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables).

## Verification Steps
To verify that the environment variables are correctly set up, you can perform the following checks:

### Check All Environment Variables
1. Open a terminal or command prompt.
2. Run the following command:

   ```shell
   node
   ```

3. Once in the Node.js REPL, type the following command to view all environment variables:

   ```javascript
   console.log(process.env);
   ```

This will display all the environment variables available.

### Check a Specific Environment Variable
To check the value of a specific environment variable, use the following command:

```shell
node --print 'process.env.your_key_name'
```

Replace `your_key_name` with the name of the specific environment variable you want to inspect.

By following these steps and best practices, you can ensure that environment variables, including your  license key, are properly integrated into your software.

**Reply by damon314159** [reply]
pretty sure you had ChatGPT write this

**Reply by ajaymahadeven** [reply]
and  I'm pretty sure ChatGPT refers to itself as 'we.' I'm glad you cracked the case!" @damon314159

**Comment by hari7priya** [comment]
Solution Found. @thenameisajay Thank you for replying. Everything that you mentioned was in place already but still had the issue.

Following helped me resolve the issue:

Scenario:
1. Image is running within the ECR container task. Had environmental variables set in the task definition. Printenv command inside the container shows NEXT_PUBLIC_JWT_TOKEN=valuetobedisplayed.
2. UI is trying to access NEXT_PUBLIC_JWT_TOKEN by using process.env.NEXT_PUBLIC_JWT_TOKEN
3. Build was successful and Deploy was also successful. Website was loading fine. However, console.log of above value on the UI is always undefined.

Findings:
1. Image runs but unable to access container's variables. How to expose container's env vars to image running inside the container during runtime?
2. Seemed like image needs to be rebuilt with container's env var

Solution:
1. Declare  NEXT_PUBLIC_JWT_TOKEN=uniquevalue in .env.production (or any env file that image is using)
2. using dockerfile and entrypoint.sh script, replace 'uniquevalue' string with env variable value thats within the container (valuetobedisplayed). And then, run npm run build && npm run start. 
3. Now, on the UI, console.log(process.env.NEXT_PUBLIC_JWT_TOKEN) displays valuetobedisplayed instead of undefined or uniquevalue (as declared in .env.production)

Following is my DockerFile

```
FROM public.ecr.aws/docker/library/node:latest     

WORKDIR /

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod u+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"] 

EXPOSE 80

CMD npm run build && npm run ci
```


Here is the entrypoint.sh file in the root directory where .env.production file and dockerfile are present:

```
!/bin/bash
set -e
 
sed -i "s/uniquevalue/${NEXT_PUBLIC_JWT_TOKEN}/g" .env.production
 
exec "$@"
```


**Here is the .env.production file:**
```
NEXT_PUBLIC_JWT_TOKEN=uniquevalue
```

**Comment by joelbentham** [comment]
Hi, any other workaround for this?
I would like to avoid creating a env.production to set my secrets there?
I set the env keys for region and credentials from aws in the task definition for the ECS, but those are not being readed ok.

thanks

**Comment by edelinp** [comment]
Here's how Ive solved the problem to ensure the .env variables are present, and the application is running correctly in AWS ECS Service.

In Dockerfile Im passing ARG during the build process, because Next.js requires environment variables (like NEXT_PUBLIC_) to be available when it builds the app, and the ENV ensures that these variables persist and are available at runtime when the application runs in the container. This is regardless of passing the variables in the Task definition, which only makes the variables available at runtime.

Inside the Dockerfile
```
# Add build-time arguments for environment variables
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

# Set build-time environment variables for Next.js to use during the build
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}


RUN corepack enable pnpm && pnpm run build
```

Im using AWS Secret Manager to store the API keys, and fetch them during the codebuild process.

Inside the buildspec.yml;
```
pre_build:
    on-failure: ABORT
    commands:
      - export NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$(aws secretsmanager get-secret-value --secret-id $SERVICE/MAPS_API_KEY --query SecretString --output text)
      - export NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$(aws secretsmanager get-secret-value --secret-id $SERVICE/STRIPE_PUBLISHABLE_KEY --query SecretString --output text)
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $REPOSITORY
      - echo Pre-build phase completed successfully.

  build:
    on-failure: ABORT
    commands:
      - echo Building the Docker image...
      - docker build --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY --build-arg NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY -t $IMAGE .
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG
      - echo Tagging the Docker image...
    finally:
      - echo Build phase completed successfully.
```

I hope this helps someone, or I would love to hear if there's a better way to go around this.
