### DISCUSSION TITLE
Failed to load SWC binary when using Nexus proxy on Gitlab CI

### DISCUSSION THREAD

**Discussion by othierry-asi** [vercel/next.js#32000] [Help]
Hi,

I try to make a Gitlab CI pipeline to build a Next.js application. We setup a NPM proxy in Nexus and I configured a `.npmrc` file to use it. But this job : 

```
build:
  stage: build
  image: node:16-alpine
  script:
    - npm ci
    - npm run build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - .next
      - build
    expire_in: 1 day
```

fails ont `npm run build` with this error :

```
error - Failed to load SWC binary, see more info here: https://nextjs.org/docs/messages/failed-loading-swc
```

No problem if I disable Nexus proxy in `.npmrc`.

It works well too on my MacOS with Nexus proxy enabled.
So only a problem with Nexus proxy on Gitlab CI.

Anyone tried to do this and could achieve it ?
