### DISCUSSION TITLE
Use envinfo for issue template

### DISCUSSION THREAD

**Discussion by mohsen1** [vercel/next.js#32858] [Ideas]
It will make it easier if the issue template was something like this:

```
### Environment 
    
    <summary>
    Results of <code>npx envinfo --preset next</code>
    </summary>
    <details>
    
    ```
    
    ```
    
    </details>
```

Or it cloud use the GitHub issue form template:

```
 - type: input
    attributes:
      label: What environment are you running on?
      description: Run `npx envinfo --preset next` to get the details 
    validations:
      required: true
```

I've created a PR for envinfo here to add a preset for Next.js if this is something that team agrees to. We can add more information to be gathered in that preset.

https://github.com/tabrindle/envinfo/pull/215
