### DISCUSSION TITLE
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./src/styles/index.css Error: Unexpected '/'. Escaping special characters with \ may help.

### DISCUSSION THREAD

**Discussion by deadcoder0904** [vercel/next.js#34157] [Help] [answered]
i was using tailwind v2 on an old project & now i switched to using tailwind v3 & it's throwing errors. it was working fine before i updated my deps.

the error is:

> error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./src/styles/index.css
Error: Unexpected '/'. Escaping special characters with \ may help.

it looks like the error is pointing out to comments in my css files.

### styles/index.css

```css
@import 'tailwindcss/base';

@import './nprogress.css';
@import './base.css';
@import './scrollbar.css';
@import './fast-image-zoom.css';
@import './grid.css';
@import './anchor.css';
@import './prism.css';
@import './gif.css';
@import './giscus.css';

@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```

 the root file has no comments but i have comments in other files.

### styles/giscus.css

```css
// style loading comments indicator in giscus
.gsc-comments-count {
	@apply text-gray-900 dark:text-white mt-10;
}
```

### styles/nprogress.css

```css
#nprogress {
	@apply pointer-events-none;

	& .bar {
		@apply bg-white h-[2px];

		/* Fancy blur effect */
		& > .peg {
			box-shadow: 0 0 20px rebeccapurple, 0 0 15px rebeccapurple;
			@apply block absolute right-0 w-[140px] h-full opacity-100 rotate-3 translate-x-0 -translate-y-1;
		}
	}

	& > .spinner > .spinner-icon {
		@apply border-l-gray-300 border-t-gray-800;
	}
}
```

it also looks like `postcss-loader` & `css-loader` issue & i'm not sure how to solve it?

here are some additional files:

### postcss.config.js

```js
module.exports = {
	plugins: [
		'postcss-import',
		'postcss-flexbugs-fixes',
		'postcss-nested',
		'postcss-custom-properties',
		'tailwindcss',
		'autoprefixer',
	],
}
```

### next.config.js

```js
const bundleAnalyzer = require('@next/bundle-analyzer')

const withBundleAnalyzer = bundleAnalyzer({
	enabled: process.env.ANALYZE === 'true',
})

const nextConfig = {
	experimental: {
		esmExternals: true,
	},
	webpack: (config, options) => {
		config.module.rules.push({
			test: /\.svg$/,
			use: ['@svgr/webpack', 'url-loader'],
		})
		
		if (!options.isServer) {
			config.resolve.fallback.fs = false
		}

		return config
	},
}

module.exports = withBundleAnalyzer(nextConfig)
```

how do i solve it? i just can't get it to run :(
