### DISCUSSION TITLE
NX Monorepo Next.js project deployment via Gitlab CI to Vercel

### DISCUSSION THREAD

**Discussion by forza11879** [vercel/next.js#34211] [Help]
I am trying do deploy a NX Monorepo Next.js project via Gitlab CI to Vercel. Here is `.yml` file .
```
image: node:lts
stages:
  - build
  - web-test
  - deploy
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
build website:
  stage: build
  script:
    - npm install
    - npm i @nrwl/cli -g
    - nx run shop-wine:build
  artifacts:
    paths:
      - ./dist
test website:
  stage: web-test
  script:
    - npm install
    - npm i @nrwl/cli -g
    - nx run shop-wine:serve &
    - sleep 60
    - curl "http://localhost:4200" | grep -q "Welcome shop-wine"
deploy-to-vercel:
  stage: deploy

  variables:
    PREVIEW_URL: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$VERCEL_USER.vercel.app
    VERCEL_ORG_ID: $VERCEL_ORG_ID
    VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID

  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'

  environment:
    name: vercel/$CI_COMMIT_REF_NAME
    url: https://$PREVIEW_URL

  script:
    - npm i -g vercel
    - DEPLOYMENT_URL=$(VERCEL_ORG_ID=$VERCEL_ORG_ID VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID vercel --confirm -t $VERCEL_TOKEN --scope $VERCEL_USER)
    - vercel alias set $DEPLOYMENT_URL $PREVIEW_URL -t $VERCEL_TOKEN --scope $VERCEL_USER
```
There are no problems with `build `and `web-test` stages but when I get to manual `deploy-to-vercel` stage I am getting the following error from GitLab:

![image](https://user-images.githubusercontent.com/23064521/153524853-e654f497-86fc-4a20-8987-06a23839d208.png)

Here are the overrides on Vercel:

![image](https://user-images.githubusercontent.com/23064521/153524924-f99a7cf9-ea9e-46b5-a50c-db554d127a95.png)

I am also using a plugin to automaticaly deploy to Vercel. As you can see it is deployed with success ahead of `build`, `web-test` and manual `deploy-to-vercel` stages.

![image](https://user-images.githubusercontent.com/23064521/153525000-87f976fa-1e1f-4d82-961a-131fd97f47cf.png)

But when it gets to manual `deploy-to-vercel` here is Vercel error. Let me know if I am doing something wrong.

![image](https://user-images.githubusercontent.com/23064521/153525060-4bf63d5b-417b-4363-87fa-64e025ed27d4.png)
![image](https://user-images.githubusercontent.com/23064521/153525077-84992368-98f2-4a30-8e9c-d876f8fb392b.png)
