### DISCUSSION TITLE
Attempting to make the image fill the page

### DISCUSSION THREAD

**Discussion by Alee14** [vercel/next.js#34250] [Help]
Hello, at the moment I want to fill the page with the image provided with CSS

/pages/index.js
```html
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Andrew Lee</title>
        <meta name="description" content="Andrew's personal website" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.landing}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </main>
      </div>
    </div>
  )
}
```
/styles/Home.module.css
```css
.container {
  padding: 0 2rem;
}
.landing {
  height: 100%;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  background-image: url("/temp-landing.png")
}
```

![image](https://user-images.githubusercontent.com/11698947/153686271-81177a46-e428-46d8-ae07-d1d4338d0a10.png)
