### DISCUSSION TITLE
yarn build cache warning during CI

### DISCUSSION THREAD

**Discussion by Sed9yDataBank** [vercel/next.js#34805] [Help]
using GitHub workflow to deploy an SSG nextjs website. this is the caching part in my .`yaml` file:
```yaml
- name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
```

during `yarn build` i get this warning:

```
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
```

I checked this https://github.com/vercel/next.js/blob/main/errors/no-cache.md#github-actions that uses this:
```yaml
uses: actions/cache@v2
with:
  path: ${{ github.workspace }}/.next/cache
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
```

and this https://github.com/belgattitude/nextjs-monorepo-example/pull/290/commits that uses this:

```yaml
- name: Restore nextjs build web-app from cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/apps/web-app/.next/cache
          key: ${{ runner.os }}-nextjs-web-app-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('apps/web-app/src/**.[jt]sx?') }}
          restore-keys: |
               ${{ runner.os }}-nextjs-web-app-${{ hashFiles('**/yarn.lock') }}-
```

my question: what is the right way to fix the `yarn build` warning about the `no cache build found`
