### DISCUSSION TITLE
SSG DB access with Docker build

### DISCUSSION THREAD

**Discussion by orbiteleven** [vercel/next.js#36475] [Help] [answered]
I'm trying to "Dockerize" my Next.js app and running into a problem. Possibly/probably of my own doing, but still.

I have a Dockerized Postgres image to run my database. That is up and running, but when I try to build my app via Docker (via `docker build -f Dockerfile`), everything works up until the point it tries to build the SSG pages:
```
Error: Can't reach database server at `localhost`:`5432`
```

I've tried using `depends_on` in a `docker-compose.yml`, passing various things into `--add-host`, as well as replacing `localhost` with `host.docker.internal` in my `.env` file, but nothing seems to work. I know this is more of a Docker thing, and I'll probably cross-post this to SO, but since it feels like a pretty common sense way to Dockerize a Next.js app with SSG, perhaps someone here has pointers.

FWIW I'm using a lightly modified version of https://github.com/vercel/next.js/tree/canary/examples/with-docker

thanks

**Comment by orbiteleven** [comment, marked as answer]
Classic rubber duck posting, but in case someone else is searching:

The issue I had was that I was adding `network: host` to the service, but not build. So while this didn't work:
```yaml
services:
  web:
    # network listed on service:web
    network: host
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 5432:5432
      - 6379:6379
```

This did:

```yaml
services:
  web:
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      # network listed on service:web:build
      network: host
      dockerfile: ./packages/web/Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 5432:5432
      - 6379:6379
```
