### DISCUSSION TITLE
Next.js 12 getting stuck on 'next build' on Travis but working on local machine. How can I debug?

### DISCUSSION THREAD

**Discussion by sor-geison** [vercel/next.js#36658] [Help]
When I change my package.json to version 12 of Next.jst it simply gets stuck on Travis at the 'next build' command (npm run build in my case). I've tried using the command install with travis_wait to see if it would run:

  - "other commands"
  - travis_wait 60 npm run build

and it still got stuck for 60 minutes.

On my local machine everything works. I've tried changing it to run with the --debug flag but it doesn't show anything different.
How can I debug it?

Here's my package.json:

```{
  "name": "maggie",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build --debug",
    "start": "next start",
    "lint": "next lint",
    "test": "jest --watch",
    "test:travis": "jest",
    "test:coverage": "jest --collectCoverage",
    "open-cy": "cypress open --config-file cypress.test.json",
    "test-local": "NODE_ENV=test start-server-and-test dev 3000 open-cy",
    "start:ci": "next dev",
    "cy:run": "cypress run",
    "cy:verify": "cypress verify"
  },
  "dependencies": {
    "axios": "^0.21.1",
    "knex": "^0.95.6",
    "mongodb": "^3.6.9",
    "next": "12.1.5",
    "next-auth": "^3.27.3",
    "pg": "^8.6.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-icons": "^4.3.1",
    "react-query": "^3.19.6",
    "react-spring": "^9.2.4",
    "react-use": "^17.2.4",
    "sass": "^1.35.1",
    "swr": "^1.0.1",
    "tslib": "^2.3.0"
  },
  "devDependencies": {
    "@shelf/jest-mongodb": "^2.2.0",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^12.0.0",
    "@types/gtag.js": "0.0.8",
    "@types/mongodb": "^3.6.20",
    "@types/react": "^17.0.11",
    "@typescript-eslint/eslint-plugin": "^4.27.0",
    "@typescript-eslint/parser": "^4.27.0",
    "babel-jest": "^27.1.0",
    "cypress": "^7.5.0",
    "eslint": "^7.29.0",
    "eslint-config-airbnb-typescript": "^12.3.1",
    "eslint-config-next": "11.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.23.4",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.4.0",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^1.7.0",
    "eslint-plugin-testing-library": "^4.12.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^27.1.0",
    "prettier": "2.3.1",
    "react-test-renderer": "^17.0.2",
    "start-server-and-test": "^1.12.5",
    "typescript": "4.3.4"
  },
  "engines": {
    "node": "14.17.2",
    "npm": "6.14.13"
  }
}
```

Here's my yaml file: 

```
# Travis YML CI/CD config
language: node_js
node_js:
  - v14.17.1
dist: trusty

env:
  MONGO_URI=mongodb://127.0.0.1:27017/
  CYPRESS_MONGO_URI=mongodb://127.0.0.1:27017/
  MONGODB=3.6.13

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
  - npm install
  - npm run build

addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  # install dependencies and check that Cypress can run
  # override:
  #   - npm ci
  #   - npm run cy:verify

script:
  # start server in the background
  #- npm run start:ci &
  # run all Cypress tests and record on the dashboard
  #- npm run cy:run
  # run jest tests
  - npm run test:travis
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true
```
