### DISCUSSION TITLE
Increasing size of .next directory

### DISCUSSION THREAD

**Discussion by mislimiscode** [vercel/next.js#37426] [Help]
Hi,

I have a problem with constant memory growth of the **.next** folder.
We have an application running on docker.
We are using Incremental Static Regeneration and Server-Side Rendering.

Version of next
```
"next": "^11.1.0"
```

docker-compose.yml
```yml
version: '2.4'
services:
  # Frontend prod
  node-prod:
    build: 
      context: ../www
      dockerfile: ../.docker/node/Dockerfile
      args:
        - ENV_FILE=prod.env
    container_name: test-prod
    environment:
      - NODE_OPTIONS="--max-old-space-size=1536"
    expose:
      - "3000"
    restart: always
    cpus: 1
    mem_limit: 1536m
    networks:
      - test
networks:
  test:
    external: true
```

DockerFile
```DockerFile
ARG NODE_ENV=production

FROM node:16-slim AS base

ENV NODE_ENV $NODE_ENV

ARG PORT=3000
ENV PORT $PORT
EXPOSE $PORT

RUN npm i npm@latest -g

RUN mkdir -p /opt/node_app
WORKDIR /opt/node_app

RUN mkdir -p /opt/node_app/app/.next

RUN mkdir -p /opt/node_app/_logs

COPY ./package.json ./package-lock.json* ./.npmrc ./

RUN npm ci --legacy-peer-deps && npm cache clean --force
ENV PATH /opt/node_app/node_modules/.bin:$PATH

WORKDIR /opt/node_app/app
COPY . .

ARG ENV_FILE=production.env
COPY ./$ENV_FILE .env.local

# Development
FROM base AS next-app-development
CMD npm run dev

# Production
FROM base AS next-app-production
RUN npm run build
CMD npm start

FROM next-app-$NODE_ENV AS next-app-final
```

Bellow you can see the logs of memory increasing of the **.next** folder.
It is during midnight and the website is not being used as much as during the day.
```
Fr 3. Jun 00:00:01 CEST 2022
588M	/opt/node_app/app/.next
Fr 3. Jun 00:30:01 CEST 2022
610M	/opt/node_app/app/.next
Fr 3. Jun 01:00:01 CEST 2022
631M	/opt/node_app/app/.next
Fr 3. Jun 01:30:01 CEST 2022
655M	/opt/node_app/app/.next
```
