### DISCUSSION TITLE
Next Js Docs Code Snippets Color Theme

### DISCUSSION THREAD

**Discussion by kmanadkat** [vercel/next.js#37814] [Help] [answered]
I recently started learning Next Js, coming from react background. The docs are really helpful, thank you so much for writing it so well :)

I wanted to know what is code syntax highlighting theme is used on the [officials docs](https://nextjs.org/learn/foundations/from-react-to-nextjs)

If you have vscode extension link for color theme, it will be really great!

**Comment by icyJoseph** [comment, marked as answer]
Interesting question, I don't think it is public, other than through inspecting the CSS.

```css
    code[class*="language-"],pre[class*="language-"] {
                color: #f8f8f2;
                text-shadow: 0 1px rgba(0,0,0,.3);
                direction: ltr;
                text-align: left;
                white-space: pre;
                word-spacing: normal;
                word-break: normal;
                line-height: 1.5;
                -moz-tab-size: 4;
                -o-tab-size: 4;
                tab-size: 4;
                -webkit-hyphens: none;
                -moz-hyphens: none;
                -ms-hyphens: none;
                hyphens: none
            }

            .token.comment,.token.prolog,.token.doctype,.token.cdata {
                color: #999
            }

            .token.punctuation {
                color: #c5c8c6
            }

            .namespace {
                opacity: .7
            }

            .token.property,.token.keyword,.token.tag {
                color: #96cbfe
            }

            .token.class-name {
                color: #ffffb6
            }

            .token.boolean,.token.constant {
                color: #9c9
            }

            .token.symbol,.token.deleted {
                color: #f92672
            }

            .token.number {
                color: #ff73fd
            }

            .token.selector,.token.attr-name,.token.string,.token.char,.token.builtin,.token.inserted {
                color: #a8ff60
            }

            .token.variable {
                color: #c6c5fe
            }

            .token.operator {
                color: #ededed
            }

            .token.entity {
                color: #ffffb6;
                cursor: help
            }

            .token.url {
                color: #96cbfe
            }

            .language-css .token.string,.style .token.string {
                color: #87c38a
            }

            .token.atrule,.token.attr-value {
                color: #f9ee98
            }

            .token.function {
                color: #dad085
            }

            .token.regex {
                color: #e9c062
            }

            .token.important {
                color: #fd971f
            }

            .token.important,.token.bold {
                font-weight: bold
            }

            .token.italic {
                font-style: italic
            }
```

These class names are from Prism.js I believe, but I couldn't find a matching theme. This one for example, has the same main colour, but that's about it, https://github.com/PrismJS/prism/blob/e0ee93f138b7da294a28db50b97c22977fdfc8ed/themes/prism-okaidia.css
