### DISCUSSION TITLE
axios POST/GET request SpringCloud data header no cookie

### DISCUSSION THREAD

**Discussion by zhangwei900808** [vercel/next.js#39222] [Help]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

 Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
    Binaries:
      Node: 14.17.1
      npm: 8.10.0
      Yarn: 1.22.5
      pnpm: N/A
    Relevant packages:
      next: 12.2.2
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 版本 103.0.5060.134（正式版本） (x86_64)

### How are you deploying your application? (if relevant)

yarn dev

### Describe the Bug

When I used next.js api is Success! 
But when I used spinggateway request data is not working!

**Next.js API RESPONSE：**
```
Connection: keep-alive
Content-Length: 19
Content-Type: application/json; charset=utf-8
Date: Mon, 01 Aug 2022 07:52:57 GMT
ETag: "13-5j0ZZR0tI549fSRsYxl8c9vAU78"
Keep-Alive: timeout=5
Vary: Accept-Encoding
```

**Next.js API REQUEST(have Cookie)：**
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Connection: keep-alive
Content-Length: 50
Content-Type: application/json
Cookie: aaa=2222
Host: localhost:3000
Origin: http://localhost:3000
Referer: http://localhost:3000/login
sec-ch-ua: ".Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
```

**Spring RESPONSE：**
```
access-control-allow-credentials: true
access-control-allow-origin: http://localhost:3000
cache-control: no-cache, no-store, max-age=0, must-revalidate
content-type: application/json
date: Mon, 01 Aug 2022 07:19:31 GMT
expires: 0
pragma: no-cache
strict-transport-security: max-age=15724800; includeSubDomains
vary: Origin
vary: Access-Control-Request-Method
vary: Access-Control-Request-Headers
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
```

**Spring REQUEST(No Cookie)：**
```
:authority: testapi.seaurl.com
:method: POST
:path: /account/info/login
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9
content-length: 50
content-type: application/json
origin: http://localhost:3000
referer: http://localhost:3000/
sec-ch-ua: ".Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
```

axios.js
```
const axiosInstance = axios.create({
  baseURL: `${process.env.NEXT_PUBLIC_API_HOST}`,
  withCredentials: true
});
```

spring-gateway
```
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      globalcors:
        #add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            # 为true时allowedOrigins不允许为* 会报错
            allowCredentials: true
            allowedOrigins: 
              - "https://test.seaurl.com"
              - "http://127.0.0.1:3000"
              - "http://localhost:3000"
            allowedMethods: 
              - GET
              - POST
              - DELETE
              - PUT
              #- OPTIONS
            allowedHeaders: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
```

### Expected Behavior

Spring request data cookie can pass！

### Link to reproduction

...

### To Reproduce

1、login
2、axios POST/GET request（no cookie）
3、return data
