### DISCUSSION TITLE
with-docker-multi-env with fast refresh

### DISCUSSION THREAD

**Discussion by jb19901234** [vercel/next.js#41107] [Show and tell]
I have never posted to an opensource repository, so I am just dumping it here.

If you want to use fast reload in de dev enviroment of the with-docker-multi-env example, you should adjust the code:

Change the dockerfile in the docker/development folder into:

-------------------------------
```yaml
# 1. Install dependencies only when needed
FROM node:16-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

# Set /app as the working directory
WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
    else echo "Lockfile not found." && exit 1; \
    fi

# 2. Rebuild the source code only when needed
FROM node:16-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
# This will do the trick, use the corresponding env file for each environment.
COPY . /app
COPY .env.development.sample .env.production
RUN yarn build

# Copy the rest of our Next.js folder into /app

ENV NODE_ENV=development

EXPOSE 3000
ENV PORT 3000

# Run yarn dev, as we would via the command line 
CMD ["yarn", "dev"]
```
--------------------------------------------------------------------------

Change the docker-compose file in the docker/development folder into:

-----------------------------------------------------------------------
```Dockerfile
version: '3'

services:
  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    restart: always
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3001:3000'
  ```
------------------------------------------------------------

**Comment by rishigupta121** [comment]
@jb19901234 Not working just create container

**Reply by jb19901234** [reply]
Currently, I am using this for my development enviorment:

Dockerfile:
```Dockerfile

# 1. Install dependencies only when needed
FROM node:18 AS deps

# Set /app as the working directory
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN yarn --frozen-lockfile

# 2. Rebuild the source code only when needed
FROM node:18 AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules

# This will do the trick, use the corresponding env file for each environment.
COPY . /app

ENV NODE_ENV=development

EXPOSE 3000
ENV PORT 3000

# Run yarn dev, as we would via the command line 
CMD ["yarn", "dev"]
```
Docker compose File:
```yaml

version: '3'

services:
  blabla:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: blabla
    restart: always
    volumes:
      - ../../:/app:delegated
    ports:
      - '3001:3000'
    networks:
      - asdasd
    env_file:
      - ../../.env.dev
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - asdasd
    volumes:
      - mongo-data:/data/db
networks:
  asdasd:
    driver: bridge
volumes:
  mongo-data:
    driver: local
```
