### DISCUSSION TITLE
usage @next/font for google font icon

### DISCUSSION THREAD

**Discussion by aifrim** [vercel/next.js#42881] [Ideas]
### Describe the feature you'd like to request

`@next/font/google` to allow the loading of [Material Symbols](https://fonts.google.com/icons)

What are Material Symbols?

As Google states:

> Material Symbols are our newest icons consolidating over 2,500 glyphs in a single font file with a wide range of design variants. Symbols are available in three styles and four adjustable variable font styles (fill, weight, grade, and optical size).

### Describe the solution you'd like

```ts
import { MaterialSymbols } from "@next/font/google";

MaterialSymbols({ subsets: ["outlined", "rounded", "sharp"] });
```

### Describe alternatives you've considered

The only solution, for now, is to add this to the `head` of the document.

```html
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={"crossOrigin"} />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
```

**Comment by vBohu** [comment]
YES PLEASE

**Comment by Mandelag** [comment]
I am thinking the same thing, since currently the whole font file is 2 Mb..

It would be very nice if Next.js able to filter out unused glyph at build time, and then give them the same treatment as next js font optimization flow as this thread suggest

**Reply by aifrim** [reply]
That seems a bit too complex but it's a great idea.

**Comment by simonecervini** [comment]
While it may appear to be a convenient option, I am not certain that Next.js should recommend this approach.

The main issue is that the `font-display` descriptor does not have a valid value that works well with icon fonts (the best option, `font-display: block` is still not ideal). As a result, users with slow internet connections will often see the ligature text instead of the intended icon.

In my opinion, there is no benefit to using an advanced solution like `@next/font` for performance optimization if it results in a flash of text such as "check_circle" instead of the proper icon.

**Reply by N2D4** [reply]
Copying [my response from the MUI repo](https://github.com/mui/material-ui/issues/32846#issuecomment-1845173188):

> You can use the codepoints instead (optimally the library would do the transformation):
> 
> https://github.com/mui/material-ui/assets/19274317/c68d0333-c5e1-49dd-8ea5-ad1bc41ec3f9
> 
> There's some CLS in my video, but there are ways to fix that with a fallback font as well.
> 
> I'd like to have fonts over SVG because of the animations, but I'm worried about the 2MB file size if all variants are included (even the 300KB baseline is a lot). Creating an optimized font file at build-time based on whatever icons you imported would be the optimal solution, but that sounds more like a bundler plug-in than a MUI component.

Next would be in the optimal position to make a bundler plug-in like that, so maybe?

**Comment by andymcgunagle** [comment]
Is there currently a way to use Material Symbols with the new app directory?

In the pages directory I would add them with a `<link rel="stylesheet" />` tag to the Head component in my _document.tsx file, but right now `<link rel="stylesheet" />` is [listed as unsupported in the new docs](https://beta.nextjs.org/docs/api-reference/metadata#unsupported-metadata).

**Reply by Akasiek** [reply]
I made it work by creating static css files for each import. If you'll go to the [example URL](https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0) of the import that google provides you'll see something like this:
```css
/* fallback */
@font-face {
  font-family: 'Material Symbols Rounded';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialsymbolsrounded/v109/syl0-zNym6YjUruM-QrEh7-nyTnjDwKNJ_190FjpZIvDmUSVOK7BDB_Qb9vUSzq3wzLK-P0J-V_Zs-QtQth3-jOc7TOVpeRL2w5rwZu2rIelXxc.woff2) format('woff2');
}

.material-symbols-rounded {
  font-family: 'Material Symbols Rounded';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-feature-settings: 'liga';
  -webkit-font-smoothing: antialiased;
}
```

Copy it, create `materialSymbolsRounded.css` file and paste the code. Now you can import this file in your `layout.tsx` or `app.tsx`. 

Just a heads up. The `src` may change so I think it's not a permanent solution.

**Reply by luanmm** [reply]
I'm using with local fonts. If interests anyone, check below.

Material symbols NPM package installation (just for simplicity, but you may reference, below, the `woff2` font file directly if you want):

```sh
npm install material-symbols --save
```

In your (root) `layout.tsx` file (in `app` directory):

```tsx
import localFont from 'next/font/local'
import './global.css'

const materialSymbols = localFont({
  variable: '--font-family-symbols', // Variable name (to reference after in CSS/styles)
  style: 'normal',
  src: '../node_modules/material-symbols/material-symbols-rounded.woff2', // This is a reference to woff2 file from NPM package "material-symbols"
  display: 'block',
  weight: '100 700',
})

export default function Layout(props: React.PropsWithChildren) {
  const { children } = props

  return (
    <html className={`${materialSymbols.variable}`}>
      <body>{children}</body>
    </html>
  )
}
```

In your `global.css` (or any other global styles file that you have):

```css
i.symbol {
  font-family: var(--font-family-symbols); // Variable declared in local font configuration
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
  font-feature-settings: 'liga';
}
```

The definition above was copied from the original configuration used in [Material Icons/Symbols repository](https://github.com/google/material-design-icons), which is the same as Google Fonts generated CSS.

In any component:

```tsx
export default function Icon() {
  return (
    <i className="symbol">face</i> // Use as documented in Material System guide
  )
}
```

Hope it helps someone or the overall discussion here.

I would love to have this declarations simplified directly in the `next/font` optimization API somehow (or symbols be imported directly as any other fonts, like people suggested in this thread).
