### DISCUSSION TITLE
next.js app doesn't look the same as it looks in the local environment

### DISCUSSION THREAD

**Discussion by lithika-damnod** [vercel/next.js#42982] [Help] [answered]
This is the desired output: https://sampathmotors.vercel.app
What I get after deploying: https://ecommerce-nextjs-dun.vercel.app
Repo: https://github.com/lithika-damnod/ecommerce-nextjs

I'm stuck on this issue. 
Can somebody help me plz.. 🙏

**Comment by icyJoseph** [comment, marked as answer]
At least when it comes to the `.btn` class a bunch of properties are missing on e-commerce site:

```css
.btn {
    align-items: center;
    border-radius: 0.5em;
    color: #000;
    cursor: pointer;
    display: flex;
    font-family: Fira Sans,sans-serif;
    font-weight: bolder;
    height: 40px;
    justify-content: center;
    opacity: 62%;
    width: 130px;
}
```

The funny part is that I see them here: https://github.com/lithika-damnod/ecommerce-nextjs/blob/master/styles/Button.module.css

That in turn made me check the source code, and I found a floating `;`  in line 300.

![Screenshot 2022-11-16 at 11 00 30](https://user-images.githubusercontent.com/21013447/202149985-de80149c-e580-422c-8978-bbe5c5c08045.png)

Which made look into the Hero module, which at the last line, https://github.com/lithika-damnod/ecommerce-nextjs/blob/master/styles/Hero.module.css#L137, does indeed have a floating `;`

I removed it, `npm run build && npm run start` and voila! It works.

> Note: You might observe this only in production mode, because the CSS is minified, so the floating `;` becomes into an issue
