### DISCUSSION TITLE
Unable to configure docker-compose with headleass WordPress + nginx + nextjs

### DISCUSSION THREAD

**Discussion by debonx** [vercel/next.js#43152] [Help]
Hello there, 

I have an issue of (probably) networking between my frontend (running `nextjs`) and my backend service (headless `WordPress` + `nginx`). Basically when I compose `nextjs` it doesn't recognize the backend host. Let me explain :information_source: 

My `docker-compose.yml` is the following:

```
version: '3.9'

services:
  # backend
  nginx:
    image: nginx:latest
    container_name: my-app-nginx
    hostname: my-app-nginx
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - "./backend/nginx/:/etc/nginx/templates/"
      - ./backend/src:/var/www/html/backend:rw,cached
      - ./backend/certs:/etc/certs
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN_MAIN=my-app.test"
      - "DOMAIN_API=api.my-app.test"
    depends_on:
      - wordpress
    restart: always

  mysql:
  ...

  wordpress:
  ...
   
  # frontend
  nextjs:
    build:
      context: ./frontend
      dockerfile: next.Dockerfile
    container_name: my-app-next
    restart: always
    depends_on:
      - nginx
    ports:
      - "81:80"
      - "3031:3000"

 # for the experiment
  curl:
    image: curlimages/curl:latest
    ports:
      - "3030:3000"
    stdin_open: true
    tty: true

networks:
  default:
    driver: bridge
    name: my-app
```

## What happens?
- when I run `docker-compose up -d` all services and network get created correctly.
- I can run `docker-compose run --rm curl http://my-app-nginx/wp-json/rm/v1/config` and I get the correct response :rocket: !

## What's the issue then :sob: ?
Nextjs actually doesn't build. It doesn't recognize the host within its `next.Dockerfile`, specified in `docker-compose.yml`.
I set the `next.Dockerfile` for the sake of the experiment as following:
```
FROM node:18-alpine AS builder
WORKDIR /app
RUN apk --no-cache add curl

### I try here to curl with the name of my nginx container inside here
RUN curl -v -o - -I http://my-app-nginx/wp-json/rm/v1/config
```

When I run `docker-compose up -d --force-recreate --build nextjs` it returns the following:
```
...
Could not resolve host: my-app-nginx
* Closing connection 0
curl: (6) Could not resolve host: my-app-nginx
...
```

Maybe it's easier than I think. But I cannot see why this happens and I am not very expert with docker.
Any suggestion would be gold at this point. :pray: :pray: :pray: 

Thanks a lot.
