### DISCUSSION TITLE
any plan to support `unicode-range` on `next/font/google` ?

### DISCUSSION THREAD

**Discussion by shifenhutu** [vercel/next.js#47309] [Ideas]
### Goals

i am sorry for my bad english， i used google translate my words

I want to set different fonts for different texts, such as using **Jost** font for English and **Noto Sans SC** font for Chinese.

here is my code

```tsx
import { Jost, Noto_Sans_SC } from 'next/font/google'

const jost = Jost({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
})

const noto_sans_SC = Noto_Sans_SC({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  unicodeRange: ["U+41-5A","U+61-7A", "U+C0-FF"], // use Noto_Sans_SC if in this unicode Range
})

 
 

```
 

### Non-Goals

1.
2.
3.

### Background

I want to set different fonts for different texts, such as using **Jost** font for English and **Noto Sans SC** font for Chinese.

### Proposal

i have no idea

**Comment by leafertw** [comment]
I would also like to see this happen!

**Comment by krismorf** [comment]
You might not need `unicode-range`. You can use `adjustFontFallback: false` on your Chinese font. Example below loads Noto Sans font for arabic characters and Roboto for the missing characters.

```jsx
import { Noto_Sans_Arabic, Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ['arabic'],
  display: 'swap',
  adjustFontFallback: false,
})
```

You can then load both fonts. 
```
{locale !== 'ar' ? (
  <style jsx global>
    {`
      :root {
        --sans-font: ${roboto.style.fontFamily};
      }
    `}
  </style>
) : (
  <style jsx global>{`
    :root {
      --sans-font: ${notoSansArabic.style.fontFamily},
        ${roboto.style.fontFamily};
    }
  `}</style>
)}
```

The browser will fill in all chinese characters with the first font, then use the second font for the latin characters.

**Reply by seho0808** [reply]
I tried your approach but most fonts don't seem to support subsets of multiple languages. They only have "latin" and "latin-ext".
Hence, it is hard to implement a page with multiple languages at once.

**Reply by bethanyfish** [reply]
This helped immensely! Thanks so much!

**Reply by ahmedsaed** [reply]
OMG, finally. I have been searching a lot for a solution. don't know why this is not common on search results

**Comment by seho0808** [comment]
I gave up on using nextjs font, and just went with custom font-face.
```css
@font-face {
  font-family: "CustomFont";
  src: url("/fonts/NanumGothic-Regular.ttf") format("truetype");
  font-style: normal;
}

@font-face {
  font-family: "CustomFont";
  src: url("/fonts/Karla-Medium.ttf") format("truetype");
  font-style: normal;
  unicode-range: U+0041-005A, U+0061-007A;
}
```
I added the above code to `global.css` and changed `layout.tsx` as below
```tsx
<html>
      <body className={`font-[CustomFont]`}>{children}</body>
</html>
```
I will update this post when I make this font face to act like the nextjs font.
