### DISCUSSION TITLE
Page scroll lags due to loading images

### DISCUSSION THREAD

**Discussion by dbrown2642** [vercel/next.js#47606] [Help]
### Summary

Hoping to get some advice with laggy scroll/display on my next.js website.

[Example of this happening](https://bak-site.vercel.app/projects/ervol2)

On the site, I use an S3 bucket with Cloudfront to store and access images (I know I'm not using the cleanest implementation). Normally this works great, but when I use my "image_gallery" module to display a number of images, the page glitches out quite a bit.

I've tested and it doesn't appear that react-medium-image-zoom has anything to do with my issue. I've also tried using Next/Image but didn't find that to affect things either.

I'd appreciate any advice with navigating this.

I've attached the code for my image_gallery module & its CSS for reference.

**image_gallery.js**
```js
import styles from "./image_gallery.module.css";
import MacWindow from "./mac_window";
import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'

export default function ImageGallery({ project, num, title}) {
  const img_url = process.env.NEXT_PUBLIC_CLOUDFRONT_URL;
  const array = Array.from({ length: num }, (_, i) => i + 1);
  const content = (
    <div className={`polkaBackground ${styles.grid}`}>
      {array.map((val) => {
        return (
            <div key={val} className={styles.photoContainer}>
              <Zoom>
                <img
                  className={`${styles.projectPhoto}`}
                  src={`${img_url}/projects/${project}/gallery/${val}.jpg`}
                />
              </Zoom>
            </div>
        );
      })}
    </div>
  );

  return (
    <div className={styles.window}>
      <MacWindow title={title} content={content} header={false} />
    </div>
  );
}
```

**image_gallery.module.css**
```css
.window {
  max-width: var(--max-width-project);
}

.grid {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  width: 100%;
  border: 0.15rem solid var(--off-black);
  gap: .8rem;
  padding: .8rem;
}

.photoContainer {
  display: flex;
  position: relative;
}

.projectPhoto {
  width: 100%;
  object-fit: cover;
  aspect-ratio: 4/3;
  border: 0.15rem solid var(--off-black);
  cursor: zoom-in;
}

@media (max-width: 700px) {
  .grid {
    grid-template-columns: 1fr;
  }
}
```

### Example

https://bak-site.vercel.app/projects/ervol2
