### DISCUSSION TITLE
Swapping an Image on hover

### DISCUSSION THREAD

**Discussion by Nfinished** [vercel/next.js#48925] [Help]
### Summary

Wondering what the best practice is here. Handle hover with state and swap two image components? iirc an Image's src has to be static

**Comment by icyJoseph** [comment]
You mean something like:

```css
.cross-fade {
  position: relative;
}

.cross-fade img {
  position: absolute;
  opacity: 0;
  transition: opacity 0.25s ease-in-out;
} 

.cross-fade img:first-child {
  opacity: 1;
}

.cross-fade:hover img {
  opacity: 1;
}

.cross-fade:hover img:first-child {
  opacity: 0;
}

```

And HTML:

```html
<div class="cross-fade">
  <img src="https://picsum.photos/200/300" />
  <img src="https://picsum.photos/id/237/200/300"/>
</div>
```

Take that to a codepen [pen.new](https://pen.new)
