### DISCUSSION TITLE
NextJS application in k8s cluster with Nginx Ingress using TLS/SSL. Only loads initial static html page

### DISCUSSION THREAD

**Discussion by gurkang** [vercel/next.js#48976] [Help]
### Summary

I'm trying to get my application up and running in my k8s cluster. However it's not correctly loading the application, especially styling/css when it's deployed in the cluster. 

If I port-forward the service I can correctly see the application.

What the website should look like and what it looks like just port-forwarding the `svc`:
<img width="1500" alt="Screenshot 2023-04-29 at 11 19 50" src="https://user-images.githubusercontent.com/9166287/235283169-9ef53d11-f79d-4682-a799-49ee6789d6d0.png">

What it looks like deployed using nginx ingress:

<img width="1512" alt="Screenshot 2023-04-29 at 11 20 40" src="https://user-images.githubusercontent.com/9166287/235283200-749a8960-da77-4fd1-9fe3-469ac074848a.png">

I'm seeing some errors in the console as well:

```js
caught SyntaxError: Unexpected token '<'
framework-2c79e2a64abdb08b.js:1 Uncaught SyntaxError: Unexpected token '<'
main-17a9a24315ee9390.js:1 Uncaught SyntaxError: Unexpected token '<'
_app-2afab9796c6a6373.js:1 Uncaught SyntaxError: Unexpected token '<'
index-b6e8e964ce5feab0.js:1 Uncaught SyntaxError: Unexpected token '<'
_buildManifest.js:1 Uncaught SyntaxError: Unexpected token '<'
_ssgManifest.js:1 Uncaught SyntaxError: Unexpected token '<'
```

I'm totally confused on what's going on here. There seems to be some issues with nextjs loading the css/styling when behind an ingress, but not when it's just port-forwarded from a service?
Is the SSL/TSL messing things up for the application?

### Additional information

```js
deployment file with ingress and service.


apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationName
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applicationName
  template:
    metadata:
      name: applicationName
    spec:
      containers:
        - name: applicationName
          image: image
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: applicationName-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: applicationName-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - applicationName.domain.cloud
      secretName: prod-applicationName-tls-secret
  rules:
    - host: applicationName.domain.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: applicationName-svc
                port:
                  number: 80
```

**Comment by ghost** [comment]
Were you able to fix this? If so, I’m interested to know how as I’m having a very similar problem.

**Reply by tadghh** [reply]
I came up with this, css works along with static. Havent tested ssr or anything though. Favicon and public would need their paths handled too.
```js
const nextConfig = {
	assetPrefix: "/nextjs",
	output: "standalone",
	async rewrites() {
	return [
	{
	     source: "/nextjs/_next/:path*", // Rewrite requests to /_next/ to /nextjs/_next/
             destination: "/_next/:path*",
	   },
	];
   },
};
```

Using haproxy I have the following paths setup for my ingress, this allows me to access other nextjs pages and not be redirected to /. Not sure if its "proper", still learning.

```yaml
annotations:
     haproxy.org/path-rewrite: |
        /nextjs/(.*) /\1    
     ingress.class: "haproxy"
paths:
      - path: /nextjs/
        pathType: Prefix
        backend:
          service:
            name: nextblogy-kube-service
            port:
              number: 8080
      - path: /nextjs/(.*)
        pathType: Prefix
        backend:
           service:
            name: nextblogy-kube-service
            port:
              number: 8080
      - path: /.next/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: nextblogy-kube-service
            port:
              number: 8080
      - path: /_next/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: nextblogy-kube-service
            port:
              number: 8080
```
