### DISCUSSION TITLE
Next.js cache for Github actions not working

### DISCUSSION THREAD

**Discussion by ImBIOS** [vercel/next.js#49089] [Help]
### Summary

I have been following the Next.js docs for continuous integration and everything has been working except the caching. The cache is being created, but npm seems to not recognize the cache.

I used the Firebase CLI to generate the workflow .yml files but added what the Next docs said so that I can deploy my Firebase and Next.js app as soon as I push a change to my repository.

The cache is being stored and accessed in te actions/cache@v3 action but on the actions/checkout@main it is not being recongized.

![image](https://user-images.githubusercontent.com/41441643/235669133-f876b7b6-ffdb-4af9-98c2-2c3e50b8f6d6.png)

Action actions/cache@v3:

```
Run actions/cache@v3
Received 37748736 of 186316347 (20.3%), 35.9 MBs/sec
Received 150994944 of 186316347 (81.0%), 71.9 MBs/sec
Received 186316347 of 186316347 (100.0%), 66.6 MBs/sec
Cache Size: ~178 MB (186316347 B)
/usr/bin/tar -xf /home/runner/work/_temp/96ae133a-ac04-4ff2-b31d-ba5f3579ece7/cache.tzst -P -C /home/runner/work/secure-pi/secure-pi --use-compress-program unzstd
Cache restored successfully
Cache restored from key: Linux-nextjs--
```

npm ci --force && npx next build && npx next export:

```
added 607 packages, and audited 608 packages in 52s

115 packages are looking for funding
  run `npm fund` for details

6 vulnerabilities (2 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
info  - Loaded env from /home/runner/work/secure-pi/secure-pi/.env
warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
```

firebase-hosting-merge.yml:

```yml
name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - uses: actions/checkout@main
      - run: npm ci --force && npx next build && npx next export
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.MY SERVICE ACCOUNT }}"
          channelId: live
          projectId: MY PROJECT ID
```

Can someone help?

Thanks in advance!

### Additional information

Related #49091
