### DISCUSSION TITLE
GitHub Action Cache not working with Next.js Cache

### DISCUSSION THREAD

**Discussion by ImBIOS** [vercel/next.js#49091] [Help]
### Summary

I was working to implement Continuous Integration with Next.js, but found out the cache only used when it's my PR but when the rest of my team make a PR, it says no cache found even there are a bunch of cache created within several hours because of this bug.

ci file:
```yml
name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - develop
      - 'feature/dev-**'

jobs:
  ci:
    name: Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: '⏰ Set timezone for Date testing'
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: 'Asia/Jakarta'
      - name: '☁️ Checkout repository'
        uses: actions/checkout@v3
      - name: '📦 Cache node modules'
        id: cache-npm
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: '🔧 Use Node.js from .node-version'
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: '📦 List the state of node modules'
        continue-on-error: true
        run: npm list
      - name: '📦 Install dependencies'
        run: npm ci
      - name: '🧪 Run unit tests'
        run: npm run test:unit
      - name: '📦 Build'
        run: npm run build
```

### Additional information

next info:
```


    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112
    Binaries:
      Node: 18.15.0
      npm: 9.5.0
      Yarn: N/A
      pnpm: 8.3.1
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.2
      react: 18.2.0
      react-dom: 18.2.0


```

duplicate cache:
![image](https://user-images.githubusercontent.com/41441643/235672418-32915842-e8dd-4932-a215-38bf762a493b.png)

Related #49089
