### DISCUSSION TITLE
EROFS: read-only file system, open '/app/.next/package.json'

### DISCUSSION THREAD

**Discussion by sanalpanicker** [vercel/next.js#51376] [Help] [answered]
### Summary

I am getting EROFS: read-only file system, open '/app/.next/package.json' when deploying nextJS 13 app in a container. I am thinking a read-only file system won't work because we change the .next folder in runtime.
What Is the workaround?

### Additional information

```js
## Error:

- ready started server on 0.0.0.0:7442, url: http://localhost:7442
- info Loaded env from /app/.env.development
[Error: EROFS: read-only file system, open '/app/.next/package.json'] {
  type: 'Error',
  errno: -30,
  code: 'EROFS',
  syscall: 'open',
  path: '/app/.next/package.json'

## dockerfile:

COPY . /
WORKDIR /

RUN chmod +x startup.sh

ENTRYPOINT ["/startup.sh"]

## startup.sh

if [[ "$NODE_ENV" == "production" ]]; then
  yarn start
elif [[ "$NODE_ENV" == "development" ]]; then
  yarn dev
  else
  echo "Invalid environment specified. Please set the ENVIRONMENT variable to 'production' or 'development'."
fi
```

**Comment by sanalpanicker** [comment, marked as answer]
I fixed this by updating the container file system to writable.

**Reply by Far-1d** [reply]
i'd appreciate if you explain how you did it

**Reply by sanalpanicker** [reply]
```
container:
  emptyDirSizeLimit: <>
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    **readOnlyRootFilesystem: false**
```
    

  setting it in helm chart
