### DISCUSSION TITLE
@next/font + font-feature-settings

### DISCUSSION THREAD

**Discussion by bradwoods** [vercel/next.js#52456] [Ideas]
Requesting this issue be reopened - https://github.com/vercel/next.js/issues/41862

**Comment by lightwalker-eth** [comment]
+1 on this request. For security reasons it's very important for our use case to make use of the disambiguation capability in Inter. Without this, characters such as 1, i, and l can appear similar.

More details here: https://rsms.me/inter/#features/ss02

**Comment by joulev** [comment]
I think you have to self-host fonts here, as I don't think the Inter version hosted on Google Fonts support those features. You can try it by using Google's font file directly e.g.

```css
/* Taken from the CSS file returned by Google Fonts */
@font-face {
  font-family: "Inter";
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hjp-Ek-_EeA.woff)
    format("woff");
  font-feature-settings: "ss02";
}
```

and you will notice that the feature doesn't work.

If you self-host the font by downloading from https://rsms.me directly, you can then use `next/font/local` with [`declarations`](https://nextjs.org/docs/app/api-reference/components/font#declarations) to customise the `@font-face` declaration.

```ts
const inter = localFont({
  src: [...],
  display: "swap",
  declarations: [{ prop: "font-feature-settings", value: "ss02" }],
  variable: "--sans",
});
```
