### DISCUSSION TITLE
Warning: Extra attributes from the server: deluminate_imagetype

### DISCUSSION THREAD

**Discussion by hoosin** [vercel/next.js#53277] [Help]
### Summary

When you use a div to simulate a button in your Next.js project and control different state (background-image) styles using classnames, you may encounter a warning: "Warning: Extra attributes from the server: deluminate_imagetype". This warning is likely caused by the addition of an unsupported attribute named deluminate_imagetype on the div element during server-side rendering.

I'm not entirely certain whether this issue is specific to Next.js or not. However, it seems to be related to how the server renders the div with the extra attribute, resulting in the warning message.

<img width="678" alt="image" src="https://github.com/vercel/next.js/assets/3365399/724440bf-eb42-40e1-b3db-68a8b08bf453">

```tsx


import styles from './app.module.css'
import cx from 'classnames'
import { useState } from 'react'

export default function Wheel({ onclick }: { onclick: (is3D: boolean) => void }) {
  const [is3D, setIs3D] = useState(true)

  const toggleSwitch = () => {
    onclick && onclick(!is3D)
    setIs3D(!is3D)
  }

  return (
    <div
      onClick={toggleSwitch}
      className={cx(styles.wheel, {

        [`${styles.wheel3d}`]: is3D,
        [`${styles.wheel2d}`]: !is3D,
      })}
    />
  )
}

```

app.module.css
```css
.wheel {
  float: right;
  width: 244px;
  height: 68px;

  background-size: 100% 100%;
  cursor: pointer;
}
.wheel2d {
  background-image: url('/images/2d.png');
  background-repeat: no-repeat;
}
.wheel3d {
  background-image: url('/images/3d.png');
  background-repeat: no-repeat;
}
```
