### DISCUSSION TITLE
In devtools are anothers file than in server.

### DISCUSSION THREAD

**Discussion by meridPL** [vercel/next.js#53363] [Help]
### Summary

Hello,

I have one app which I deploy on two servers. The first app is on port 3000 and language PL and the second is on port 3001 language DE. If I build_de and start on port 3000 everything is good, but on port 3001 not work PL and DE. When I open devtools and open the tab Source I see different files than on the server. I use bitbucket pipelines and a server run by PM2. What can be the reason?

PL
![image](https://github.com/vercel/next.js/assets/14768785/93743acb-f543-4474-8d81-6fc756292817)
DE
![image](https://github.com/vercel/next.js/assets/14768785/4842e91a-75ac-4e7b-a3a5-eb88ed84710b)

### Additional information

```
image: atlassian/default-image:3

pipelines:
  branches:
    dev:
      - step:
          name: Build & Deploy artifacts using RSYNC to DEV PL
          image: node:16.14.0
          deployment: dev-pl
          artifacts:
            - .next/**
          script:
            - yarn install
            - yarn clean
            - yarn build_pl
            - pipe: atlassian/rsync-deploy:0.8.1
              variables:
                USER: $SSH_USER
                SERVER: $SSH_HOST
                REMOTE_PATH: $PROJECT_PATH_PL
                LOCAL_PATH: '.next'
                EXTRA_ARGS: '-avz'
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SSH_HOST
                COMMAND: 'cd $PROJECT_PATH_PL && sh _deploy.sh'
                PORT: 22
     - step:
         name: Build & Deploy artifacts using RSYNC to DEV DE
         image: node:16.14.0
         deployment: dev-de
         artifacts:
           - .next/**
         script:
           - yarn install
           - yarn clean
           - yarn build_de
           - pipe: atlassian/rsync-deploy:0.8.1
             variables:
               USER: $SSH_USER
               SERVER: $SSH_HOST
               REMOTE_PATH: $PROJECT_PATH_DE
               LOCAL_PATH: '.next'
               EXTRA_ARGS: '-avz'
           - pipe: atlassian/ssh-run:0.4.1
             variables:
               SSH_USER: $SSH_USER
               SERVER: $SSH_HOST
               COMMAND: 'cd $PROJECT_PATH_DE && sh _deploy.sh'
               PORT: 22
```
