### DISCUSSION TITLE
Deployed on Azure - After Authentication going to localhost

### DISCUSSION THREAD

**Discussion by NoobFullStack** [vercel/next.js#53591] [Help]
### Summary

I am trying to get the [Supabase Starter](https://github.com/vercel/next.js/tree/canary/examples/with-supabase) working on Azure; but, when I use the signin function, the browser goes to 'localhost'; which isn't working on an Azure deployment.. 

How can I fix this? 

In the code I see:
```
  if (error) {
    return NextResponse.redirect(
      `${requestUrl.origin}/login?error=Could not authenticate user`,
      {
        // a 301 status is required to redirect from a POST to a GET route
        status: 301,
      }
    )
  }

  return NextResponse.redirect(requestUrl.origin, {
    // a 301 status is required to redirect from a POST to a GET route
    status: 301,
  })
}

```

Should I hardcode the `requestUrl` to my own domain? 
Or make this an environment variable? 

What's the best way to handle this? I do notice that I'm authenticated when I manually refresh the page. 

my azure.yml file:
```
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - iconsensei-supabase

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'iconsensei-supabase'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C68 }}
          package: .
```

### Example

https://github.com/vercel/next.js/tree/canary/examples/with-supabase
