### DISCUSSION TITLE
Using App Router for exported SSG connected to API

### DISCUSSION THREAD

**Discussion by bazylhorsey** [vercel/next.js#54039] [App Router]
We are trying to migrate to the app router to create an exported SSG, we had it working with pages, but would like to switch to App Router.

Take this example config:
```
/** @type {import('next').NextConfig} */
const config = {
  output: 'export',
  // trailingSlash: true,
  reactStrictMode: false,
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/,
      use: ['@svgr/webpack'],
    });
    return config;
  },
  // other config here, feel free to replace whatever
};

module.exports = config;
```

We are playing around with removing trailing slash as well, but does not seem easily supported in the file server we tried.

To test use any next.js app project (assuming its built and an out/ dir exists) and start this docker compose (docker compose up):
```
version: '3.8'
services:
  caddy_reverse_proxy:
    container_name: caddy_test
    image: caddy:alpine
    restart: always
    ports:
      - 80:80
    environment:
      - EXT_ENDPOINT1=${EXT_ENDPOINT1}
      - LOCAL_1=${LOCAL_1}
      - LOCAL_2=${LOCAL_2}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./out:/code/static
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
```

.env:
```
EXT_ENDPOINT1="example.com"
EXT_ENDPOINT2="127.0.0.1"
LOCAL_1="localhost"
LOCAL_2="127.0.0.1"
```

caddy/Caddyfile:
```
{
  email example@example.com
}

static.{$EXT_ENDPOINT1}:80, static.{$LOCAL_1}:80, static.{$LOCAL_2}:80 {
  root * /code/static
  file_server browse
}
```

EXPECTED BEHAVIOR:
The app should run by finding the base index file. If theres a trailing slash than it should find the index.html, although maybe its possible while set to false/defaulted-null.

Other questions:
- Are there any other considerations for this architecture? We would like the benefits of next.js for a use-case more designed for normal react but with page seperation and next.js style routing.
- Are there any caveats to dynamic data on these pages such as external api requests using fetch or axios?
