### DISCUSSION TITLE
[URGENT] Couldn't find any `pages` or `app` directory. Please create one under the project root

### DISCUSSION THREAD

**Discussion by katiesun138** [vercel/next.js#54564] [Help]
### Summary

Hi, I am trying to dockerize my nextjs application (app directory - next13.4), however I am encountering this issue when I run "docker-compose -up" - "Couldn't find any `pages` or `app` directory. Please create one under the project root"
My file hierarchy looks like this:
_my-app name
___.next
___.vscode
___app
______[locale]
_________//here i have my files to the pages.tsx
______api
_________//here i have my files to the routes.tsx
___data
___docker-app
___lib
___nodemodules
___prisma
___public
___.dockerignore
___Dockerfile
___docker-compose.yml

This is what my Dockerfile looks like:
```
FROM node:18-alpine as dependencies

WORKDIR /app
COPY package*.json ./

RUN npm install

FROM node:18-alpine as build

WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

RUN npx prisma generate
COPY migrate-and-start.sh .
RUN chmod +x migrate-and-start.sh

FROM node:18-alpine as deploy

WORKDIR /app

ENV NODE_ENV production

COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/prisma ./prisma

EXPOSE 3000

ENV PORT 3000

CMD [ "npm", "run", "build" ]

```

Here is my docker-compose.yml file:
```
version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: myhost
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  mywebsite-app:
    image: mywebsite
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    volumes:
      - postgres-data:/app/postgres-data
    environment:
      DATABASE_URL: postgresql://test:test@myhost:5433/mywebsite?schema=public&connect_timeout=60
    ports:
      - 3000:3000
volumes:
  postgres-data:
```

Finally, here is the scripts in package.json:
```
"scripts": {
    "dev": "prisma generate  && next dev",
    "build": "prisma generate && next build",
    "start": "next start",
... 
}
``` 
Thank you in advance!
