### DISCUSSION TITLE
Setting responsive dimensions on next/image component

### DISCUSSION THREAD

**Discussion by TomBell95** [vercel/next.js#55731] [Help]
### Background
While working with the next/image component, I'm trying to create an image that fills its parent without explicitly defining its width or height.

### Expected Behavior
I want the image to automatically adjust its dimensions based on its parent container's dimensions without explicitly specifying its width or height.

### Actual Behavior
Currently, I can only achieve the desired behavior using what feels like a "hacky" solution where I have to define both width and height.

### Working - "hacky" example:
```javascript
<Image
  src={fileUrl}
  className={classes.image}
  width={300}
  height={300}
/>
```
```scss
.image {
  object-fit: cover;
  max-width: 80vw;
  max-height: 80vh;
  min-height: auto;
  min-width: 30vw;
  width: auto;
  height: auto;

  @include extra-small-break {
    min-height: 50vh;
    min-width: 75vw;
  }

  @include small-break {
    min-height: 30vh;
    min-width: 90vw;
  }

  @include mid-break {
    min-height: 20vh;
  }
}
```

### Not working - Ideal solution:
```javascript
<div className={classes.imageWrapper}>
   <Image src={fileUrl} className={classes.image} fill />
</div>
```
```scss
.imageWrapper {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;

  max-width: 80vw;
  max-height: 80vh;
  min-height: 10vh;
  min-width: 30vw;

  @include extra-small-break {
    min-height: 50vh;
    min-width: 75vw;
  }

  @include small-break {
    min-height: 30vh;
    min-width: 90vw;
  }

  @include mid-break {
    min-height: 20vh;
  }
}

.image {
  object-fit: cover;
}
```

Any suggestions on how to approach this?

### Additional information

```js
Other examples: 
- https://stackoverflow.com/a/76008677/15369125
- https://github.com/vercel/next.js/discussions/53025#discussioncomment-6517609
- https://github.com/vercel/next.js/discussions/18474#discussioncomment-5501724
```
