### DISCUSSION TITLE
Suspense fires too late/twice

### DISCUSSION THREAD

**Discussion by EliasVal** [vercel/next.js#56011] [Help]
### Summary

Hello! I have a project that uses Next.js `v13.5.3` and when I enter a page, it loads the page, flashes the `loading.tsx` component and hides it.

I'm not sure if my understanding of loading/Suspense is flawed or if a part of the code is flawed.

Intended Behavior:
* Enter URL
* Immediately see loading fallback
* Then see actual page once loading is finished

### Additional information

I have a simple `loading.tsx` file in the `app/` folder.

```js
export default function loading() {
  return (
    <span className='h-screen w-full flex justify-center items-center'>
      <span className='animate-ping relative flex h-10 w-10  rounded-full bg-purple-400 opacity-75' />
    </span>
  );
}
```

`next info`:

```yaml
Operating System:        
  Platform: win32        
  Arch: x64
  Version: Windows 10 Pro
Binaries:
  Node: 18.17.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 13.5.3
  eslint-config-next: 13.5.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

`package.json`:

```json
"dependencies": {
  "@emotion/cache": "^11.11.0",
  "@emotion/react": "^11.11.1",
  "@emotion/styled": "^11.11.0",
  "@mui/icons-material": "^5.14.9",
  "@mui/material": "^5.14.10",
  "@mui/x-date-pickers": "^6.14.0",
  "@next/bundle-analyzer": "^13.5.2",
  "dayjs": "^1.11.10",
  "lodash": "^4.17.21",
  "next": "13.5.4-canary.0",
  "next-intl": "3.0.0-beta.18",
  "overlayscrollbars": "^2.3.1",
  "overlayscrollbars-react": "^0.5.2",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "react-signature-canvas": "^1.0.6",
  "stylis": "^4.3.0",
  "stylis-plugin-rtl": "^2.1.1",
  "sweetalert2": "^11.7.28",
  "sweetalert2-react-content": "^5.0.7"
},
"devDependencies": {
  "@trivago/prettier-plugin-sort-imports": "^4.2.0",
  "@types/lodash": "^4.14.198",
  "@types/node": "^20.6.3",
  "@types/react": "18.2.22",
  "@types/react-dom": "18.2.7",
  "@types/react-signature-canvas": "^1.0.2",
  "@types/stylis": "^4.2.0",
  "@typescript-eslint/eslint-plugin": "^6.7.2",
  "@typescript-eslint/parser": "^6.7.2",
  "autoprefixer": "10.4.16",
  "eslint": "^8.49.0",
  "eslint-config-next": "13.5.3",
  "eslint-config-prettier": "^9.0.0",
  "eslint-plugin-prettier": "^5.0.0",
  "npm-check": "^6.0.1",
  "postcss": "^8.4.30",
  "prettier": "3.0.3",
  "sass": "^1.68.0",
  "tailwindcss": "3.3.3",
  "typescript": "5.2.2"
}
```
