### DISCUSSION TITLE
Production deployment is broken because of next/font

### DISCUSSION THREAD

**Discussion by pirmax** [vercel/next.js#56642] [Help]
### Summary

Hi,

I want to do an `npm run build` during a pipeline on GitLab, but the build is not performed correctly. I'm on NodeJS 18.

My .gitlab-ci.yml file :

```
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

stages:
  - build
  - deploy

build:
  stage: build
  image: node:18-alpine
  variables:
    NODE_ENV: "production"
  before_script:
    - apk add --update bash
    - apk add --update git && rm -rf /tmp/* /var/cache/apk/*
    - apk add --no-cache g++ make py3-pip libc6-compat
    - npm install
  script:
    - npm run build
```

![image](https://github.com/vercel/next.js/assets/1739235/fe0fe82b-7f4d-44d5-9622-87d3852b9c6b)

### Additional information

```js
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Binaries:
  Node: 18.18.0
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.5.4
  eslint-config-next: 13.5.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: standalone
```
