### DISCUSSION TITLE
Dynamic Environment File

### DISCUSSION THREAD

**Discussion by beyondsensor** [vercel/next.js#58585] [App Router]
### My Issue 

Hi there, I am using NextJS to build my web application and I dockerized my project, so that I can easily deploy it for my projects. I am running into an issue where my environment variables is not taken in from docker, as I understood that this is because next build actually embeds the environment variables into the codes during build time. 

### My Current Workaround 

As part of my docker container, I had to use next dev to run my service, (instead of run start). By doing so, the environment variables will be read from my instance, and updated accordingly. 

**This is my docker build scripts** 
```
# Use an official Node.js runtime as a parent image
FROM node:21-alpine3.17

# Set the working directory in the container
WORKDIR /anpr-smart-frontend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Install dependencies using Yarn
RUN yarn install --frozen-lockfile

# Copy the rest of the application code to the working directory
COPY . .

# Build the Next.js application
RUN npm run build

# Expose the port that the Next.js application will run on
EXPOSE 3000

# Command to start the application
CMD ["yarn", "dev"]
```

**This is my docker compose script** 
```
  # ANPR-Dashboard    
  frontend:
    image: smart-anpr-frontend
    container_name: smart-anpr-frontend
    environment:
      - BASE_URL=http://something-new-hurray.com ### The Variable 
    ports:
      - '1001:3000'
```

### My Question 

1. I wanted to check if whether this is the only workaround, of if anyone has any better solutions out there for me to resolve this. It is actually very simple, I want my environment variables defined to be loaded in run time, so that I can flexibily deploy my applications in other sites, without any specific builds for my customers. 
2. I would like to check if anyone had been using dev mode for their productions, and if there is any implications which I would need to be aware of. My services are designed to serve only no more than 10 Clients at any one time, so the load is actually not that big.
