### DISCUSSION TITLE
NextJS server rendered page fails to call my backend node app for multi containerization of services

### DISCUSSION THREAD

**Discussion by myselfuser1** [vercel/next.js#58635] [Help] [answered]
### Summary

I am trying to learn `docker`. I have a `next.js` app and a `node.js` app.

In my` next.js` app, in `page.tsx` I am calling my `backend` api

```
export const revalidate = 0;

export default async function Home() {
  const response = await fetch("/api/getRandomNumber");
  const data = await response.json();
  console.log(data);

  return (
    <main className={styles.main}>
      <h1>{data.lastInfo.randomNumber}</h1>
    </main>
  );
}
```

In `nodejs` I have just created an endpoint `getRandomNumber` with `expressjs`

```
router.get("/getRandomNumber", async (req, res) => {
  const randNumber = `${Math.random() * 100}`;
  const info = new Info({ randomNumber: randNumber });
  await info.save();
  const lastInfo = await Info.findOne({
    where: { randomNumber: randNumber },
  });

  return res.status(200).send({ lastInfo });
});
```

I know `next.js` is a full stack framework, but here I am trying to learn how to `dockerize` multiple services so created separate `node.js` app

Below is my `docker` file for `next.js` app

```
FROM node:18-alpine

WORKDIR /usr/app

COPY ./package.json ./

RUN npm install

COPY ./ ./

CMD ["npm","run","dev"]
```

Below is my `docker` file for `node.js` app

```
FROM node:18-alpine

WORKDIR /usr/app

COPY ./package.json ./

RUN npm install

COPY ./ ./

CMD ["npm","run","dev"]
```

Next I want to use `nginx` so I created a folder for it and inside it I created `default.conf` and `Dockerfile.dev`

In `default.conf`

```
upstream nextapp {
    server nextapp:3000;
}

upstream nodeapp {
    server nodeapp:3001;
}

server {
    listen 80;

    location / {
        proxy_pass http://nextapp;
    }

    location /api {
        rewrite /api/(.*) /$1 break;
        proxy_pass http://nodeapp;
    }

    location /ws {
      proxy_pass http://nextapp;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
  }
}

```
So I am appending `/api` to my `nodejs` app via `default.conf`

In `Dockerfile.dev`

```
FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf
```

Then one `docker-compose.yml` file for `next.js`, `nginx` and `node.js`

```
version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - nodeapp
      - nextapp
  nodeapp:
    build:
      dockerfile: Dockerfile.dev
      context: ./nodeapp
    volumes:
      - /app/node_modules #don't try to override this folder
      - ./nodeapp:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  nextapp:
    build:
      dockerfile: Dockerfile.dev
      context: ./nextapp
    volumes:
      - /app/node_modules
      - ./nextapp:/app
    environment:
      - WDS_SOCKET_PORT=0
```

I am able to see my `node.js` app on http://localhost:3050/api/getRandomNumber but in my `next.js` app I get error when I try to call the `node.js` api. If I comment out the fetch call in my `next.js` app it works fine on `http://localhost:3050/`

If I try to call just  `/api/getRandomNumber` in `fetch` I get error saying `Failed to parse url`

<img width="1064" alt="POSKA" src="https://github.com/vercel/next.js/assets/127964629/d13551ee-e925-41c0-bdf1-43640756f434">

This issue happens because my page is a server rendered component. If i change it to a client rendered component in NextJS then it works fine. 

One way to resolve the issue for my server rendered component was to change the `fetch` endpoint to `http://nginx/api/getRandomNumber` but this seems extremely poor approach to me. Is there a way to directly call my node.js api by just passing `/api/getRandomNumber` in fetch for server rendered page as both `next.js` app and `node.js` app are hosted on same port 3050

### Example

https://github.com/kyadalu1/MultiContainerServiceSample
