### DISCUSSION TITLE
How to override cssnano config?

### DISCUSSION THREAD

**Discussion by xiaojundebug** [vercel/next.js#58711] [Help]
### Summary

See:
<https://github.com/cssnano/cssnano/issues/1526>

The following code does not work because the % was removed (Only production environment).

```css
@property --percent {
  syntax: '<percentage>';
  inherits: false;
  initial-value: 0%;
}

```

![image](https://github.com/vercel/next.js/assets/24448924/30aacb01-6c22-443c-af9e-d1f612634ed3)
