### DISCUSSION TITLE
Docker: No tests found, exiting with code 1, Run with `--passWithNoTests` to exit with code 0

### DISCUSSION THREAD

**Discussion by alamenai** [vercel/next.js#60744] [Help]
### Summary

I just started integrating Docker in my NextJS ( app router ) and I'm facing this issue regarding the test script:

[![enter image description here][1]][1]

Well, my tests are under `src` folder:

[![enter image description here][2]][2]

I made my `Dockerfile` like this:

```
FROM node:20-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN npm install pnpm -g

RUN pnpm install

RUN pnpm test

RUN pnpm cypress-run-component

COPY next.config.js ./next.config.js

RUN pnpm build

EXPOSE 3000

CMD [ "pnpm","start" ]
```

My `docker-compose` like this :

```
version: "3"
services:
  app:
    image: docker-esg-suite-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./.contentlayer:app/.contentlayer
      - ./public:app/public
      - ./scripts:app/scripts
      - ./src:app/src
      - ./ui:app/ui
    environment:
      - NODE_ENV=development
```

I tried to change the `testMatch` in jest.config.mjs` but It did not work:

```
import nextJest from "next/jest.js"

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: "./",
})

// Add any custom config to be passed to Jest
/** @type {import('jest').Config} */
const config = {
  // Add more setup options before each test is run
  // setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],

  testEnvironment: "jest-environment-jsdom",
  testMatch: ["<rootDir>/src/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x)"],
}

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
export default createJestConfig(config)

```

I got the same issue:

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/IYjue.png
  [2]: https://i.stack.imgur.com/DkkMh.png
  [3]: https://i.stack.imgur.com/1gzQD.png
