### DISCUSSION TITLE
Can't access to env variables value

### DISCUSSION THREAD

**Discussion by yasersharifi** [vercel/next.js#60774] [App Router]
I can't access to env variables in aws fargate

I use these:

- Next.js 14 - App Router
- fargate
- task definition -> set variable in task definition

### My env

```env
NEXT_PUBLIC_API_BASE_URL=https://example.com
```

### My dockerfile

```docker
#Use an official Node.js runtime as the base image
FROM node:alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./


# Install pnpm 
RUN npm install pnpm -g



# Install project dependencies
RUN pnpm install

# Copy the rest of the application code to the container
COPY . .

# Build the Next.js application
RUN npm run build

# Expose the port that the Next.js app will run on
EXPOSE 80

# Start the Next.js application
CMD ["npm", "run","start"]
```

**Comment by icyJoseph** [comment]
Hi,

Is the ENV var available during the build step?

**Reply by yasersharifi** [reply]
Hi,
No It's not available in build.

**Comment by ezeparziale** [comment]
Use docker compose:

`compose.yaml` file:
```
services:

  web:
    build: .
    container_name: nextjs-web
    hostname: nextjs-web
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://example.com
    networks:
      - nextjs_net

networks:
  nextjs_net:
    name: nextjs_net
```

or add your env vars during the build
