### DISCUSSION TITLE
accessing runtime ENV in a docker-compose

### DISCUSSION THREAD

**Discussion by Clumsy-Coder** [vercel/next.js#60947] [Help]
### Summary

How do I pass ENV to the docker-compose so it can be used in the docker container.

NOTE: I'm not talking about setting the ENV during the build process. I'm talking about setting the env when running the container using docker-compose?
NOTE: using App router

why?
I have a usecase where the docker image is build and pushed to a container registry. I can't have the ENV stored in the docker image. I prefer to set the ENV before running `docker-compose up`

The end goal for me is to pull the docker image from a container registry and use it in docker-compose, pass some ENVs and start the container with `docker-compose up`

### Additional information

I checked the example https://github.com/vercel/next.js/tree/canary/examples/with-docker-compose

The example only mentions using the ENV during the build process. I'm talking about passing ENV during the runtime.

this is something I'm hoping to use
```yaml

version: "3"

services:
  next-app:
    image: some-image:latest # not real image
    container_name: next-app
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    env_file:
      - ./.env
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
```
