### DISCUSSION TITLE
Dockerize production image with prisma

### DISCUSSION THREAD

**Discussion by FadyAmir223** [vercel/next.js#62890] [Help]
### Summary

Hi guys,

during docker build process the image can't access outside world like host machine on `localhost` or running containers like postgres database by service name (of docker-compose), but next.js build needs db for SSG.

I don't know how it is achieved in this repo because of the massive details
https://github.com/nemanjam/nextjs-prisma-boilerplate

## Attempts
- I wait the database inside the container to run before proceeding to the build.

###
- how does he access the postgresql by service name here
./envs/production-docker/.env.production.docker.local.example
```
POSTGRES_DB=npb-db-prod
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
```
if the solution within traefic proxy so how?

###
- the problem is that the data is not inside the image during the buile, so maybe the solution is to mount the data inside prisma folder which is copied inside the image
```yml
  npb-db-prod:
    volumes:
      - ./prisma/pg-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/data-prod
```
https://github.com/nemanjam/nextjs-prisma-boilerplate/blob/main/docker-compose.prod.yml
but is it even possble to run postgres instance inside the build !

## code
```yml
# docker-compose.stage.yml

version: '3.9'

services:
  app-stage:
    image: app-stage
    container_name: app-stage
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - ARG_DATABASE_URL=$DATABASE_URL
    command: sleep 10
    ports:
      - 3000:3000
    env_file:
      - ./envs/staging/.env.staging.docker.local
    networks:
      - internal-stage
    depends_on:
      - db-stage

  db-stage:
    image: postgres:16.2-alpine
    container_name: db-stage
    ports:
      - 5432:5432
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - ./prisma/pg-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/data-stage
    env_file:
      - ./envs/staging/.env.staging.docker.local
    networks:
      - internal-stage

networks:
  internal-stage:
    external: false
  # traefik removed
  proxy:
    external: true
```

```Dockerfile
# Dockerfile.prod

FROM node:21.6.2-alpine AS base

FROM base AS dependencies
RUN apk update \
  && apk add --no-cache libc6-compat

WORKDIR /app

COPY package*.json .
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate \
  && rm -rf prisma


FROM base AS builder
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ARG ARG_DATABASE_URL
ENV DATABASE_URL=$ARG_DATABASE_URL

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

# fails
RUN npm run build \
  && rm -rf node_modules


FROM base AS runner
# ...
```

then run with
```sh
docker compose -f docker-compose.stage.yml compose up -d db-stage
dotenv -e .env.staging -- docker compose -f docker-compose.stage.yml compose build app-stage
```
