### DISCUSSION TITLE
please help i new here with vercel

### DISCUSSION THREAD

**Discussion by frywl** [vercel/next.js#66454] [Help]
### please

Previously I had a CORS problem, which involved from my Spring Boot backend and the frontend with Next.js, was that localhost:3000 (frontend) wanted to receive information from localhost:8080 (backend), but this way it worked:

``` 
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/cliente/**
        - id: configuracion-service
          uri: lb://configuracion-service
          predicates:
            - Path=/configuracion/**
        - id: agendamiento-service-colaborador
          uri: lb://agendamiento-service
          predicates:
            - Path=/colaborador/**
        - id: agendamiento-service-cita
          uri: lb://agendamiento-service
          predicates:
            - Path=/cita/**
        - id: agendamiento-service-horario
          uri: lb://agendamiento-service
          predicates:
            - Path=/horario/**
        - id: agendamiento-service-motivocancelacion
          uri: lb://agendamiento-service
          predicates:
            - Path=/motivocancelacion/**
        - id: moduloCompra-service
          uri: lb://moduloCompra-service
          predicates:
            - Path=/compras/**
        - id: servicio-service
          uri: lb://servicio-service
          predicates:
            - Path=/servicio/**
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
        - id: venta-service
          uri: lb://venta-service
          predicates:
            - Path=/venta/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*" 
```

Now that I deployed my frontend to a vercel.app url, I tried changing where the localhost:3000 was to:

``` allowedOrigins: "https://alexasoft-proyecto.vercel.app" ```

And it doesn't work, I get the CORS error. Help please, I appreciate you help :)

### Additional information

```js
clientes:1  Access to fetch at 'http://localhost:8080/cliente' from origin 'https://alexasoft-proyecto.vercel.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### Example

https://alexasoft-proyecto.vercel.app/admin/clientes
