### DISCUSSION TITLE
Vercel Aliasing PR Deploys Automatically

### DISCUSSION THREAD

**Discussion by JamesWalkerGit** [vercel/next.js#67163] [Help]
### Summary

Hello, I'm working on setting up Vercel so that I can trigger a deploy whenever a Pull Request to main is opened/updated, and I want that Vercel deploy to be aliased to staging.mysite.com automatically. 

It's annoying because all I need to do in reality is have an option where any Preview deploy from any branch automatically gets assigned to staging.mysite.com as a final step in the automatic Vercel-Github integration. (Or better yet a PR to main only deploy option instead of every push/every branch) 

Instead I had to do it manually via Github Actions, however in order to do so I needed to manually create another Vercel deploy to get its url, then use that url as the alias argument to assign it to staging.mysite.com. 

I only did that because I was unable to find any way to setup in Vercel a situation where:
1. PR branch to main in repository 
2. Vercel build/deploy occurs for that PR
3. Alias staging.mysite.com to that PR-triggered deploy after it completes 

My question is am I missing something and there is a way to do this via Vercel built in? 

Is there an easier way to get the url of the current Vercel deploy of a given branch or even just most recent Vercel Preview deploy to alias to my staging.mysite.com url? 

Or 

Do I need to manually create this setup for my PR's and main merges via Github Actions, and disable the automatic Vercel-Github integration so that I don't constantly have 2 builds going off. 
Unfortunately I think I would also lose the Vercel Preview comments integration if I were to do this. 

Anyway just curious if anyone had any suggestions, here's my Github Actions setup for PR's that I'll most likely duplicate for main merges for prod deploys. 

Thanks!

```
name: Github Actions - Vercel Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: url="$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }})"
      - name: Deploy Project to Staging
        run: |
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} $url staging.mysite.com --scope=myProjectScope
```
