### DISCUSSION TITLE
A small bug

### DISCUSSION THREAD

**Discussion by diqye** [vercel/next.js#68781] [App Router]
source page.css
```css
@property --p{
    /* https://developer.mozilla.org/zh-CN/docs/Web/CSS/percentage */
    syntax: '<percentage>';
    initial-value: 0%;
    inherits: false;
}
```

After `next build`

```
@property --p{
    /* https://developer.mozilla.org/zh-CN/docs/Web/CSS/percentage */
    syntax: '<percentage>';
    initial-value: 0;
    inherits: false;
}
```

The problem is that `0` isn't a valid value for `<percentage>`, so `@property` will be ignored
