### DISCUSSION TITLE
Verce build path errros

### DISCUSSION THREAD

**Discussion by thunder-007** [vercel/next.js#68953] [App Router]
### Summary

I'm trying to build a vercel ci/cd pipeline and it says path 
```
name: GitHub Actions Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        env:
          NEXT_PUBLIC_GITHUB_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GITHUB_CLIENT_ID }}
          NEXT_PUBLIC_BACKEND_API_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_API_URL }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
```
> Export encountered errors on following paths:
	/(auth)/(routes)/github/page: /github
	/(auth)/(routes)/login/page: /login
	/(auth)/(routes)/logout/page: /logout
	/(dashboard)/(auth)/(routes)/billing/page: /billing
	/(dashboard)/(auth)/(routes)/dashboard/page: /dashboard
	/(dashboard)/(auth)/(routes)/organisations/page: /organisations
	/(dashboard)/(auth)/(routes)/projects/page: /projects
	/(dashboard)/(auth)/(routes)/settings/page: /settings
	/(landing)/page: /
I thought could be cause of the urls fetch(process.env.NEXT_PUBLIC_BACKEND_API_URL + "/api/auth/user/", {
so I mentioned them as env vars in build it's still the same I don't get this error when I building in vercel app without actions
