### DISCUSSION TITLE
ECONNREFUSED when call backend API with docker name from server side /pages/api

### DISCUSSION THREAD

**Discussion by themitichris** [vercel/next.js#70196] [Help]
### Summary

FrontEnd: Next.JS 14
BackEnd: .NET 6
Docker Desktop (Docker Engine v27.2.0)

package.json main packages

```
"@next/env": "^14.2.6",
"react": "^18.3.1",
"next": "^14.1.11",
"next-auth": "^4.24.7",
```

docker-compose file

 ```
services:  
   c-eventi-be:
     container_name: c-eventi-be
     image: c-eventi-be
     build: .
     ports:
       - 7258:443
       - 5258:80
   c-eventi-fe:
     container_name: c-eventi-fe
     image: c-eventi-fe
     build: ./CEvents.ClientApp
     ports:
       - 3000:3000
     environment:
       - BASE_API_URL=http://c-eventi-be:5258/api
       - NODE_TLS_REJECT_UNAUTHORIZED=0
     depends_on:
       - c-eventi-be
```

NextJS .env

NEXT_PUBLIC_BASE_URL="http://127.0.0.1:3000/" //User for client side call to /api
NEXTAUTH_URL="$NEXT_PUBLIC_BASE_URL/api/auth"
BASE_API_URL="http://localhost:5258/api" //Used for server side call to Backend API (Under /pages/api)

Refer to Docs I added a file envConfig.ts that I imported on every file where I wrote the client side API (to /api)

```
import { loadEnvConfig } from "@next/env";

const projectDir = process.cwd();
loadEnvConfig(projectDir);
```

Current vs. Expected behavior
Calling API from Postman (pointing localhost:5258) works fine
Open the app from browser (localhost:3000) returns Error 500 Internal Server Error.
Calling API from Next app (localhost:3000/api/xyz) returns ECONNREFUSED
```

{
  "status": "fetch failed",
  "message": {
    "cause": {
      "errno": -111,
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "172.20.0.2",
      "port": 5258
    }
  }
}
```

Provide environment information
- Docker Desktop (Docker Engine v27.2.0)
- WSL 2 backend

Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 48840
  Available CPU cores: 16
Binaries:
  Node: 18.17.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.11 // Latest available version is detected (14.2.11).
  eslint-config-next: 14.2.7
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 4.6.3
Next.js Config:
  output: standalone
