### DISCUSSION TITLE
css usage: active-view-transition-type compilation error

### DISCUSSION THREAD

**Discussion by FerretAngel** [vercel/next.js#74054] [Help]
### Summary

This code is referenced from：https://developer.chrome.com/docs/web-platform/view-transitions/cross-document?hl=zh-cn#view-transition-types
```css
html:active-view-transition-type(forwards,backwards) {
  &::view-transition-old(app-page),
  &::view-transition-new(app-page) {
    animation-timing-function: cubic-bezier(0, 0, 0.2, 1);
  }
}

html:active-view-transition-type(forwards) {
  &::view-transition-old(app-page) {
    view-transition-name: none;
  }

  &::view-transition-new(app-page) {
    animation-name: fromBottom;
  }
}

html:active-view-transition-type(backwards) {
  &::view-transition-old(app-page) {
    view-transition-name: none;
  }

  &::view-transition-new(app-page) {
    animation-name: fromTop;
  }
} 
```
![image](https://github.com/user-attachments/assets/c57e6306-3f02-48b6-864a-ffef6120cb61)
