### DISCUSSION TITLE
Build Error: HookWebpackError - Cannot read properties of undefined (reading '0')

### DISCUSSION THREAD

**Discussion by coderrshyam** [vercel/next.js#76050] [Help] [answered]
### Summary

I am getting this error:
```
Failed to compile.

HookWebpackError: Cannot read properties of undefined (reading '0')
    at makeWebpackError (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\webpack\bundle5.js:28:314608) 
    at C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\webpack\bundle5.js:28:106402
    at eval (eval at create (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\webpack\bundle5.js:13:9218), <anonymous>:44:1)
-- inner error --
TypeError: Cannot read properties of undefined (reading '0')
    at C:\CoderrShyam\portfolio\static\css\ced646a0a046baac.css:2:109823
    at Parser.attribute (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:84899)
    at Parser.parse (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:99055)
    at Parser.loop (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:98727) 
    at new Parser (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:84494)  
    at Processor._root (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:101743)
    at Processor._runSync (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:102250)
    at Processor.processSync (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:103005)
    at C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:39339
    at Array.every (<anonymous>)
    at ensureCompatibility (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:38727)
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read properties of undefined (reading '0')
899)
    at Parser.parse (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:99055)      
    at Parser.loop (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:98727)       
    at new Parser (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:84494)        
    at Processor._root (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:101743)  
    at Processor._runSync (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:102250)
    at Processor.processSync (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:103005)
    at C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:39339
    at Array.every (<anonymous>)
    at ensureCompatibility (C:\CoderrShyam\portfolio\node_modules\.pnpm\next@15.1.7_react-dom@19.0.0_react@19.0.0__react@19.0.0\node_modules\next\dist\compiled\cssnano-simple\index.js:320:38727)


> Build failed because of webpack errors
```

Beacuse of the following css:

```css
.prose :where(a):not(:where([class~="not-prose"], [class~="not-prose"] *)) {
  @apply text-link hover:text-link-hover no-underline transition-colors;
}

.prose :is(h2, h3, h4) a code {
  font-size: inherit;
  color: inherit;
}

.prose
  :where(h2:not(:is(h1 + h2))):not(
    :where([class~="not-prose"], [class~="not-prose"] *)
  ) {
  @apply border-foreground/20 mt-10 border-t pt-10;
}

.prose code:not(pre code) {
  padding: 0.12em 0.25em;
  @apply border border-solid border-[#ededed] bg-[#f7f7f7] leading-[1.2] dark:border-[#3e3c3c] dark:bg-[#2a2828];
}

.prose ul ::marker {
  content: "-";
  @apply text-accent-4;
}

.prose ol ::marker {
  counter-increment: list;
  content: counter(list) ". ";
  font-feature-settings: "tnum";
  font-variant: tabular-nums;
}

.prose ol {
  list-style-type: none;
  counter-reset: list;
  padding: 0;
  padding-left: 18px;
}

.prose ol li {
  counter-increment: list;
  padding-left: 8px;
}

.prose pre > code {
  @apply text-accent-7! m-0! grid max-w-[inherit]! bg-white dark:bg-neutral-950;
}

blockquote > p::before {
  display: none;
}

.prose pre [data-line] {
  padding: 0 1rem;
}

.prose code[data-theme*=" "]:not(pre code),
.prose code[data-theme*=" "]:not(pre code) span {
  @apply text-(--shiki-light) dark:text-(--shiki-dark);
}

.prose pre code[data-theme*=" "],
.prose pre code[data-theme*=" "] span {
  @apply bg-(--shiki-light-bg) text-(--shiki-light) dark:bg-(--shiki-dark-bg) dark:text-(--shiki-dark);
}

.prose pre code span[data-highlighted-line] {
  @apply border-primary/70 bg-primary/20! border-l-2;
}

.prose pre code[data-line-numbers] {
  counter-reset: line;
}

.prose pre code[data-line-numbers] > [data-line]::before {
  counter-increment: line;
  content: counter(line);
  display: inline-block;
  width: 0.75rem;
  margin-right: 18px;
  text-align: right;
  color: #6e6e6e;
  font-size: 13px;
}

.prose pre code[data-line-numbers-max-digits="2"] > [data-line]::before {
  width: 1.25rem;
}

.prose pre code[data-line-numbers-max-digits="3"] > [data-line]::before {
  width: 1.75rem;
}

.prose pre code[data-line-numbers-max-digits="4"] > [data-line]::before {
  width: 2.25rem;
}

.prose pre code [data-highlighted-chars] {
  border-radius: 0.2rem;
  background-color: #52525b80;
  box-shadow: 0 0 0 4px #52525b80;
}
```

I review very carefully to my css but i am not find any error. If i remove this css the build error not occured.

### Additional information

```js
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home Single Language
  Available memory (MB): 16069
  Available CPU cores: 12
Binaries:
  Node: 22.14.0
  npm: 10.9.2
  Yarn: N/A
  pnpm: 10.3.0
Relevant Packages:
  next: 15.1.7
  eslint-config-next: 15.1.7
  react: 19.0.0
  react-dom: 19.0.0
  tailwindcss: 4.0.6
  typescript: 5.7.3
Next.js Config:
  output: N/A
```

### Example

https://github.com/coderrshyam/next.js-hook-webpack-error

**Comment by icyJoseph** [comment, marked as answer]
So the issue are these lines:

```css
.prose code[data-theme*=" "]:not(pre code),
.prose code[data-theme*=" "]:not(pre code) span {
  @apply text-(--shiki-light) dark:text-(--shiki-dark);
}

.prose pre code[data-theme*=" "],
.prose pre code[data-theme*=" "] span {
  @apply bg-(--shiki-light-bg) text-(--shiki-light) dark:bg-(--shiki-dark-bg) dark:text-(--shiki-dark);
}
```

More specifically this bit `prose code[data-theme*=" "]` ~ removing these works, let me think about about what alternative syntax could you use.

**Reply by icyJoseph** [reply]
So, like in Tailwind 3 this works:

```css
.prose code[data-theme*=" "] {
  color:red
}
```

It is parsed correctly, as:

```node
Parser {
  rule: '.prose code[data-theme*=" "]',
  options: { lossy: false, safe: false },
  position: 8,
  css: '.prose code[data-theme*=" "]',
 /* more stuff */
}
```


but when I upgrade to Tailwind 4, then the selector is changed to:

```node
Parser {
  rule: '.prose code[data-theme*=\\]',
  options: { lossy: false, safe: false },
  position: 8,
  css: '.prose code[data-theme*=\\]',
```

And that causes the issue 🤷 ~ maybe go for an empty string for now, if possible, within your codebase, or some other indicator other than whitespace. One should probably report this to Tailwind.

The parser at play here is `cssnano`.
