### DISCUSSION TITLE
Problem with next/font/google CSS Variables in Tailwind CSS with Next.js v5 + Tailwind v4

### DISCUSSION THREAD

**Discussion by Jafar-Sabaouni** [vercel/next.js#77337] [Help]
### Summary

I'm currently using **Next.js v5** with **Tailwind CSS v4** in my project and ran into an issue when trying to integrate fonts from `next/font/google` with my Tailwind configuration.

In previous versions of Tailwind, I could assign CSS variables to fonts within the Tailwind theme, and everything worked as expected. However, with the new **CSS-based configuration in Tailwind v4**, that method no longer seems to function correctly.

### My First Attempt (Unsuccessful)

I initially followed the same approach that worked in earlier versions:

**`layout.tsx`**
```tsx
import { Inter, Syne } from "next/font/google";

const inter = Inter({
  variable: "--next-font-inter",
  subsets: ["latin"],
});

const syne = Syne({
  variable: "--next-font-syne",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${syne.variable} bg-rich-black text-white`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
```

**`tailwind.config.css`**
```css
@theme {
  /* Fonts */
  --font-inter: var(--next-font-inter);
  --font-syne: var(--next-font-syne);
}
```

Unfortunately, this setup didn’t work as expected.

### What Worked for Me

After some experimentation, I found the simplest solution was to directly assign the font names as strings instead of referencing the CSS variables:

```css
@theme {
  /* Fonts */
  --font-inter: "inter";
  --font-syne: "syne";
}
```

This resolved the issue for me. If anyone has a better or more consistent method of integrating `next/font/google` with Tailwind v4’s new config system, I’d love to hear about it!

---

**Comment by dnlsandiego** [comment]
Referencing variables needs to be inside a `@theme inline` like:
```css
@theme inline {
  --font-sans: var(--font-inter);
}
```
