### ISSUE TITLE
cssnano incorrectly minifies opacity

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#14690]
Input:
```css
.g-docs-sidenav .filter::-webkit-input-placeholder {
  opacity: 80%;
}
```

Output:
```css
.g-docs-sidenav .filter::-webkit-input-placeholder{opacity:1%}
```
