### ISSUE TITLE
Strict CSS Module imports

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#14704]
It should be possible to import class names from CSS modules via ESM harmony imports, and webpack should throw a class not found error if it exists.

Desired:

```css
/* index.module.css */
.example {
  color: blue;
}
```

```tsx
// index.tsx
import { example } from './index.module.css'; // OK
import { other } from './index.module.css'; // Compile Error
```

This should be accomplishable via the new `esModule` setting in `css-loader`.
