### ISSUE TITLE
[Bug:Styled-Component] change child style from parent  

### ISSUE THREAD

**Issue by beqramo** [vercel/next.js#15203]
my jsx looks like:
```jsx
      <SectionTiTle >
        <span style={{ color: '#66C3AD' }}>dummy</span>
      </SectionTiTle>
```
and my style: 

```jsx
     
export const SectionTiTle = styled.h1`
  color: #343d47;
  soan: { 
    font-family: NotoSansGeorgian-Bold;
  }
`;

```

I have already tried accessing by span id  ``#span``and ``& > span`` but don't work, I can't style child element from parent

**Comment by mattcarlotta** [comment]
This is unrelated to next. You have a several syntax errors...

## Issue 1
You have  invalid CSS syntax: `soan: { ... }` or `span: { ... }`. Instead you can select `<span>` with just `span { ... }` (selector `#span` refers to an `id`, which doesn't exist as an attribute to your `<span>` and while `& > span` is a valid selector, the reason it didn't work is related to issue 2 mentioned below).

An even better approach would be to assign a `className` to the `<span>` element and target the className. 

For example:
 ```jsx
<span className="example">dummy</span>
```
and then selecting the class name using:
```css
& .example { 
   font-family: "Noto Sans Georgian Bold; sans-serif
}
```
This is better for **flexibility/reusability** and **specificity**.

Anyway, here's the corrected syntax:
```jsx
import styled from "styled-components";

const SectionTiTle = styled.h1`
  color: #343d47;

  span { 
    font-family: "Noto Sans Georgian Bold", sans-serif";
  }
`;

export default SectionTtile
```
## Issue 2 
Your `font-family` names have to match.

You'll need to import the font and specify the `font-family` naming **and** specify the correct `url` -- this can either be a CDN url: `https://example.com` or if it's in your project's `public` folder, then using Next's [static-file serving](https://nextjs.org/docs/basic-features/static-file-serving), you can import with `/`:

```css
@font-face {
  font-family: "Noto Sans Georgian Bold";
  font-style: normal;
  font-weight: bold;
  src: url("/NotoSansGeorgian-Bold.ttf") format("truetype");
}
```

## Working repo 
[![Edit ancient-shape-tdog0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ancient-shape-tdog0?fontsize=14&hidenavigation=1&theme=dark)
A prop mismatch warning may be thrown; however, this a codesandbox only issue and won't be there when ran locally.
