### ISSUE TITLE
Pages render without styles for a brief second

### ISSUE THREAD

**Issue by Lillebo** [vercel/next.js#15642]
# Bug report

## Describe the bug

Pages render without any styles for a brief second before the CSS is loaded:

![Jul-29-2020 20-54-52](https://user-images.githubusercontent.com/74510/88841314-13010400-d1de-11ea-85fa-91c78cb771fb.gif)

This only happens in production. In development everything is fine and pages render perfectly styled immediately.

## To Reproduce

I try to load some global styles in `_app.tsx` like:

```tsx
// _app.tsx
import '../assets/styles/global.scss';

const MyApp = () => { ... }

export default MyApp;
```

```SCSS
// global.scss
@mixin system-font() {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
    "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

body {
  @include system-font();
  background: white;
  color: $text-color;
  line-height:1.5;
}
```

Then all my pages and components follow this pattern:

```tsx
// my-page.tsx
import './my-page.scss'

const MyPage = () => { ... }

export default MyPage;
```

```tsx
// my-component.tsx
import './my-component.scss'

const MyComponent = () => { ... }

export default MyComponent;
```

## Expected behavior

I expect pages to render with styles without such flickering.

## System information

- OS: macOS Catalina 10.15.5
- Browser: Firefox 78.0.2
- Version of Next.js: 9.4.4
- Version of Node.js: 12.18.1
