### ISSUE TITLE
Built-in sass does not recognize native html tags

### ISSUE THREAD

**Issue by billcastillo** [vercel/next.js#15992]
# Bug report

Inside `hello-world.module.scss`, trying to style a native html tag such as `article`, `nav`, `main`, etc. will throw an error.
sass modules doesn't recognize these properties

```css
article {
  font-size: 18px;
}
```

```
error - ./components/hello-world.module.scss:7:1
Syntax error: Selector "article" is not pure (pure selectors must contain at least one local class or id)
```

## To Reproduce

1. Fork [next-sass](https://github.com/vercel/next-plugins/tree/master/packages/next-sass) from next-plugin examples
2. Add a native html tag like `article`, etc.
3. Add styles to `hello-world.module.scss` for that `article`
```css
article {
  font-size: 24px;
  color: blue;
}
```
5. Add className like `<article className="post">`
6. Style using that class name
```css
.post {
  font-size: 32px;
  color: yellow;
}
```
7. No style rendered

## Additional context

Work around is to use [next-sass plugin](https://github.com/vercel/next-plugins/tree/master/packages/next-sass)
