### ISSUE TITLE
[with-ant-design-less] Media definitions require block statements after any features

### ISSUE THREAD

**Issue by ManAnRuck** [vercel/next.js#16037]
# Bug report

## Describe the bug

App does not work when using media queries

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. npx create-next-app --example with-ant-design-less
2. Add media query to antd-custom.less
```less
@primary-color: #52c41a;

@layout-header-height: 40px;
@border-radius-base: 2px;

// Add this
@media (min-width: @screen-md-min) {
  @primary-color: #1ab6c4;
}
```
3. start app

## Expected behavior

Render without error

## Screenshots

<img width="983" alt="Bildschirmfoto 2020-08-10 um 12 27 47" src="https://user-images.githubusercontent.com/2183135/89773814-ee255e80-db04-11ea-8311-df2f34a32f51.png">

## System information

- OS: macOS
- Browser (if applies) [chrome & safari]
- Version of Next.js: [latest (9.5.1)]
- Version of Node.js: [12.x & 14.x]

## Additional context

```
error - ./node_modules/antd/lib/button/style/index.less

@primary-color: #52c41a;@layout-header-height: 40px;@border-radius-base: 2px;@media (min-width: @screen-md-min) {
  @primary-color:#1ab6c4;
                       ^
Media definitions require block statements after any features
      in …/with-ant-design-less/node_modules/antd/lib/button/style/index.less (line 227, column 25)
    at runMicrotasks (<anonymous>)
```
