### ISSUE TITLE
@keyframes transpiled wrongly

### ISSUE THREAD

**Issue by Joozty** [vercel/next.js#16648]
# Bug report

## Describe the bug
When I use the default sass configuration the animation is transpiled incorrectly:

```css
@keyframes slide-in-up {
  from {
    transform: translateY(200%);
  }

  to {
    transform: translateY(0);
  }
}

.container {
  animation: 3s slide-in-up;
  width: 100px;
  height: 100px;
  background: black;
}
```

Gets transpiled to:
```css
@-webkit-keyframes index_slide-in-up__3zvVY {
  from {
    -webkit-transform: translateY(200%);
            transform: translateY(200%);
  }

  to {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
}

@keyframes index_slide-in-up__3zvVY {
  from {
    -webkit-transform: translateY(200%);
            transform: translateY(200%);
  }

  to {
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
}

.index_container__3XRMM {
  -webkit-animation: 3s :local(slide-in-up); /* <-- this is wrong */
          animation: 3s :local(slide-in-up); /* <-- this is wrong */
  width: 100px;
  height: 100px;
  background: black;
}
```

## To Reproduce

1. Clone [this repo](https://github.com/Joozty/zeit-keyframes)
2. Run `npm run dev` - open dev console and see styles applied on container class
3. Run `npm run build` - it fails because there is missing semicolon

## Screenshots

![keyframes](https://user-images.githubusercontent.com/12775440/91557543-f1a64b80-e934-11ea-82bd-723fa519f4ec.PNG)
