### ISSUE TITLE
Next.js cache growing infinitely

### ISSUE THREAD

**Issue by NMinhNguyen** [vercel/next.js#17873]
# Bug report

## Describe the bug

On CI providers such as [Heroku](https://github.com/vercel/next.js/blob/canary/errors/no-cache.md#heroku) where you don't get to specify cache keys (presumably, the CI provider will restore the most recently available cache), Next.js cache can [keep growing](https://stackoverflow.com/questions/58815078/why-is-heroku-build-cache-getting-bigger-with-every-release). See https://github.com/mui-org/material-ui/pull/22948 where I first spotted this issue and the Next.js cache grew to 3GB over ~7 months. In Material-UI's case, they were using Azure Pipelines with a cache key derived from `yarn.lock`'s checksum (as documented in https://github.com/vercel/next.js/blob/canary/errors/no-cache.md) together with [restore keys](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#restore-keys) to pull in the most recent cache in case there isn't an exact match on the lockfile.

A related question I have is whether `yarn.lock` is a good cache key at all? What caching strategy does Vercel use? Is it also based on a lockfile checksum? Or does it simply download the latest available cache?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

If using Azure Pipelines, use the below cache configuration and watch how the cache grows as you update `yarn.lock`:

```yml
variables:
  # `docs` is where the Next.js app lives: https://github.com/mui-org/material-ui/tree/next/docs 
  DOCS_NEXT_CACHE_FOLDER: $(Build.SourcesDirectory)/docs/.next/cache

# ...

  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(DOCS_NEXT_CACHE_FOLDER)
    displayName: Cache nextjs build
```

## Expected behavior

I'm not sure if this is optimal, but perhaps Next.js could purge old cache entries using some heuristic?

## System information

- OS: Ubuntu 18.04
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: 9.5.5
- Version of Node.js: 10
