### ISSUE TITLE
Overlay font size with global styles

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#18680]
![image](https://user-images.githubusercontent.com/616428/97880952-c7378c80-1cef-11eb-84dd-5c690983b7fe.png)

>The font size is affected by the user’s style sheet (I had a global style for pre)
 

```css
html, body { font-size: 20px }
```
