### ISSUE TITLE
CircleCI: ../web/components/Layout.tsx:4:18 - error TS2307: Cannot find module 'next/Link' or its corresponding type declarations.

### ISSUE THREAD

**Issue by garrett-gottlieb** [vercel/next.js#19039]
# Bug report

## Describe the bug

When running `tsc` on CircleCI, I see:
```
../web/components/Layout.tsx:4:18 - error TS2307: Cannot find module 'next/Link' or its corresponding type declarations.

4 import Link from 'next/Link'
                   ~~~~~~~~~~~
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a yarn workspaces project with a subfolder `web` and create a blank NextJS app
2. Import the following in a page: `import Link from 'next/Link'`
3. Run `tsc` on CircleCI
```yml
version: 2
workflows:
  version: 2
  master:
    jobs:
      - web

jobs:
  web:
    docker:
      - image: circleci/node:12.18.3
      - image: circleci/postgres:11.5-alpine

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            cd server
            yarn install -D

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run Tests
          command: |
            cd web
            yarn tsc
```

NOTE: This works in the local environment.

## Expected behavior

Typescript passes

## System information

- OS: [e.g. macOS, Windows] macOS
- Browser (if applies) [e.g. chrome, safari]
- Version of Next.js: [e.g. 6.0.2] 10.0.0
- Version of Node.js: [e.g. 10.10.0] v12.18.3

## Additional context

/web/tsconfig.json:
```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "types": ["@emotion/core"]
  },
  "include": ["web/next-env.d.ts", "**/*.ts", "**/*.tsx"]
}
```

/tsconfig.json:
```json
{
  "compilerOptions": {
    "allowJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": false,
    "target": "esnext",
    "rootDir": ".",
    "baseUrl": "."
  },
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "**/node_modules"]
}
```
