### ISSUE TITLE
Using SASS with CSS Modules and `:global` and `&` is impossible -- catch 22

### ISSUE THREAD

**Issue by salazarm** [vercel/next.js#20034]
# Bug report

When using CSS modules combined with SCSS, `&` and `:global` usage we end up in a catch 22.

## Describe the bug

I'm running into this issue here: https://github.com/webpack-contrib/sass-loader/issues/507
Specifically this causes an error in SASS:

```
.className :global {
  &.someClass {
     color: 'red',
  }
}
```

The workaround is to do this:
```
:global :local(.className) {
  &.someClass {
     color: 'red',
  }
}
```

However then Next.js can't recognize that the selector is still a "Pure" selector.

So this feels like a catch 22? Is there a way to disable the pure selector rule on a particular line?

## Expected behavior
I Expect the second case to be identified as a pure selector? Or maybe SASS should make an exception for :`global` ?

## Additional context

Next version 10.0.3 using the built in CSS support.
https://gist.github.com/salazarm/58c473c4efae1b1aab799c7064bee67f

**Comment by LoicHa** [comment]
I tried with 

```
.itemsList :global {

  $this: &;
  &.busy {
    background:red;
  }

}
```

But the result is the same

**Comment by jasonmelgoza** [comment]
I tried:

```scss
:local(.root) {
  color: green;
  :global &.ui {
    color: blue;
  }
}
```

and

```scss
:global {
  :local(.root) {
    &.ui {
      color: green;
    }
  }
}
```

Both produce the same error.
