### ISSUE TITLE
FOUC where text appears all uppercase

### ISSUE THREAD

**Issue by nicholaschiang** [vercel/next.js#22001]
**What version of Next.js are you using?**

10.0.6

**What version of Node.js are you using?**

12.18.3

**What browser are you using?**

Firefox

**What operating system are you using?**

PopOS 20.04 (Ubuntu 20.04)

**How are you deploying your application?**

Vercel

**Describe the Bug**

I'm currently using Google Fonts to import the Inter font face for [my Tutorbook project](https://github.com/tutorbookapp/tutorbook) in a [`styles/global.scss`](https://github.com/tutorbookapp/tutorbook/blob/0.22.0/styles/global.scss#L27) file that is imported into [`pages/_app.tsx`](https://github.com/tutorbookapp/tutorbook/blob/0.22.0/pages/_app.tsx#L15):

```scss
// styles/global.scss
@import url('https://fonts.googleapis.com/css?family=Inter:100,200,300,400,500,600,700,800,900');
@import url('https://fonts.googleapis.com/icon?family=Material+Icons');

:root {
  --font-sans: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto',
    'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
}

html,
body {
  font-family: var(--font-sans);
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

The font face seems to load correctly (eventually), but at first, I see a FOUC in the production deployment that uses the system default font (not Inter) and is in all uppercase:

![fouc-uppercase](https://user-images.githubusercontent.com/20798889/107426101-a80d7f80-6ad4-11eb-9f3e-bdf2ace889b6.gif)

**Expected Behavior**

There should be no FOUC. The text should appear in the specified Inter font face with normal capitalization (not all uppercase).

**To Reproduce**

1. Go to [https://tutorbook.app](https://tutorbook.app).
2. See FOUC.

To reproduce locally:
1. Clone [`tutorbookapp/tutorbook`](https://github.com/tutorbookapp/tutorbook).
2. Install dependencies using `yarn`.
3. Start the development server using `yarn dev`.
4. Go to [http://localhost:3000](http://localhost:3000).
5. See FOUC.
