### ISSUE TITLE
Minified production CSS differs from authored CSS

### ISSUE THREAD

**Issue by hatsumatsu** [vercel/next.js#22389]
**What version of Next.js are you using?**

10.0.7

**What version of Node.js are you using?**

15.9.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**How are you deploying your application?**

next start

**Describe the Bug**

When combining long and short formats of the same property AND custom properties in CSS, webpack's CSS minifier seems to combine rules in a wrong way. This results in the production CSS to differ from the authored CSS.

**Expected Behavior**

The production CSS produces the same visual result as the authored CSS.

**To Reproduce**

***A***

A.1 Clone repo: https://github.com/hatsumatsu/next-postcss-production-bug

A.2 Run `npm run dev`. Visual result: Both borders are 1px thick.

A.3 Run `npm run build` and `npm run start`. Visual result: The inner border is thicker than the outer one.

***B***

B.1 Create a new next project via `npx create-next-app`.

B.2 Add the following **valid** CSS:

````css
:root {
	--border--width--thick: 10px;
	--border--width--thin: 1px;
}

html,
body {
	padding: 0;
	margin: 0;
	background: #eee;
}

.a {
	width: 200px;
	height: 200px;
	margin: 100px;
	background: white;
/**
 * works without custom properties:
 * border-top: 10px solid blue;    
 */
    border-top: var(--border--width--thick) solid blue;    
    border-width: 1px;    
}

.a > .b {
	width: 80%;
	height: 80%;
	margin: 10%;

	/**
          * works without custom properties:
	 * border-left: 10px solid blue;    
	 */
    border-left: var(--border--width--thick) solid blue;
    border-width: 1px;
}	
````

B3. Compare the visual result of the development and production build. 

The production CSS is 

````css
:root {
	--border--width--thick: 10px;
	--border--width--thin: 1px
}

body,html {
	padding: 0;
	margin: 0;
	background: #eee
}

.a {
	width: 200px;
	height: 200px;
	margin: 100px;
	background: #fff;

	border-top: solid #00f /* defaults to `medium`*/
}

.a, .a > .b {
	border-width: 1px
}

.a > .b {
	width: 80%;
	height: 80%;
	margin: 10%;
	border-left: solid #00f /* defaults to `medium`*/
}
````
