### ISSUE TITLE
Docker: Locale undefined with i18n enabled + 404 on pages

### ISSUE THREAD

**Issue by ref-thomasledoux1** [vercel/next.js#22668]
### What version of Next.js are you using?

10.0.8-canary.11

### What version of Node.js are you using?

14.15.5

### What browser are you using?

Chrome

### What operating system are you using?

Docker

### How are you deploying your application?

Docker run

### Describe the Bug

We are running our Next.js application in a Docker container.
After enabling i18n through the next.config.js, I noticed that the URL's which should be generated by Next.js for the files in /pages are not correctly being served.
The homepage gets served correctly, but when I for example surf to /contentPage (which is in the /pages folder), I get a 404.
I have the defaultLanguage set to 'nl', and when I surf to /nl/contentPage, the page is served correctly.

While debugging this problem, I noticed that the 'locale' prop in getStaticProps on my /pages/index file is undefined.
The same happens when try the following: 
const router = useRouter()
console.log(router.locale)

=> this returns undefined too.

This all works fine while using 'npm run dev' and even when I use 'npm run build' & 'npm start' locally.

### Expected Behavior

I would expect the i18n features to work in Docker containers too.

### To Reproduce

My next.config.js file:
```javascript
module.exports = {
  i18n: {
    localeDetection: false,
    defaultLocale: 'nl',
    locales: ['nl', 'en'],
  },
  webpackDevMiddleware: config => {
    config.watchOptions = {
      poll: 1000,
      aggregateTimeout: 300,
    }

    return config
  },
}
```

My docker-compose.yml file:
```yml
version: '3.8'
services:
  solution:
    image: ${REGISTRY}${PROJECT_NAME}-solution:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./docker/build/solution/Dockerfile
      args:
        BASE_IMAGE: node:${NODE_VERSION}
        BUILD_IMAGE: node:${NODE_VERSION}
    scale: 0

  webapp:
    image: ${REGISTRY}${PROJECT_NAME}:${VERSION:-latest}
    build:
      context: ./docker/build/webapp
      args:
        BASE_IMAGE: node:${NODE_VERSION}
        SOLUTION_IMAGE: ${REGISTRY}${PROJECT_NAME}-solution:${VERSION:-latest}
    depends_on:
      - solution
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app #map app with sources for local dev
      - /app/node_modules
      - /app/.next
    entrypoint: npm run dev #overrides entrypoint for local dev
```

My docker/build/solution/Dockerfile:
```
ARG BASE_IMAGE
ARG BUILD_IMAGE

FROM ${BUILD_IMAGE} as build

WORKDIR /app

COPY src/package.json src/package-lock.json ./

# install dependencies
RUN npm ci 

COPY src .

# build
RUN npm run build

FROM ${BASE_IMAGE}

WORKDIR /artifacts/webapp

# copy from build image
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
```

My docker/build/webapp/Dockerfile
```
ARG BASE_IMAGE
ARG SOLUTION_IMAGE

FROM ${SOLUTION_IMAGE} as solution
FROM ${BASE_IMAGE}

WORKDIR /app

# copy from build image
COPY --from=solution /artifacts/webapp .

EXPOSE 3000

USER node

ENTRYPOINT [ "npm", "start" ]
```

Commands I use locally:
docker compose build
docker run -p 3000:3000 $projectName:latest

(I replaced the project name with $projectName in the snippet above).
