### ISSUE TITLE
Environment Variables undefined with Docker & getInitialProps

### ISSUE THREAD

**Issue by dopt** [vercel/next.js#23695]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

12.18.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

I am trying to build NextJS with docker, along with `assetPrefix` in `next.config.js`. Whenever I enabled the `getInitalProps` option, the `assetPrefix` option with .env will be ignored in the docker build, and when I comment the `getInitialProps`, the build seems ok with `assetPrefix` with `.env`. Another problem is that, the .env is undefined in `getInitialProps`, unless I put NEXT_PUBLIC as prefix in env name.

### Expected Behavior

When using docker, `assetPrefix` should always taken from .env, regardless of `_app.js` having `getInitialProps` or not. 
.env variables should be accessible inside `getInitialProps` when context is server without `NEXT_PUBLIC`.

### To Reproduce

https://github.com/dopt/with-docker
Install the repo, execute `npm run up-docker`, notice that assetPrefix defined by .env is not working, environment variables MY_CDN is undefined.
After commenting **MyApp.getInitialProps**, assetPrefix with .env MY_CDN is working.

**Comment by wwwdepot** [comment]
You didn't specify the dotenv file. You can do `docker-compose --env-file ./.env up`

or add the `env-file` to the service in the docker-compose file:

```yml
version: "3.9"
services:
  next-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: nextjs-ui
    env_file:
      - .env
    ports:
      - "3000:3000"
```
