### ISSUE TITLE
Class names are not added to DOM when classname is hyphenated

### ISSUE THREAD

**Issue by PsyGik** [vercel/next.js#25230]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

v12.16.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

Other Platform

### Describe the Bug

This is a weird one and I am not able to pinpoint the exact root cause, but definitely looks like a bug. 

Given the following component:
```jsx
// app-bar.js
import React from "react";
import styles from "./app-bar.module.scss";

const AppBar = ({ brand }) => {
  console.log(styles);
  return (
    <div className={styles.appBar}>
      <span className={styles.text}>App Bar</span>
    </div>
  );
};

export default AppBar;

```

and a corresponding scss module
```scss
// app-bar.scss
.app-bar {
  padding: 20px;
  display: flex;
  flex-direction: row;
  background-color: #757575;

  .text{
    font-size: 20px;
    color: red;
  }
}
```

The styles for `div` i.e `styles.appBar` class name does not get added to the DOM. 
![image](https://user-images.githubusercontent.com/5432911/118679506-90543e80-b81b-11eb-9d7f-55ad70c594b3.png)

If I change the scss to this,  and use `className={styles.container}` it works.
```scss
.container {
  padding: 20px;
  display: flex;
  flex-direction: row;
  background-color: #757575;

  .text{
    font-size: 20px;
    color: red;
  }
}

```
And the DOM looks like:
![image](https://user-images.githubusercontent.com/5432911/118679746-c4c7fa80-b81b-11eb-83c5-a7765c642359.png)

It's something to do with hyphenated class names

### Expected Behavior

correct classname must be applied to the DOM

### To Reproduce

https://github.com/PsyGik/nextjs-issue-repo

- Clone Repo
- Run `npm install`
- Run `npm run dev`
- Navigate to `localhost:3000/sub-folder` (I was testing an issue related to the [basePath](https://github.com/vercel/next.js/issues/21131), hence the `sub-folder`) 
- Update scss for app bar as mentioned above
- Fast refresh, and the styles get reflected.
