### ISSUE TITLE
Custom Fonts 404 on server, 200 on localhost.

### ISSUE THREAD

**Issue by rapritchard** [vercel/next.js#26688]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

14.16

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows

### How are you deploying your application?

Deploying to Azure

### Describe the Bug

I am using some custom fonts that I have placed in `public/fonts`.

This all works fine on localhost, but as soon as it goes up to my server (not vercel, hosted on azure) the font files 404, despite other files such as JavaScript and favicons being found fine in the public folder.

_document.tsx
```javascript
import Document, { Html, Head, Main, NextScript, DocumentContext } from 'next/document';

class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const initialProps = await Document.getInitialProps(ctx);

    return initialProps;
  }

  render() {
    return (
      <Html>
        <Head>
          <link
            rel="preload"
            href="/fonts/sofiapro-regular-webfont.woff2"
            as="font"
            crossOrigin=""
            type="font/woff2"
          />
          <link
            rel="preload"
            href="/fonts/sofiapro-regular-webfont.woff"
            as="font"
            crossOrigin=""
            type="font/woff"
          />
          <link
            rel="preload"
            href="/fonts/sofiapro-bold-webfont.woff2"
            as="font"
            crossOrigin=""
            type="font/woff2"
          />
          <link
            rel="preload"
            href="/fonts/sofiapro-bold-webfont.woff"
            as="font"
            crossOrigin=""
            type="font/woff"
          />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;

```
global.css
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@font-face {
  font-family: 'SofiaPro';
  font-weight: 400;
  src: url('/fonts/sofiapro-regular-webfont.woff2') format('woff2'),
    url('/fonts/sofiapro-regular-webfont.woff') format('woff');
  font-display: swap;
}
@font-face {
  font-family: 'SofiaPro';
  font-weight: 700;
  src: url('/fonts/sofiapro-bold-webfont.woff2') format('woff2'),
    url('/fonts/sofiapro-bold-webfont.woff') format('woff');
  font-display: swap;
}


input:focus-within ~ label,
input:not(:placeholder-shown) ~ label {
  @apply transform scale-75 -translate-y-6;
}
```

![image](https://user-images.githubusercontent.com/32645551/123652159-f58c4e00-d823-11eb-832e-06c0efbf3426.png)

### Expected Behavior

Custom font files should be found and 200.

### To Reproduce

Include a custom font locally on a TypeScript project and push up to a server (not vercel, hosted on azure).
