### ISSUE TITLE
Suggested GitHub Actions caching gets stale

### ISSUE THREAD

**Issue by roim** [vercel/next.js#27129]
### What version of Next.js are you using?

latest

### What version of Node.js are you using?

16.0.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying your application?

next start in a Docker container

### Describe the Bug

When using GitHub actions, `/.next/cache` is generated once, and then remains stale until you update your npm packages. If you don't update your packages, your cache will never be updated, even as your app grows, new pages are added, etc.

### Expected Behavior

The CI cache should be updated whenever `/.next/cache` is updated.

### To Reproduce

The docs for `no-cache` give the following snippet on how to configure NextJS build caches with GitHub actions:

```yaml
uses: actions/cache@v2
with:
  path: ${{ github.workspace }}/.next/cache
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
```

Using that is enough to reproduce. More details:

The cache generated by that snippet is keyed on `package-lock.json`. Now, from the GitHub Actions docs:

> When the action finds a cache, the action restores the cached files to the path you configure. If [and only if] there is no exact match, the action creates a new cache entry if the job completes successfully.
https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows

So as long as you are not updating `package-lock.json`, `/.next/cache` will never be updated again. As you keep developing your app, the cache gets more stale. I'm not sure what the consequences for this are on bundle caching, but at a minimum it increases build times significantly (on my app, builds were 30% slower than they should be).

An idea to fix this is to use `restore-keys`:

> The cache action first searches for cache hits for `key` and `restore-keys` in the branch containing the workflow run. If there are no hits in the current branch, the cache action searches for `key` and `restore-keys` in the parent branch and upstream branches.

```yaml
uses: actions/cache@v2
with:
  path: ${{ github.workspace }}/.next/cache
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]sx?') }}
  restore-keys: |
    ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
```

With this configuration, an exact cache hit will only happen if files on `**/*.js` didn't change. If any of those files change, we have a cache miss and GitHub will generate a new, updated cache. *However*, GitHub will still restore the most recently generated cache from either the current or parent branch (as long as it was built with the same `package-lock.json`).

Unfortunately, the second hash (`**/*.[jt]sx?`) has to be customized to each use case. However, I think that one will work for 95% of use cases, and for the other ones it'll just cache a bit less than ideal (but still much better than the current suggestion).

A caveat here is that the cache will keep growing over time with stale data, until a package-lock update happens. There's no ideal solution to this until cache prunes are available in NextJS builds. If this is a big problem to anyone, you can add the current week of the year to the cache key, so your cache is regenerated from scratch once a week. In our own repo, we do that at Sunday morning and follow it with a clean build to regenerate the cache while we're all enjoying our extended Sunday sleep.

**Comment by roim** [comment]
I'm wondering if this is enough

```yaml
uses: actions/cache@v2
with:
  path: ${{ github.workspace }}/.next/cache
  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**') }}
  restore-keys: |
    ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    ${{ runner.os }}-nextjs-
```
