### ISSUE TITLE
Fast refresh does not work after upgrading to 11.0.1

### ISSUE THREAD

**Issue by johnvonneumann7** [vercel/next.js#27326]
### What version of Next.js are you using?

11.0.1

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome, Safari

### What operating system are you using?

Windows 10 Pro 

### How are you deploying your application?

yarn dev

### Describe the Bug

I am setting up next.js using docker and docker-compose.

The version of next.js that we have been using is `10.1.3`, and we passed `CHOKIDAR_USEPOLLING=true` as an environment variable so that fast refresh would work with Docker.

However, after upgrading to the latest version `11.0.1` today, I have noticed that even when I use such an option
After changing file contents and saving, Fast refresh does not respond at all without any error, console log or log.

After that, I downgraded to the original `10.1.3` and it is working fine.
Also, using `next@canary` did not solve the problem.

### Expected Behavior

Fast refresh when the contents of a file are updated.

### To Reproduce

Dockerfile
```dockerfile
FROM node:lts-alpine

WORKDIR /usr/src/app

COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app/
RUN yarn install

COPY . /usr/src/app/
```
docker-compose.yml
```yml
frontend:
    build: ./frontend
    command: yarn dev
    volumes:
      - .:/workspace:cached
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file: frontend/.env.local
    ports:
      - "3000:3000"
```
.env.local
```env
CHOKIDAR_USEPOLLING=true
```

Please let me know if there are any other areas you need more information on.
Thank you.
