### ISSUE TITLE
media-query based CSS code-splitting

### ISSUE THREAD

**Issue by Sheraff** [vercel/next.js#29322]
### Describe the feature you'd like to request

I would like to see Next.js take advantage of the `media` attribute in `<link>` tags to allow for better code-splitting of CSS.

```html
<link rel="preload" href="/_next/static/css/908b69d8dc317304366e.css" as="style">
<link rel="preload" href="/_next/static/css/908b69d8dc317304366e-desktop.css" as="style" media="screen and (min-width: 1024px)">
<link rel="stylesheet" href="/_next/static/css/908b69d8dc317304366e.css" data-n-g="">
<link rel="stylesheet" href="/_next/static/css/908b69d8dc317304366e-desktop.css" media="screen and (min-width: 1024px)" data-n-g="">
```

### Describe the solution you'd like

When outputting CSS that includes media-queries, such as 

```css
.foo { color: red }
@media screen and (min-width: 1024px) {
    .foo { color: green }
}
.bar { font-size: 1rem }
@media screen and (min-width: 1024px) {
    .bar { font-size: 2rem }
}
```

There are some PostCSS plugins that allow for that output to be split into separate files, such as [postcss-extract-media-query](https://github.com/SassNinja/postcss-extract-media-query):

```css
.foo { color: red }
.bar { font-size: 1rem }
```
```css
@media screen and (min-width: 1024px) {
    .foo { color: green }
    .bar { font-size: 2rem }
}
```

I would like for such a configuration to be possible through the `next.config.js` (or other means if not that one).

### Describe alternatives you've considered

Due to the nature of Next.js of handling the loading of all files itself, it is currently not possible (to my knowledge) to use any alternative means to correctly achieve this end.
