### ISSUE TITLE
CSS @import url for loading fonts doesnt work

### ISSUE THREAD

**Issue by jaemil** [vercel/next.js#30567]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

17.0.1

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

Windows 10

### How are you deploying your application?

next start

### Describe the Bug

App.scss:
`@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');`

Loading the font with next dev works but not with next build (next start).

Tested with `optimizeFonts: false` but with same result.

### Expected Behavior

In next 11.0.1 the font was imported correctly

### To Reproduce

Inside App.scss
`@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');`

1. next build
2. next start

**Comment by alaadahmed** [comment]
Same here, I use TailwindCSS and in `globals.css` I do this: 
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');

  * {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }

  html,
  body {
    font-family: 'Poppins', sans-serif;
    line-height: 1.8;
  }
  // ...
```
 I see in chrome inspector that computed font is the one I imported, but it doesn't render as should be

On `next 11.1.2` this works fine!
