### ISSUE TITLE
@media query interpolation broken in 12.0.4

### ISSUE THREAD

**Issue by Eyas** [vercel/next.js#31562]
### What version of Next.js are you using?

12.0.4

### What version of Node.js are you using?

v16.11.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next dev

### Describe the Bug

PR #31407 fixed #30480 but introduced a new issue where interpolated strings in media queries are sometimes unnecessarily parenthesized.

Consider this, which used to work in 12.0.3 and before:

```ts
/// theme.ts

// Media Queries
export const Target: { [size in ScreenSizeQuery]: string } &
  { [prop in OtherQueries]: string } = {
  smallOnly: "screen and (max-width: 580px)",
  smallPlus: "screen and (min-width: 580px)",
  mediumPlus: "screen and (min-width: 700px)",
  largePlus: "screen and (min-width: 900px)",
  xlPlus: "screen and (min-width: 1200px)",
  touchScreen: "(hover: none), (pointer: coarse)",
};
```

And elsewhere in JSX:

```tsx
/// _app.tsx

// ...
      <style jsx global>{`
        html {
          font-size: ${Typography.base.size.default};
          line-height: ${Typography.base.lineHeight};
        }
        @media ${Target.mediumPlus} {
          html {
            font-size: ${Typography.base.size.mediumPlus};
          }
        }
        @media ${Target.largePlus} {
          html {
            font-size: ${Typography.base.size.largePlus};
          }
        }
      `}</style>
// ...
```

### Expected Behavior

This should compile into:

```css
            html {
                font-size: 16px;
                line-height: 1.75;
            }

            @media screen and (min-width: 700px) {
                html {
                    font-size:18px;
                }
            }

            @media screen and (min-width: 900px) {
                html {
                    font-size:21px;
                }
            }
```

### To Reproduce

Instead, in 12.0.4, it compiles into:

```css
html {font-size:16px; line-height:1.75}
@media (screen and (min-width: 700px)) {html {font-size:18px}}
@media (screen and (min-width: 900px)) {html {font-size:21px}}
```

Notably, this should be `@media screen and (min-width: 700px) {}` rather than `@media (screen and (min-width: 700px)) {}`.
