### ISSUE TITLE
Static Routes are throwing 404 page not found.

### ISSUE THREAD

**Issue by M0hammedImran** [vercel/next.js#31681]
### What version of Next.js are you using?

12.0.1

### What version of Node.js are you using?

16.0.0

### What browser are you using?

Chrome

### What operating system are you using?

Pop!_os

### How are you deploying your application?

Docker

### Describe the Bug

All the pages with `getInitialProps` and `getServerSideProps` are working, but the static pages are showing as 404.  

My `Dockerfile` is from https://nextjs.org/docs/deployment#docker-image and no changes have been made.

my docker-compose.yml
```yml
version: "3.4"

x-default-opts: &default-opts
    cpu_count: 1
    cpus: 0.5
    cpu_percent: 60
    mem_limit: 500m
    memswap_limit: 1gb
    mem_reservation: 256m

services:
    reverse_proxy:
        container_name: "tacticalarenas_reverse_proxy"
        image: "traefik:v2.5"
        restart: "unless-stopped"
        command:
            #- '--api.insecure=true
            #- '--log.level=DEBUG'
            - "--providers.docker"
            - "--providers.docker.exposedByDefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
            - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.le.acme.tlschallenge=true"
            #- '--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
            - "--certificatesresolvers.le.acme.email=<email>"
            - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
        ports:
            - published: 80
              target: 80
            - published: 443
              target: 443
        volumes:
            # So that Traefik can listen to the Docker events
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./letsencrypt:/letsencrypt:rw"

    tacticalarenas:
        container_name: "tacticalarenas_app"
        image: "<my-image>"
        <<: *default-opts
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=Host(`tacticalarenas.in`, `www.tacticalarenas.in`)"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.routers.frontend.tls=true"
            - "traefik.http.routers.frontend.tls.certresolver=le"

```

### Expected Behavior

All the pages rendered as usual.

### To Reproduce

All I did is scaffold the app and started the app using docker.
