### ISSUE TITLE
SASS variables not resolved when used in definition of CSS variables

### ISSUE THREAD

**Issue by catamphetamine** [vercel/next.js#34270]
### Run `next info` (available from version 12.0.8 and up)

> next info

'pnpm' is not recognized as an internal or external command,
operable program or batch file.

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 14.17.3
      npm: 6.10.0
      Yarn: 1.17.3
      pnpm: N/A
    Relevant packages:
      next: 12.0.10
      react: 17.0.2
      react-dom: 17.0.2

### What version of Next.js are you using?

12.0.10

### What version of Node.js are you using?

14.17.3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying your application?

next start

### Describe the Bug

SASS variables not resolved when used in definition of CSS variables, unless forcing it with a `#{}` syntax workaround.

In the example below, `--body-background-color-not-working` is not substituted properly.

Code:

```scss
body {
  background-color: $primary;
  --body-background-color-not-working: $primary;
  --body-background-color: #{$primary};
  background-color: var(--body-background-color);
}
```

Result:

![image](https://user-images.githubusercontent.com/477167/153718380-08219d4a-50c4-4d12-9373-88b669eb366b.png)

### Expected Behavior

`--body-background-color-not-working` CSS variable being correctly substituted

### To Reproduce

See the code snippet above.
