### ISSUE TITLE
Loading custom font when using styled-components loads multiple times and creates short flashes

### ISSUE THREAD

**Issue by cdelacombaz** [vercel/next.js#34462]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
    Binaries:
      Node: 16.13.0
      npm: 8.3.0
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.0.11-canary.20
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Firefox Developer 98.0b5 (64-bit) & Google Chrome Version 98.0.4758.80 (Official Build) (x86_64)

### Describe the Bug

# Bug report description

I am using NextJS with styled-components and try to load a custom font. I tried different implementations and all of 
them are buggy. Am I doing something wrong or is there a bug somewhere?

## Bug 1: font-face defined in GlobalStyles / styled-components  (main branch)

If I define the font-face in style/index.js, the **font gets loaded 3 times** and sometimes **there is a short flash** where 
the text disappears and appears again.

Check out this video (maybe slow it down to 0.25x): https://www.youtube.com/watch?v=tGsEaL8Ppvk

## Bug 2: font-face defined in global.css (css branch)

Defining everything in global.css works just fine. Also defining the font-face in global.css and assigning the 
font-family in styled components GlobalStyle works. But if I add `display: flex` or `display: grid` to the body tag in 
my global styles, the font is first displayed incorrectly and then switches to my custom font. If I use 
`display: absolute`, no problem, it works as intended.

I don't get why using flex or grid affects fonts. I did move this code in a global css in my project, so it works fine, 
but would like to find out the reason or the bug, in order to fix it or not make this mistake again in the future.

Check out this video (maybe slow it down to 0.25x): https://www.youtube.com/watch?v=mvxPKKQmrDA

### Expected Behavior

Bug 1: font-face definition in GlobalStyles should not trigger 3 requests to load the fonts and the page should not rerender/flash

Bug 2: using display flex or display grid should have the same behavior as display block or absolute (related to fonts). Custom font should be displayed from the beginning.

## Bug 1: font-face defined in GlobalStyles / styled-components  (main branch)

1. Clone repo https://github.com/cdelacombaz/nextjs-fonts-bugreport
2. run `yarn install`
3. Ensure that you are on **main** branch
4. run `yarn run dev`
5. visit http://localhost:3000
6. disable cache in your browser and reload the page (flash only happens sometimes)

## Bug 2: font-face defined in global.css (css branch)

(clone repo and run `yarn install` as mentioned previously)
1. Switch to **css** branch
2. run `yarn run dev`
3. visit http://localhost:3000
4. refresh the page

**Comment by jamiem-splunk** [comment]
I'm having this exact issue - have there been any updates or found workarounds?

**Comment by cdelacombaz** [comment]
It was already on canary, but version 12. I have updated all the packages and tested if the bugs persisted, and the did.

@jamiem-splunk sorry, only saw your comment now. I added the code in a global.css file instead of using styled-component's GlobalStyle/theme.


Example workaround:
 
```css
/* global.css */
@font-face {
    font-family: "YourFontName";
    font-style: normal;
    font-weight: 300 700;
    font-display: optional;
    src: url(/fonts/YourFontName.woff2) format("woff2");
}

body {
    font-family: 'YourFontName', -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans,
    Droid Sans, Helvetica Neue, sans-serif;
    /* flex properties had to be set here instead of globalStyles - else I got a bug with the fonts where the custom
     font would appear and disappear all the time. Don't know the reason though.. */
    display: flex;
    flex-direction: column;
}
```
