### ISSUE TITLE
The location where css import appears is not at the beginning, resulting in css import not taking effect.

### ISSUE THREAD

**Issue by masx200** [vercel/next.js#34510]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

 Operating System:        
      Platform: win32        
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 17.5.0
      npm: 8.3.1
      Yarn: 1.22.10
      pnpm: 6.27.1
    Relevant packages:
      next: 12.1.0
      react: 17.0.2
      react-dom: 17.0.2

### What browser are you using? (if relevant)

Chrome  98.0.4758.102（正式版本） （64 位）

### How are you deploying your application? (if relevant)

next build

### Describe the Bug

https://nextjs-masx200-home.vercel.app/_next/static/css/417c9f617d24a150.css

```css
@charset "UTF-8";body,html {
    font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif;
    margin: 0;
    padding: 0
}

a {
    color: blue;
    text-decoration: none
}

* {
    box-sizing: border-box
}

@import url(https://cdn.staticfile.org/mui/3.7.1/css/mui.min.css);@import url(https://cdn.jsdelivr.net/gh/masx200/masx200.github.io@4.2.2/src/assetscss/github-6556dfa9be535e551ffffaadfecdad99.min.css);@import url(https://cdn.jsdelivr.net/gh/masx200/masx200.github.io@4.2.2/src/assetscss/github-frameworks-a2fba223d5af91496cac70d4ec3624df.min.css);@import url(https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css);@-webkit-keyframes App-logo-spin {
    0% {
        transform: rotate(0deg)
    }

    to {
        transform: rotate(1turn)
    }
}

.App-header {
    background-color: #fff
}

nav {
    width: 100%
}

.图片列表200 img {
    height: auto;
    max-height: 200px;
    max-width: 100%;
    min-height: 150px;
    min-width: 150px;
    width: auto
}
```

### Expected Behavior

https://nextjs-masx200-home.vercel.app/_next/static/css/417c9f617d24a150.css

```css
@import url(https://cdn.staticfile.org/mui/3.7.1/css/mui.min.css);@import url(https://cdn.jsdelivr.net/gh/masx200/masx200.github.io@4.2.2/src/assetscss/github-6556dfa9be535e551ffffaadfecdad99.min.css);@import url(https://cdn.jsdelivr.net/gh/masx200/masx200.github.io@4.2.2/src/assetscss/github-frameworks-a2fba223d5af91496cac70d4ec3624df.min.css);@import url(https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css);
@charset "UTF-8";body,html {
    font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif;
    margin: 0;
    padding: 0
}

a {
    color: blue;
    text-decoration: none
}

* {
    box-sizing: border-box
}

@-webkit-keyframes App-logo-spin {
    0% {
        transform: rotate(0deg)
    }

    to {
        transform: rotate(1turn)
    }
}

.App-header {
    background-color: #fff
}

nav {
    width: 100%
}

.图片列表200 img {
    height: auto;
    max-height: 200px;
    max-width: 100%;
    min-height: 150px;
    min-width: 150px;
    width: auto
}
```

### To Reproduce

https://github.com/masx200/nextjs-masx200-home/blob/d8f4143c30a2e24686809180a6f8b900a69993ec/styles/styles.64e1a1f300e049d9a965.css
