### ISSUE TITLE
Server crash with invalid api route URI and dd-trace

### ISSUE THREAD

**Issue by jakst** [vercel/next.js#35132]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```yaml
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
Binaries:
  Node: 16.14.0
  npm: 8.3.1
  Yarn: 1.22.17
  pnpm: N/A
Relevant packages:
  next: 12.1.1-canary.7
  react: 17.0.2
  react-dom: 17.0.2
```

### Describe the Bug

I opened this issue yesterday [https://github.com/vercel/next.js/issues/35113](https://github.com/vercel/next.js/issues/35113), but it seems I hadn't dug deep enough, and so I reproduced the wrong thing. We actually do have a server crash.

The crash happens under the following circumstances:
* There is a Next.js catch all page route, like `pages/[...catchAll].js`
* The Next.js server is started with dd-trace running, like this `NODE_OPTIONS='--require ./datadog' next start` and `datadog.js` has this content: `require('dd-trace').init()`. This applies to any version of dd-trace between 1.2.0 and the latest 2.3.1.
* There is a request to an api route with an invalid URI `/api/%ff`.

It produces the following stack trace from Next.js

```
./node_modules/next/dist/shared/lib/router/utils/route-matcher.js:18
                throw new _utils.DecodeError('failed to decode param');
                      ^
DecodeError: failed to decode param
    at decode (./node_modules/next/dist/shared/lib/router/utils/route-matcher.js:18:23)
    at ./node_modules/next/dist/shared/lib/router/utils/route-matcher.js:26:80
    at Array.map (<anonymous>)
    at ./node_modules/next/dist/shared/lib/router/utils/route-matcher.js:26:67
    at Array.forEach (<anonymous>)
    at Object.match (./node_modules/next/dist/shared/lib/router/utils/route-matcher.js:22:29)
    at NextNodeServer.handleApiRequest (./node_modules/next/dist/server/base-server.js:538:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

I don't know whether the actual error is in next.js or in dd-trace, but they are both black boxes to me and I only get a stack trace containing next.js code. I have cross-posted this in the dd-trace repo: https://github.com/DataDog/dd-trace-js/issues/1898

### Expected Behavior

The server responds with 404 or 400.

### To Reproduce

* Clone this repo: https://github.com/jakst/nextjs-router-crash-reproduction
* Run `yarn build`
* Run `yarn start`
* Visit http://localhost:3000/api/%ff
