### ISSUE TITLE
Next.js(running on Google App Engine): Client Side(browser) can not get the env values from process.env.NEXT_PUBLIC_XXX only production mode.

### ISSUE THREAD

**Issue by tkmktkhr** [vercel/next.js#36181]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

Docker image base: node:14-slim
```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Debian 5.10.103-1 (2022-03-07)
    Binaries:
      Node: 14.19.1
      npm: 6.14.16
      Yarn: 1.22.17
      pnpm: N/A
    Relevant packages:
      next: 12.1.5
      react: 17.0.2
      react-dom: 17.0.2
```

Also,

Docker image base: node:16-slim
```
    Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Debian 5.10.103-1 (2022-03-07)
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 12.1.4
      react: 17.0.2
      react-dom: 17.0.2
```

### What browser are you using? (if relevant)

Chorme: Version 100.0.4896.75 (Official Build) (x86_64), Brave: Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (x86_64)

### How are you deploying your application? (if relevant)

next start, Google App Engine(Flexible)

### Describe the Bug

It cloud be wrong to write here...

Only when Next.js server(production mode) runs on Google App Engine flexible environment.
Next.js Client Side(browser) can not get the env values from `process.env.NEXT_PUBLIC_XXX` only production mode, while server side can get them.
Moreover, Next.js Client Side(browser) can get the values when running as development mode(next dev).

However, if the environment variables are loaded from `next.config.js` using `publicRuntimeConfig` in nextConfig module, Next.js Client Side(browser) can get them correctly even on production mode running.

I have not checked whether this problem happens on AWS, Azure, Vercel and so on, but  running Docker container on local PC, it works correctly.

### Expected Behavior

As written on the official [documentation](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser), environment variables should be available in the browser even if they are written as just `process.env.NEXT_PUBLIC_XXX`.

### To Reproduce

Deployment configuration files. (Deployment by GAR, Github Actions)
1. app.yaml(for GAE) like the bellow.
```
runtime: custom
env: flex

service: nextjs-server

instance_class: B2

handlers:
  - url: .*
    script: auto

env_variables:
  ENVIRONMENT: start // when this value is 'dev', it is totally fine. No problem on GAE.
  NEXT_PUBLIC_SECRET_FROM_GITHUB_SECRETS: $NEXT_PUBLIC_SECRET_FROM_GITHUB_SECRETS

manual_scaling:
  instances: 1
```

2. .github/workflows/xxx.yaml like the bellow.
```
name: any
on:
  push:
    branches: [any]

jobs:
  deploy:
    name: GAE deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: replace app.yaml
        run: |
          sed -i -e 's/$NEXT_PUBLIC_SECRET_FROM_GITHUB_SECRETS/${{ secrets.NEXT_PUBLIC_SECRET_FROM_GITHUB_SECRETS }}/g' app.yaml
      - name: Deploy an App Engine app
        id: deploy-app
        uses: google-github-actions/deploy-appengine@v0.3.1
        env:
          NEXT_PUBLIC_SECRET_FROM_GITHUB_SECRETS: ${{ secrets.NEXT_PUBLIC_SECRET_FROM_GITHUB_SECRETS }}
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v1 
```

3. Dockerfile
```
...
RUN npm run build
ARG ENVIRONMENT
ENV ENVIRONMENT=$ENVIRONMENT
CMD npm run $ENVIRONMENT
```

4. package.json
```
...
  "scripts": {
    "dev": "NODE_OPTIONS='--inspect' next dev",
    "build": "next build",
    "start": "next start",
...
```

Should you need more information, please comment. Thanks.
