### ISSUE TITLE
Unable to run tests against a custom server starting from v12.0.9

### ISSUE THREAD

**Issue by micheleriva** [vercel/next.js#37176]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.1.0
  npm: 8.8.0
  Yarn: N/A
  pnpm: 7.0.1
Relevant packages:
  next: 12.1.6
  react: 18.1.0
  react-dom: 18.1.0
```

### Describe the Bug

Even though the v12.0.9 is described as "completely backward-compatible", it introduces some changes in how HTTP headers are managed.

This makes it impossible to use modules such as [light-my-request](https://github.com/fastify/light-my-request) to inject fake HTTP request/responses to run unit/integration tests without running an actual server.

By running tests that were working fine until v12.0.8, I get the following error:

```
 ✖ Cannot read properties of undefined (reading 'headers')

  test: should support a custom handler
  stack: |
    sendEtagResponse (node_modules/next/server/send-payload/index.ts:89:17)
    Object.sendRenderResult (node_modules/next/server/send-payload/index.ts:45:9)
  at:
    line: 89
    column: 17
    file: node_modules/next/server/send-payload/index.ts
    function: sendEtagResponse
  type: TypeError
  tapCaught: unhandledRejection
```

By looking at the [release notes for v12.0.9](https://github.com/vercel/next.js/releases?q=12.0.9&expanded=true), I can't identify a place where this change has been introduced.

In any case, tests run using Cypress or manual QA testing on a browser are working fine.

Please note that this is not a problem with that project exclusively, but could happen with every project using [light-my-request](https://www.npmjs.com/package/light-my-request) for testing purposes.

### Expected Behavior

Given that the upgrade to v12.0.9 should be fully backward compatible, I'd expect to be able to perform the upgrade and run the tests of the [fastify-nextjs](https://github.com/fastify/fastify-nextjs) project without errors.

### To Reproduce

You can reproduce the error by running the test suite for [this project](https://github.com/fastify/fastify-nextjs), after upgrading Next.js to `>=12.0.9`.
