### ISSUE TITLE
@next/font + font-feature-settings

### ISSUE THREAD

**Issue by weleo** [vercel/next.js#41862]
### Describe the feature you'd like to request

Are `font-feature-settings` supported?

```css
@font-face {
        font-family: 'Inter var';
        font-feature-settings: 'cv02', 'cv03', 'cv04', 'cv11', 'ss03';
}
```

### Describe the solution you'd like

```ts
const inter = Inter({
        weight: 'variable',
        subsets: ['latin'],
        features: ['cv02', 'cv03', 'cv04', 'cv11', 'ss03']
})
```

### Describe alternatives you've considered

```css
@font-face {
        font-family: 'Inter var';
        font-feature-settings: 'cv02', 'cv03', 'cv04', 'cv11', 'ss03';
}
```
