### ISSUE TITLE
@next/font subsets option still adds other subsets in <head>

### ISSUE THREAD

**Issue by thomasledoux1** [vercel/next.js#42361]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
    Binaries:
      Node: 16.14.2
      npm: 8.5.0
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.2-canary.0
      eslint-config-next: 13.0.1
      react: 18.2.0
      react-dom: 18.2.0

### Describe the Bug

I'm using @next/font to load my font from Google. I added the following in my `next.config.js`:
```js
  experimental: {
    fontLoaders: [{loader: '@next/font/google', options: {subsets: ['latin']}}],
  }
```

In my component I use the following:
```js
import {Roboto_Flex} from '@next/font/google'

const roboto = Roboto_Flex()
return <div className={roboto.className}>...</div>
```

When inspecting the `<head>` section in the HTML output, I can see the following `<style>` tag being added:

```css
<style>
/* cyrillic-ext */
@font-face {
  font-family: '__Roboto_Flex_848f71';
  font-style: normal;
  font-weight: 100 1000;
  font-stretch: 100%;
  font-display: optional;
  src: url(/_next/static/media/5f5bfb4319f60b4d.woff2) format('woff2');
  unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
}
/* cyrillic */
@font-face {
  font-family: '__Roboto_Flex_848f71';
  font-style: normal;
  font-weight: 100 1000;
  font-stretch: 100%;
  font-display: optional;
  src: url(/_next/static/media/944e03cf40dc9062.woff2) format('woff2');
  unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
}
/* greek */
@font-face {
  font-family: '__Roboto_Flex_848f71';
  font-style: normal;
  font-weight: 100 1000;
  font-stretch: 100%;
  font-display: optional;
  src: url(/_next/static/media/8d4994c51da15746.woff2) format('woff2');
  unicode-range: U+0370-03FF;
}
/* vietnamese */
@font-face {
  font-family: '__Roboto_Flex_848f71';
  font-style: normal;
  font-weight: 100 1000;
  font-stretch: 100%;
  font-display: optional;
  src: url(/_next/static/media/67b188343f397499.woff2) format('woff2');
  unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB;
}
/* latin-ext */
@font-face {
  font-family: '__Roboto_Flex_848f71';
  font-style: normal;
  font-weight: 100 1000;
  font-stretch: 100%;
  font-display: optional;
  src: url(/_next/static/media/c48fa5e09690beb0.woff2) format('woff2');
  unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
}
/* latin */
@font-face {
  font-family: '__Roboto_Flex_848f71';
  font-style: normal;
  font-weight: 100 1000;
  font-stretch: 100%;
  font-display: optional;
  src: url(/_next/static/media/eb15695615c924c8.p.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}@font-face {font-family: '__Roboto_Flex_Fallback_848f71';src: local("Arial");ascent-override: 93.26%;descent-override: 24.54%;line-gap-override: 0.00%;size-adjust: 99.48%
}.__className_848f71 {font-family: '__Roboto_Flex_848f71', '__Roboto_Flex_Fallback_848f71';font-style: normal
}
</style>
```

### Expected Behavior

I was expecting to only see the Latin subset pop up in my `<style>` tag. Is this a wrong assumption? Does the inclusion of the other subsets in the `<style>` tag not have any negative impact on performance etc?

### Link to reproduction

https://github.com/thomasledoux1/next13-font-loading-bug

### To Reproduce

Run `npm run dev`, open DevTools, and look for `Roboto` in the "Elements" tab. You should find the `<style>` tag, and see the subsets there.
