### ISSUE TITLE
Resolution errors may happen in server components with packages whose exports field only includes ES module import

### ISSUE THREAD

**Issue by joulev** [vercel/next.js#42534]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```yml
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Binaries:
  Node: 18.12.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 7.14.2
Relevant packages:
  next: 13.0.3-canary.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
```

### Describe the Bug

In some ES module packages, the `exports` field in `package.json` only includes one `import` field. This causes some resolution errors when imported to server components. However, `getStaticProps` and other data-fetching functions in `pages` directory still works fine.

Since it's quite vague to me, I think I will continue with the example. Clone the repo linked below.

The path `/test` (in `pages` directory, with `getStaticProps`) works as intended. Meanwhile, `/` (RSC in `app` directory) doesn't, with a confusing error message:

```
Module not found: Package path . is not exported from package /path/to/node_modules/periscopic
(see exports field in /path/to/node_modules/periscopic/package.json)
```

That is (apparently) because `periscopic`'s `exports` field is like this

```json
"exports": {
  "import": "./src/index.js"
}
```

After modifying this `exports` manually, in `periscopic` and 2 other similar modules (`is-reference` and `estree-walker`),

```diff
- "exports": {
-  "import": "./src/index.js"
- },
+ "exports": "./src/index.js",
```

then `/` works as intended.

Ref: https://github.com/orgs/mdx-js/discussions/2168

### Expected Behavior

`/` should not crash and gives the same output as `/test` in the linked reproduction repository.

### Link to reproduction

https://github.com/joulev/debug/tree/nextjs-42534

### To Reproduce

Mentioned in the "Describe the Bug" section.

* Clone the repository
* `npm install`
* `npm run dev`
* Open `/`: crash
* Open `/test`: works normally
