### ISSUE TITLE
dynamicParams of parent segments overrides dynamicParams of child segments

### ISSUE THREAD

**Issue by joulev** [vercel/next.js#42940]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```yml
Operating System:
  Platform: linux
  Arch: x64
  Version: #100~18.04.1-Ubuntu SMP Mon Oct 17 11:44:30 UTC 2022
Binaries:
  Node: 18.11.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: N/A
Relevant packages:
  next: 13.0.3-canary.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
```

(v13.0.4-canary.0 is not actually released to NPM for some reasons)

### Describe the Bug

As the title specified.

Say if I have dynamic route `/[a]/[b]`, where I want `[a]` to be static (so anything except specified by `generateStaticParams` will return 404), but `[b]` to be dynamic.

Then in `app/[a]/layout.tsx` I would do

```ts
export async function generateStaticParams() {
  return [{ a: "a" }];
}
export const dynamicParams = false;
```

In `app/[a]/[b]/page.tsx`,

```ts
export async function generateStaticParams() {
  return [];
}
export const dynamicParams = true;
```

Then I would have

* `/b/hello` → 404 (of course, since only valid value for `a` is `"a"`
* `/a/hello` → 404 **not desired** – `a` satisfies its allowed values and `b` can be anything.

### Expected Behavior

In the example above, `/b/hello` should return 404 as before but `/a/hello` should return the page normally and not throw 404.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/joulev/debug/tree/nextjs-dynamicparams

### To Reproduce

* Clone the repo
* `npm install`
* `npm run dev`
* Visit http://localhost:3000/b/hello → 404 (expected)
* Visit http://localhost:3000/a/hello → also 404 (buggy)

### Additional info

This may not necessarily be a bug but a feature, in such case probably it's best to clarify this overriding behaviour in the documentation.

But I'd still consider it a bug because, otherwise what should I do to make sure `[a]` is static while `[b]` is dynamic?
