### ISSUE TITLE
Add meta viewport tag to app directory automatically

### ISSUE THREAD

**Issue by joulev** [vercel/next.js#43711]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```yaml
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Binaries:
  Node: 18.12.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 7.17.1
Relevant packages:
  next: 13.0.7-canary.1
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://nextjs-appdir-responsiveness-issue-146a.vercel.app/

### To Reproduce

1. `pnpx create-next-app@latest --experimental-app`
2. Remove `<meta content="width=device-width, initial-scale=1" name="viewport" />` from the root `head.tsx`.
3. `pnpm install && pnpm build && pnpm start`
4. Go to browser devtool of localhost:3000
5. Look at the `<head>` tag

### Describe the Bug

```tsx
<meta content="width=device-width, initial-scale=1" name="viewport" />
```

is missing from `<head>`. While it may be obvious it's due to we removing the tag in step 2, this means developers have to manually add the tag now. That isn't the case for the `pages` directory, hence caused a lot of confusion for people migrating from Next.js 12 to Next.js 13.

I know you have made much effort to mitigate this confusion, e.g. to add the tag by default with `create-next-app` or show the tag in (an awkward place in) [the beta docs](https://beta.nextjs.org/docs/upgrade-guide#step-3-migrating-nexthead). However I reckon this is not sufficient &ndash; many still don't do that, making their app function not well on mobile devices.

So I think many will agree with me here that the `pages` behaviour should be replicated in `app` as well: the above meta tag should be automatically included every time, without the developer needing to manually add it.

(Note: This issue is an exact duplicate of #41842 and the repro link is taken from that issue as well; however that one was closed by the author so I open this for it to be fixed. Please feel free to reopen it and close this as duplicate.)

### Expected Behavior

The viewport meta tag should be automatically included in the `app` directory.
