### ISSUE TITLE
bundle css in wrong order

### ISSUE THREAD

**Issue by bluelovers** [vercel/next.js#44977]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

.

### Link to the code that reproduces this issue

.

### To Reproduce

```scss
@import './font-notosans.scss';
@import './font-jetbrains-mono.scss';
@import './vars.scss';
//@import 'antd/dist/reset.css';

@import "primereact/resources/themes/lara-light-indigo/theme.css"; //theme
@import "primereact/resources/primereact.min.css"; //core css
@import "primeicons/primeicons.css"
; //icons
@import 'primeflex/primeflex.css';

@import './scrollbar.scss';

:root, body, html
{
	-webkit-font-feature-settings: "liga" on, "calt" on;
	-webkit-font-smoothing: antialiased;
	text-rendering: optimizeLegibility;
	/*font-family: $font_jetbrains, $font_nextjs;*/
}
```

---

_app.tsx

```tsx
import '../assets/styles/style.scss'
```

### Describe the Bug

![image](https://user-images.githubusercontent.com/167966/212991027-e6b8d16f-2fa4-43cc-872b-690e0e0c34be.png)

this bug only happen on Production Deployment

### Expected Behavior

this code is in top of css

```scss
@import"https://fonts.googleapis.com/earlyaccess/notosanstc.css";@import"https://fonts.googleapis.com/earlyaccess/notosanssc.css";@import"https://fonts.googleapis.com/earlyaccess/notosansjp.css";@import"https://fonts.googleapis.com/earlyaccess/notosanskr.css";@font-face {
	font-family: JetBrains Mono;
	src: url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/otf/JetBrainsMono-Regular.otf) format("opentype"),url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/webfonts/JetBrainsMono-Regular.woff2) format("woff2"),url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/ttf/JetBrainsMono-Regular.ttf) format("truetype");
	font-weight: 400;
	font-style: normal
}

@font-face {
	font-family: JetBrains Mono;
	font-style: italic;
	font-weight: 400;
	src: url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/otf/JetBrainsMono-Italic.otf) format("opentype"),url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/webfonts/JetBrainsMono-Italic.woff2) format("woff2"),url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/ttf/JetBrainsMono-Italic.ttf) format("truetype")
}

@font-face {
	font-family: JetBrains Mono;
	font-style: normal;
	font-weight: 700;
	src: url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/otf/JetBrainsMono-Bold.otf) format("opentype"),url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/webfonts/JetBrainsMono-Bold.woff2) format("woff2"),url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/ttf/JetBrainsMono-Bold.ttf) format("truetype")
}

@font-face {
	font-family: JetBrains Mono;
	font-style: italic;
	font-weight: 700;
	src: url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/otf/JetBrainsMono-BoldItalic.otf) format("opentype"),url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/webfonts/JetBrainsMono-BoldItalic.woff2) format("woff2"),url(https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/fonts/ttf/JetBrainsMono-BoldItalic.ttf) format("truetype")
}
```
