### ISSUE TITLE
[NEXT-482] should allow synchronous `generateMetadata`

### ISSUE THREAD

**Issue by joulev** [vercel/next.js#45685]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```yaml
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64
Binaries:
  Node: 19.6.0
  npm: 9.4.0
  Yarn: 1.22.19
  pnpm: 7.26.3
Relevant packages:
  next: 13.1.7-canary.7
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true), Head component/file (next/head / head.js)

### Link to the code that reproduces this issue

N/A

### To Reproduce

* `pnpx create next-app@canary` with the `app` directory enabled
* Add a *synchronous* `generateMetadata()` to, say, `app/page.tsx`
* `next dev`

### Describe the Bug

The following very unclear error is thrown.

```
TypeError: layerMetadataPromise.then is not a function
```

(In prod mode a slightly clearer error is thrown, "Page [...] does not match the required types of a Next.js Page", but to a new user I'd say both errors are equally unclear.)

I think this is because `generateMetadata` is expected to be an `async` function. This limitation is not mentioned in the documentation yet.

### Expected Behavior

1. If `generateMetadata` must be `async`:

    * The limitation should be mentioned clearly in the documentation.
    * The error message should be clearer.

2. Otherwise

    * Well... the synchronous version of `generateMetadata` should work normally.

I personally prefer the second approach.

<sub>[NEXT-482](https://linear.app/vercel/issue/NEXT-482/should-allow-synchronous-generatemetadata)</sub>
