### ISSUE TITLE
Custom font fallbacks are not allowed with next/font/google

### ISSUE THREAD

**Issue by alfawal** [vercel/next.js#53024]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:41 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8103
    Binaries:
      Node: 19.8.1
      npm: 9.8.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10
      eslint-config-next: 13.4.10
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Font optimization (next/font)

### Link to the code that reproduces this issue or a replay of the bug

https://gist.github.com/alfawal/5329f1a884653401203730baf6bac307

### To Reproduce

Add multiple fonts as described in the docs.

### Describe the Bug

Next.js adds a fallback font by default which results in preventing the custom fallback font that you add from loading.

### Expected Behavior

To support different glyph language fonts (e.g. Arabic and English) we do assign an Arabic font and then the wanted English font as a callback.

Arabic font: Noto Sans Arabic
Latin font: Inter
Becomes:
```css
html {
    font-famility: "Noto Sans Arabic", "Inter";
}
```

But with the code snippet that I provided, it becomes:
```css
html {
    font-family: '__Noto_Sans_Arabic_fb2f84', '__Noto_Sans_Arabic_Fallback_fb2f84', '__Inter_20951f', '__Inter_Fallback_20951f';
}
```

Where it should look like:
```css
html {
    font-family: '__Noto_Sans_Arabic_fb2f84', '__Inter_20951f';
}
```

The work around that I did about it was splitting the coming font family from each of the fonts and taking the first only and then adding it.
```js
import { Inter, Noto_Sans_Arabic } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});

const noto = Noto_Sans_Arabic({
  subsets: ["arabic"],
});

export default async function Layout({ children }) {
  return (
    <html>
      <style>
        {`
          html {
            font-family: ${noto.style.fontFamily.split(",")[0]}, ${
              inter.style.fontFamily.split(",")[0]
            };
          }
        `}
      </style>
      <body>
        {children}
      </body>
    </html>
  );
}

```
