### ISSUE TITLE
Image Type Error In Github Actions

### ISSUE THREAD

**Issue by Carlwirkus** [vercel/next.js#53959]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020
    Binaries:
      Node: 20.1.0
      npm: 9.6.4
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.14-canary.2
      eslint-config-next: 13.4.13
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.1.6
    Next.js Config:
      output: N/A
```

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Carlwirkus/next-image-type-error

### To Reproduce

1. Create a new next project
2. Import an image
3. Run tsc in github actions

### Describe the Bug

Imported image type definitions are  not working inside GitHub actions however they do work locally. In this [repo](https://github.com/Carlwirkus/next-image-type-error) there is a new nextjs project with an action checking the type definitions by running tsc.

You get the following error even though the types are being imported with `next-env.d.ts`

```
app/page.tsx:2:19 - error TS2307: Cannot find module '@/public/ricky.jpg' or its corresponding type declarations.

2 import image from "@/public/ricky.jpg"
```

### Expected Behavior

No type error in CI

**Comment by kylemcd** [comment]
Have you tried setting a `baseUrl` in your `tsconfig.json` file?

See: https://www.typescriptlang.org/tsconfig#baseUrl

**Comment by Carlwirkus** [comment]
I just tried but unfortunately this doesn't resolve the issue. [commit](https://github.com/Carlwirkus/next-image-type-error/commit/c8ff46f3153d7a0a7586396abc81bb983c627027)

**Comment by salzhrani** [comment]
`next-env.d.ts` is git ignored. not sure of the reason

**Comment by peterstuart** [comment]
> next-env.d.ts is git ignored. not sure of the reason

This led me to the fix. I think `next-env.d.ts` is intentionally ignored as part of the template Next uses to set up a project, but it *is* required for type-checking to work correctly. It is generated at build time, so if you run `next build` in GitHub Actions *before* you try to type-check, it will work.

**Comment by sregg** [comment]
`next build` is quite slow, just to generate a 5 line file...
Is there a smaller command we can run to generate it?
Looks like `next lint` generates it but it's awkward to run it twice...
Also, does the [Vercel Github app](https://github.com/apps/vercel) run linting and testing automatically?

**Comment by RomaLetodiani** [comment]
[Awesome Solution](https://github.com/t3-oss/create-t3-turbo/issues/472#issuecomment-2001909818)

**Comment by RomaLetodiani** [comment]
```
  type-check:
    name: Type Checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Create next-env.d.ts
        run: echo -e '/// <reference types="next" />\n/// <reference types="next/image-types/global" />' > src/next-env.d.ts

      - name: Run TypeScript Type Check
        run: npm run check-types
```
