### ISSUE TITLE
Native CSS nesting support for css modules

### ISSUE THREAD

**Issue by equinusocio** [vercel/next.js#55053]
### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/magical-chatelet-9ddsys?file=%2Fnext.config.js%3A4%2C3

### To Reproduce

1. Create any css module file
2. Write a valid native CSS nested code
   ```css
    .Layout {
      border: 10px solid red;
    
      & body {
        height: 100vh;
        margin: 0;
        border: 10px solid blue;
      }
    }

    /* or */

    .Layout {
      border: 10px solid red;
    
      body {
        height: 100vh;
        margin: 0;
        border: 10px solid blue;
      }
    }
   ```
3. See the error about pure selectors

### Current vs. Expected behavior

Nextjs and the check it performs on CSS modules prevents from using the new CSS native nesting syntax (which is now supported by evergreen browsers).

It returns error about a simple nested CSS while this should be allowed as valid CSS syntax now.

Error:

`Selector "& body" is not pure (pure selectors must contain at least one local class or id)`

See the reproduction link.

Next should allow native and valid CSS syntax and avoid extra checks on "pure selectors" where not needed.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP PREEMPT_DYNAMIC Sun Aug  6 20:05:33 UTC 2023
    Binaries:
      Node: 16.17.0
      npm: 8.15.0
      Yarn: 1.22.19
      pnpm: 7.1.0
    Relevant packages:
      next: 13.0.8-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Additional context

The selector `.Layout { & body {} }`  should be validated as `.Layout body {}` which is a "pure" css module selector.

**Comment by samir9saeedi** [comment]
FWIW you can use this PostCSS plugin in the meantime: https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-nesting

**Comment by samir9saeedi** [comment]
No worries. The plugin I've linked to (css-nesting) supports the new official syntax, which is slightly different from what SASS uses. That syntax has its own plugin as well (css-nested), which is what you're most likely referring to. Doesn't make a difference in the bundle size presumably, just more future-proof.

**Comment by equinusocio** [comment]
> No worries. The plugin I've linked to (postcss-nesting) supports the new official syntax, which is slightly different from what SASS uses. That syntax has its own plugin as well (postcss-nested), which is what you're most likely referring to. Doesn't make a difference in the bundle size presumably, just more future-proof.

Yep, we use `postcss-nesting` since 2016 via `postcss-preset-env`. Now that the native nesting is available we would like to disable this plugin, we want nested CSS in the browser since the CSS size is reduced drastically.


> Doesn't make a difference in the bundle size presumably, just more future-proof.
Yep, it affects the final CSS drastically, here a basic example:

```css
.MyLongClassName {
  color: red;

  &[data-button-color="blue"] {
    color: blue;
  }
  
  &[data-button-color="green"] {
    color: green;
  }  
}

/* All of this, when processed, become */

.MyLongClassName { color: red }
.MyLongClassName[data-button-color="blue"] { color: blue }
.MyLongClassName[data-button-color="green"] { color: green } 
```

As you can see the parent selector is repeated over and over, now multiply this for every nested selector. Without processing the nested syntax, we just get the exact same code in browsers:

```css
.MyLongClassName {
  color: red;
  &[data-button-color="blue"] { color: blue };
  &[data-button-color="blue"] { color: blue }
} 
```

139 chars minified vs. 108 chars minified. On our side, this is a vast improvement considering the amount of CSS we ship. 😌
