### ISSUE TITLE
JSX style improperly encoding variables

### ISSUE THREAD

**Issue by paul-sachs** [vercel/next.js#55612]
### Link to the code that reproduces this issue

https://stackblitz.com/edit/nextjs-omljut?file=pages%2F_app.js

### To Reproduce

1. Start application in development mode
2. Notice that the background is **not** red

### Current vs. Expected behavior

If you look at the attached css, it will look something like:

```css
html {
  --color-default: 0: red;
  background-color: var(--color-default);
}
```

It should look like:

```css
html {
  --color-default: red;
  background-color: var(--color-default);
}
```

In Next 13.4.19 this behaviour was working properly and displayed a red background in this case.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.11
    Relevant Packages:
      next: 13.5.1
      eslint-config-next: 13.5.0
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure
