### ISSUE TITLE
turbopack - css mask url with image not working

### ISSUE THREAD

**Issue by landsman** [vercel/next.js#56862]
### Link to the code that reproduces this issue

-

### To Reproduce

In our app, I use `mask` + `background` in CSS modules to change the colors of SVG icons. It's actually the best way I found which allows me to use SVG as a regular file, so let the browser cache it, to get the best performance. 

Here is snippet:

```css
.three_dots {
  width: 24px;
  height: 24px;

  content: "";
  display: block;

  mask-size: contain;
  mask: url("/theme/three-dots.svg") no-repeat center;

  background: var(--primary-color-hex);
}
```

### Current vs. Expected behavior

mask with url path do not work at all with `npm run dev --turbo`

![Screenshot 2023-10-15 at 16 38 12](https://github.com/vercel/next.js/assets/3184228/182d97ea-f20b-438b-92cc-1ae09ca87428)

if I do not use turbo: `npm run dev` it works just fine

![Screenshot 2023-10-15 at 16 39 04](https://github.com/vercel/next.js/assets/3184228/c78fa032-4450-45a6-bd10-c2bda2954904)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:57 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8112
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.5.4
  eslint-config-next: 13.5.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)
