### ISSUE TITLE
Mdx does not build properly with GitHub Pages (Actions)

### ISSUE THREAD

**Issue by dninomiya** [vercel/next.js#58637]
### Link to the code that reproduces this issue

https://github.com/dninomiya/mdx-export-sample/blob/main/next.config.mjs

### To Reproduce

1. Enable mdx and export according to the documentation.
2. Test publishing to GitHub Pages using the yml provided by GitHub
3. The build will not proceed normally and the Job will stop.

Build completes successfully in local environment (Node 19.7.0)

### Current vs. Expected behavior

Current:
[Build Error](https://github.com/dninomiya/mdx-export-sample/actions/runs/6918373034/job/18820564526#step:19:24)

Expected:
Build is successful

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103
Binaries:
  Node: 19.7.0
  npm: 9.5.0
  Yarn: 3.5.0
  pnpm: 8.7.5
Relevant Packages:
  next: 14.0.1
  eslint-config-next: 14.0.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

MDX (@next/mdx)

### Additional context

- [next.config](https://github.com/dninomiya/mdx-export-sample/blob/main/next.config.mjs)
- [action.yml](https://github.com/dninomiya/mdx-export-sample/actions/runs/6918373034/workflow)

**Comment by zeyios** [comment]
It looks like, the output path config is `./export`, but `tar` target path is `./out`. So `tar` can't find the files..  

It said: `tar: out: Cannot open: No such file or directory`

**Comment by dninomiya** [comment]
This configuration outputs to '/out'. Running the `build` command locally will generate `/out`. Also, action is completed when mdx is disabled.

Therefore, I suspect that the mdx build is not working properly with the GitHub Actions job.

https://nextjs.org/docs/app/building-your-application/deploying/static-exports#configuration

**Comment by dninomiya** [comment]
I solved it by disabling the following line in action.yml: It appears that this step overwrote the existing next.config.ts.

```yml
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next
```
