### ISSUE TITLE
Docs: Continuous Integration (CI) Build Caching # Bitbucket Pipelines

### ISSUE THREAD

**Issue by dartess** [vercel/next.js#58815]
### What is the improvement or update you wish to see?

Docs says:

```
Add or merge the following into your bitbucket-pipelines.yml at the top level (same level as pipelines):


definitions:
  caches:
    nextcache: .next/cache


Then reference it in the caches section of your pipeline's step:


- step:
    name: your_step_name
    caches:
      - node
      - nextcache
```

But if you add a cache without a `key`, it will get "stuck" and never update. Is this really something we should all be doing? with each new release the cache will be further and further from reality. is there any benefit to it?

### Is there any context that might help us understand?

-

### Does the docs page already exist? Please link to it.

https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#bitbucket-pipelines
