### ISSUE TITLE
Next/Image is not getting copied in static media

### ISSUE THREAD

**Issue by ad-manish** [vercel/next.js#60161]
### Link to the code that reproduces this issue

https://github.com/algodomain/nextjs-image-issue

### To Reproduce

Use the public folder and copy any image under img folder

```
root
|_ public
       |_ img
             |_ test-img.png
```

inside your component 

`
              <Image src="/img/test-img.png" alt="Image" width="900" height="600" />
`

When I run the build, it creates a folder as `.next/static/media` but test-img.png (or test-img.[random_num].png file is missing
`
npm run build
`

So that you know, these files are being copied if we refer to the image via CSS file, which is strange behaviour.

```background-image: url ('../img/test-img.png')
// notice ../ before the url
```

Also note that if you use inline css via your nextjs server component, the image is again missing 
```
style={{ backgroundImage: 'url(/img/test-img.png)' }}
//or
style={{ backgroundImage: 'url(../img/test-img.png)' }}
```

However, when I deploy the public folder in my server, these images are getting served, therefore I believe this is indeed a bug and must be fixed, why images are not being copied when we are using <Image> component of nextjs.  

### Current vs. Expected behavior

Image must be copied inside `.next/static/media` directory which is not the case when using <Image> but being copied when referenced from css file (added in rootLayout) (but not inline css)

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020
Binaries:
  Node: 20.10.0
  npm: 10.2.3
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: 14.0.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

App Router, Image optimization (next/image, next/legacy/image)

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by waigel** [comment]
Hey @ad-manish,

A few errors have crept into your example. The image "test-img1.png" referred to in "Case 2" does not exist in the `/img` folder. I think this is a typing error. You also need to embed the images differently. 

Instead of `url(/img/test-img.png)` you need to use the ["internal path"](https://nextjs.org/docs/pages/api-reference/components/image#src). You can import images into inline CSS in this way:
```tsx
import testImage1 from "../public/img/test-img.png";
----
<div
    style={{
      backgroundImage: `url(${testImage1.src})`,
      height: 80,
      width: 80,
    }}
/>
````
p.s. So don't forget to add the properties `height` and `width`, otherwise the div has no size....

For case 1 and 3 there is the same problem:
e.g. `background-image: url('/img/sample-img2.jpg');`
Do not use a static path to local images, as they will no longer exist under this path later. Instead, use the path as in "sample-img3". 

You can find an example of how to import images into NextJs in the documentation: https://nextjs.org/docs/app/building-your-application/optimizing/images#local-images

I hope this helps you...

**Comment by marcodali** [comment]
I solved it using:

package.json:
```
"engines": {
  "node": ">=18.17"
},
```

next.config.mjs:
```
const nextConfig = {
  output: 'standalone',
};
```

*.tsx files:
```
import Image from "next/image";

<Image
  src="/images/logo.png"
  alt="Logo"
  width={150}
  height={30}
  className="relative z-20"
  />
```

Azure Static Web App linked to GitHub actions using this deploy.yml:
```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@latest
        with:
          azure_static_web_apps_api_token: ${{ secrets.YOUR_API_TOKEN_AUTOGENERATED_RANDOM_ID }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: ""
```
