### ISSUE TITLE
nextjs logging on docker

### ISSUE THREAD

**Issue by fabioportieri** [vercel/next.js#60709]
### Link to the code that reproduces this issue

no link

### To Reproduce

Hello, i'm deploying two nextjs app on docker, but i noticed i have no logs whatsoever in the backend, my console.logs do not get printed

my dockerfile is pretty much the one in
https://medium.com/@elifront/best-next-js-docker-compose-hot-reload-production-ready-docker-setup-28a9125ba1dc

is there a configuration to do, in order to be able to see logs in a dockerized application?
the documentation here:
https://nextjs.org/docs/pages/building-your-application/deploying/production-checklist#logging
mentions the usage of pino, i'll try that too but i'm not very optimistic

my dockerfile is a readaptation of this:

https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/next-app/prod.Dockerfile

please provide some feedback otherwise i will be forced to rebuild my app using a different framework

### Current vs. Expected behavior

i do expect to inspect my application logs when the nextjs application is containerized

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.19.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant Packages:
      next: 13.4.19
      eslint-config-next: 13.4.19
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: standalone
```

### Which area(s) are affected? (Select all that apply)

Standalone mode (output: "standalone")

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

dockerfile:
```
FROM node:18-alpine AS base

# Step 1. Rebuild the source code only when needed
FROM base AS builder

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
# Omit --production flag for TypeScript devDependencies
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
  # Allow install without lockfile, so example works even without Node.js installed locally
  else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && yarn install; \
  fi

COPY src ./src
COPY public ./public
COPY next.config.js .
COPY tsconfig.json .
COPY tailwind.config.ts postcss.config.js ./
COPY drizzle.config.ts  ./ 
COPY config-overrides.js ./ 

# Environment variables must be present at build time
# https://github.com/vercel/next.js/discussions/14030
ARG OPENAI_KEY
ENV OPENAI_KEY=${OPENAI_KEY}

ARG NEXTAUTH_SECRET
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

ARG KEYCLOAK_SECRET
ENV KEYCLOAK_SECRET=${KEYCLOAK_SECRET}

ARG KEYCLOAK_ISSUER
ENV KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}

ARG KEYCLOAK_ID
ENV KEYCLOAK_ID=${KEYCLOAK_ID}

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

ARG CHROMA_API_IMPL
ENV CHROMA_API_IMPL=${CHROMA_API_IMPL}

ARG CHROMA_SERVER_HOST
ENV CHROMA_SERVER_HOST=${CHROMA_SERVER_HOST}

ARG CHROMA_SERVER_HTTP_PORT
ENV CHROMA_SERVER_HTTP_PORT=${CHROMA_SERVER_HTTP_PORT}

ARG NUTPROJECT_ACCESS_TOKEN_PLAIN
ENV NUTPROJECT_ACCESS_TOKEN_PLAIN=${NUTPROJECT_ACCESS_TOKEN_PLAIN}

ARG NUTPROJECT_ACCESS_TOKEN_SECRET
ENV NUTPROJECT_ACCESS_TOKEN_SECRET=${NUTPROJECT_ACCESS_TOKEN_SECRET}

ARG NUTPROJECT_ACCESS_TOKEN_IV
ENV NUTPROJECT_ACCESS_TOKEN_IV=${NUTPROJECT_ACCESS_TOKEN_IV}

ARG MINIO_ENDPOINT
ENV MINIO_ENDPOINT=${MINIO_ENDPOINT}

ARG MINIO_PORT
ENV MINIO_PORT=${MINIO_PORT}

ARG MINIO_USESSL
ENV MINIO_USESSL=${MINIO_USESSL}

ARG MINIO_ACCESSKEY
ENV MINIO_ACCESSKEY=${MINIO_ACCESSKEY}

ARG MINIO_SECRETKEY
ENV MINIO_SECRETKEY=${MINIO_SECRETKEY}

ARG MINIO_BUCKET_NAME
ENV MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}

ARG PORT
ENV PORT=${PORT}

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at build time
# ENV NEXT_TELEMETRY_DISABLED 1

# Build Next.js based on the preferred package manager
RUN \
  if [ -f yarn.lock ]; then yarn build; \
  elif [ -f package-lock.json ]; then npm run build; \
  elif [ -f pnpm-lock.yaml ]; then pnpm build; \
  else yarn build; \
  fi

# Note: It is not necessary to add an intermediate step that does a full copy of `node_modules` here

# Step 2. Production image, copy all the files and run next
FROM base AS runner

WORKDIR /app

# Don't run production as root
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=builder /app/public ./public


# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static


# Environment variables must be redefined at run time

ARG OPENAI_KEY
ENV OPENAI_KEY=${OPENAI_KEY}

ARG NEXTAUTH_SECRET
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

ARG KEYCLOAK_SECRET
ENV KEYCLOAK_SECRET=${KEYCLOAK_SECRET}

ARG KEYCLOAK_ISSUER
ENV KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER}

ARG KEYCLOAK_ID
ENV KEYCLOAK_ID=${KEYCLOAK_ID}

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

ARG CHROMA_API_IMPL
ENV CHROMA_API_IMPL=${CHROMA_API_IMPL}

ARG CHROMA_SERVER_HOST
ENV CHROMA_SERVER_HOST=${CHROMA_SERVER_HOST}

ARG CHROMA_SERVER_HTTP_PORT
ENV CHROMA_SERVER_HTTP_PORT=${CHROMA_SERVER_HTTP_PORT}

ARG NUTPROJECT_ACCESS_TOKEN_PLAIN
ENV NUTPROJECT_ACCESS_TOKEN_PLAIN=${NUTPROJECT_ACCESS_TOKEN_PLAIN}

ARG NUTPROJECT_ACCESS_TOKEN_SECRET
ENV NUTPROJECT_ACCESS_TOKEN_SECRET=${NUTPROJECT_ACCESS_TOKEN_SECRET}

ARG NUTPROJECT_ACCESS_TOKEN_IV
ENV NUTPROJECT_ACCESS_TOKEN_IV=${NUTPROJECT_ACCESS_TOKEN_IV}

ARG MINIO_ENDPOINT
ENV MINIO_ENDPOINT=${MINIO_ENDPOINT}

ARG MINIO_PORT
ENV MINIO_PORT=${MINIO_PORT}

ARG MINIO_USESSL
ENV MINIO_USESSL=${MINIO_USESSL}

ARG MINIO_ACCESSKEY
ENV MINIO_ACCESSKEY=${MINIO_ACCESSKEY}

ARG MINIO_SECRETKEY
ENV MINIO_SECRETKEY=${MINIO_SECRETKEY}

ARG MINIO_BUCKET_NAME
ENV MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}

ARG PORT
ENV PORT=${PORT}

# Uncomment the following line to disable telemetry at run time
ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

CMD ["node", "server.js"]
```

docker compose file: 

```
version: "3.8"

services:
  chatpdf-app:
    container_name: ${PREFIX}-app
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
        KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
        KEYCLOAK_ID: ${KEYCLOAK_ID}
        DATABASE_URL: ${DATABASE_URL}
        CHROMA_API_IMPL: ${CHROMA_API_IMPL}
        CHROMA_SERVER_HOST: ${CHROMA_SERVER_HOST}
        CHROMA_SERVER_HTTP_PORT: ${CHROMA_SERVER_HTTP_PORT}
        NUTPROJECT_ACCESS_TOKEN_PLAIN: ${NUTPROJECT_ACCESS_TOKEN_PLAIN}
        NUTPROJECT_ACCESS_TOKEN_SECRET: ${NUTPROJECT_ACCESS_TOKEN_SECRET}
        NUTPROJECT_ACCESS_TOKEN_IV: ${NUTPROJECT_ACCESS_TOKEN_IV}
        MINIO_ENDPOINT: ${MINIO_ENDPOINT}
        MINIO_PORT: ${MINIO_PORT}
        MINIO_USESSL: ${MINIO_USESSL}
        MINIO_ACCESSKEY: ${MINIO_ACCESSKEY}
        MINIO_SECRETKEY: ${MINIO_SECRETKEY}
        MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
        PORT: ${PORT}
    restart: always
    env_file:
      - .env
    ports:
      - 3002:3002
    image: ${CHATPDF_IMAGE_NAME}:${CHATPDF_IMAGE_VERSION}
    networks:
      chatpdf_net:
        aliases:
          - ${PREFIX}-app

  minio:
    container_name: ${PREFIX}-minio
    image: minio/minio
    ports:
      - "9040:9000"
      - "9041:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ....
      MINIO_ROOT_PASSWORD:....
    command: server --console-address ":9001" /data
    networks:
      chatpdf_net:
        aliases:
          - ${PREFIX}-minio
  minio-init:
    image: minio/mc
    command:
      [
        "sh",
        "-c",
        "chmod +x /docker-entrypoint-initdb.d/init_minio.sh && /docker-entrypoint-initdb.d/init_minio.sh",
      ]
    volumes:
      - ./minio/init_minio.sh:/docker-entrypoint-initdb.d/init_minio.sh
    entrypoint: [""]
    depends_on:
      - minio
    networks:
      nut_net:
        aliases:
          - chatpdf-minio-init
  chromadb:
    container_name: ${PREFIX}-chromadb
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_persistent_folder:/chroma/chroma/

    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
    ports:
      - 8001:8000
    networks:
      chatpdf_net:
        aliases:
          - ${PREFIX}-chromadb

volumes:
  chroma_persistent_folder:
    driver: local
  minio_data:
    driver: local

networks:
  chatpdf_net:
    driver: bridge
    name: chatpdf_net
  nut_net:
    external: true
```
