### ISSUE TITLE
Sass Variables not exported in --turbo 

### ISSUE THREAD

**Issue by Chukwu3meka** [vercel/next.js#61322]
### Link to the code that reproduces this issue

https://github.com/Chukwu3meka/SoccerMASS-Web/blob/main/utils/handlers.ts

### To Reproduce

```scss

// variables.module.scss

$primary-color: rgb(68, 139, 68);
$secondary-color: rgb(141, 202, 141);
$dark-color: #000000;
$light-color: #ffffff;
$highlight-color: #e2ad26;

$dark-theme-primary-color: #22272e;
$dark-theme-secondary-color: #30353c;
$dark-theme-contrast-color: #d8d8d8;

$light-theme-primary-color: #ffffff;
// $light-theme-secondary-color: #e9e9e9;
$light-theme-secondary-color: #f7f7f7;
$light-theme-contrast-color: #06051b;

:export {
  darkColor: $dark-color;
  lightColor: $light-color;
  primaryColor: $primary-color;
  secondaryColor: $secondary-color;
  highlightColor: $highlight-color;

  darkThemePrimaryColor: $dark-theme-primary-color;
  darkThemeSecondaryColor: $dark-theme-secondary-color;
  darkThemeContrastColor: $dark-theme-contrast-color;

  lightThemePrimaryColor: $light-theme-primary-color;
  lightThemeSecondaryColor: $light-theme-secondary-color;
  lightThemeContrastColor: $light-theme-contrast-color;
}


```

### Current vs. Expected behavior

    import stylesVariables from "../styles/variables.module.scss";

stylesVariables (in helpers.ts setCssThemeVar function) is supposed to return and object of all exported scss variables, but when `next dev --turbo` is run stylesVariables returns an empty object.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.0.4
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.3.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router, Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)
