### ISSUE TITLE
Npm run build applicaation with path alias and app router and github actions does not work. 

### ISSUE THREAD

**Issue by zcemycl** [vercel/next.js#63983]
### Link to the code that reproduces this issue

https://github.com/zcemycl/systemDeploy/tree/main/src/tf/cognito-app/frontend

### To Reproduce

1. Set up application with app router.
2. Create a root page.tsx in folder structure. `src/app/page.tsx`
3. Create a use context module in `src/contexts/abc.tsx`.
4. Import module into root page.tsx. 
5. Run `npm ci` and `npm run build`.
6. Result in `Module not found: Can't resolve '@/contexts/abc'`.

### Current vs. Expected behavior

- npm run build works in local and docker. I cannot find the reason why it does not work in github actions. 
- If i change the import path from @/ to ../.. ,  it will work. 

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:06 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T8103
Binaries:
  Node: 19.2.0
  npm: 8.19.3
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.1.4
  eslint-config-next: 14.1.4
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.3
Next.js Config:
  output: standalone
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next build (local)

**Comment by JesseKoldewijn** [comment]
Hey there!
First of, sorry to hear ur having trouble with this matter.

I'd like to start with the following, I couldn't find any reference to a github action in the provided reproduction repo. So, I tested it with the that repo and a minimal github action. I couldn't reproduce the mention error as a result of the build script.

Please refer to the repo below which includes your /frontend project + a minimal github action which does pass the build step as shown in the repo below.

https://github.com/JesseKoldewijn/next-ts-alias-issue

**Comment by JesseKoldewijn** [comment]
This leads me to believe that the issue might be with the github action setup you're trying to use. If you could share this action, I'd love to troubleshoot it for you. :+1:

**Comment by zcemycl** [comment]
@JesseKoldewijn 
Commented parts are the build stage that does not work. 
```
name: Next CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
env:
  node_version: "20"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.node_version}}

      - run: npm install
      - run: |
          npm run lint
          npm run prettier:lint

  # build:
  #   runs-on: ubuntu-latest
  #   env:
  #     NODE_ENV: "production"
  #     CI: true
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{env.node_version}}

  #     - name: create .env.local file
  #       run: |
  #         touch .env.local
  #         echo NEXT_PUBLIC_AWS_REGION=${{ secrets.NEXT_PUBLIC_AWS_REGION }} >> .env.local
  #         echo NEXT_PUBLIC_AWS_COGNITO_USERPOOL_ID=${{ secrets.NEXT_PUBLIC_AWS_COGNITO_USERPOOL_ID }} >> .env.local
  #         echo NEXT_PUBLIC_AWS_COGNITO_USERPOOL_CLIENT_ID=${{ secrets.NEXT_PUBLIC_AWS_COGNITO_USERPOOL_CLIENT_ID }} >> .env.local
  #         echo NEXT_PUBLIC_AWS_ACCESS_KEY_ID=${{ secrets.NEXT_PUBLIC_AWS_ACCESS_KEY_ID }} >> .env.local
  #         echo NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY=${{ secrets.NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY }} >> .env.local
  #         echo NEXT_PUBLIC_ENV_NAME=${{ secrets.NEXT_PUBLIC_ENV_NAME }} >> .env.local
  #         echo NEXT_PUBLIC_COGNITO_OPENID_CONF_URI=${{ secrets.NEXT_PUBLIC_COGNITO_OPENID_CONF_URI }} >> .env.local
  #         echo NEXT_PUBLIC_BACKEND_BASE_URL=${{ secrets.NEXT_PUBLIC_BACKEND_BASE_URL }} >> .env.local
  #         echo NEXT_PUBLIC_DOMAIN_NAME=${{ secrets.NEXT_PUBLIC_DOMAIN_NAME }} >> .env.local
  #         echo NEXT_PUBLIC_ADMIN_EMAIL=${{ secrets.NEXT_PUBLIC_ADMIN_EMAIL }} >> .env.local

  #     - run: npm ci
  #     - run: npm run build
```
