### ISSUE TITLE
Mismatch of names in grid-template-areas and grid-area across different css modules with --turbo

### ISSUE THREAD

**Issue by Arctomachine** [vercel/next.js#64509]
### Link to the code that reproduces this issue

https://github.com/Arctomachine/next-grid-template-areas-bug

### To Reproduce

1. Start dev server with --turbo flag
2. Observe devtools for different names of grid areas in grid and in cards, incorrect visuals

### Current vs. Expected behavior

Expected: areas have same name in grid and cards
Current: area names mismatch. Grid will append its module name to grid-template-area, but card will append its module name to grid-area. Since they are different names, browser will not put cards into grid correctly.

Example of area name in grid:
![image](https://github.com/vercel/next.js/assets/29041820/32dcb2e9-65a3-4235-bc78-d7e2987d917c)
And in card:
![image](https://github.com/vercel/next.js/assets/29041820/0c7c6ced-9a2f-42d5-8583-f5278ee0a028)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32720
  Available CPU cores: 12
Binaries:
  Node: 20.10.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.1-canary.6 // Latest available version is detected (14.2.1-canary.6).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack (--turbo)

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

Only happens for turbopack in dev mode. Production build is not affected

<sub>[PACK-2976](https://linear.app/vercel/issue/PACK-2976/mismatch-of-names-in-grid-template-areas-and-grid-area-across)</sub>

**Comment by TariqSaiyad** [comment]
I'm experiencing the same issue. I've got a grid container in the _header.module.scss_ file: `header-module-scss-module__I8X9PG__Level1`

and the same grid-area name in the _mega-menu.module.scss_ file: `mega--menu-module-scss-module__cuXXBW__Level1`

This completely breaks the grid and layout

**Comment by cpotey** [comment]
Also experiencing this, and it's a pretty big blocker.

I work in a turborepo monorepo. Decided to try turbopack on a new Next.js app I was working on, and one of my shared components uses `grid-template-areas`, and has become completely confused and broken. Unsure whether to attempt to refactor things, or hope for a fix.

Think I'll just exclude turbopack/`--turbo` for now.

**Comment by erikbrgn** [comment]
I'm not entirely sure this is solely due to an issue in turbopack. It might as well be due to lightningcss doing something weird under-the-hood. Fortunately, there's a work-around for those of you who want to keep using CSS modules with ´grid-template-areas` and `grid-area` until this is fixed properly.

Using turbopack in a nextjs project, this "setup" has worked for me:

```css
/* layout.module.css */

.layout {
  grid-template-areas:
    'header header header header'
    'nav main main main'
    'nav main main main'
    'footer footer footer footer;
}

.header {
  grid-area: header;
}

.nav {
  grid-area: nav;
}

.main {
  grid-area: main;
}
```

```css
/* header.module.css */

.header {
  composes: header from './layout.module.css';
  */ ... */
}
```

```css
/* nav.module.css */

.nav {
  composes: nav from './layout.module.css';
  */ ... */
}
```

```css
/* main.module.css */

.main {
  composes: main from './layout.module.css';
  */ ... */
}
```

And so on...
