### ISSUE TITLE
Next.js doesn't resolve docker network defined hostnames

### ISSUE THREAD

**Issue by jtara1** [vercel/next.js#66920]
### Link to the code that reproduces this issue

https://gist.github.com/jtara1/bcf9b5f83d50d930763989611316146d

### To Reproduce

- create project dir, named `docker-compose-next-js`
- `mkdir api; cd api; npm init -y`
- create a basic HTTP API using node.js and express or whatever, bind the http server to `0.0.0.0:3001`
- `cd ..`
- create your next.js app as web-app
- in a react component useEffect, call `await fetch('http://api:3001/')`
- create Dockerfile's for each sub-projects
- create docker-compose.yaml such as

```
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: always

  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://api:3001
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    restart: always
```

I can resolve the default docker-compose network hostname for my service, api, in a few places:
- docker web-app container
- next.config.mjs (hard-coded)

### Current vs. Expected behavior

resolve `http://api:3001` in a component

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 32695
  Available CPU cores: 16
Binaries:
  Node: 20.13.1
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.3 // There is a newer version (14.2.4) available, upgrade recommended!
  eslint-config-next: 14.2.3
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.4.5
Next.js Config:
  output: N/A
 ⚠ There is a newer version (14.2.4) available, upgrade recommended!
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)
