### ISSUE TITLE
Small request per second rate related to trailing slash

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [vercel/next.js#70346]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System: node:18-alpine in Docker
Relevant Packages:
  next: 14.2.12 // There is a newer version (14.2.13) available, upgrade recommended! 
  eslint-config-next: 14.2.12
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.1.3
```

### Which example does this report relate to?

any

### How are you deploying your application? (if relevant)

Docker, Amazon ECS

### Describe the Bug

I use Yandex Tank to count Request Per Seconds rate in Next.js site. When I request route with small RPS (50 requests max.) everything is ok. 

I have `trailingSlash: true` settings in `next.config.js`. When I request route **/example**, RPS is ok.
<img width="1196" alt="Снимок экрана 2024-09-23 в 16 57 13" src="https://github.com/user-attachments/assets/fffe5dee-ca95-410a-ae51-70cc837a37e4">

When I request route **/example/**, I get bad RPS rate.
<img width="1191" alt="Снимок экрана 2024-09-23 в 16 56 30" src="https://github.com/user-attachments/assets/b013ceb8-77eb-4039-af6c-96cf275864b7">

When I remove `trailingSlash` settings, I get opposite result. **/example** has bad RPS rate, **/example/** is ok.

When I set `skipTrailingSlashRedirect: true`, I get bad RPS rate anyway.

Yandex Tank config example:
```yml
phantom:
  address: 127.0.0.1:443
  load_profile:
    load_type: rps
    schedule: const(500, 1m)
  ssl: true
  header_http: "1.1"
  headers:
    - "[Host: example.com]"
    - "[Connection: close]"
  uris:
    - "/example"
console:
  enabled: true
telegraf:
  enabled: false
  ```

### Expected Behavior

RPS rate does not depend on trailing slash.

### To Reproduce

Higher
