### ISSUE TITLE
[v15] Module parse failed: Bad character escape sequence

### ISSUE THREAD

**Issue by faisalrehmanlums** [vercel/next.js#71582]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/condescending-haze-go8s7s 

### To Reproduce

1. run this commad: `npx create-next-app@latest`
2. This will install latest version of nextjs like in package.json is  `"dependencies": {
    "react": "19.0.0-rc-65a56d0e-20241020",
    "react-dom": "19.0.0-rc-65a56d0e-20241020",
    "next": "15.0.0"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "eslint": "^8",
    "eslint-config-next": "15.0.0"
  }` 
3. npm run dev
4. browser showing error `Module parse failed: Bad character escape sequence (11:57)
|   const fileSizeInMB = buffer.byteLength / 1024 / 1024

![error](https://github.com/user-attachments/assets/6955ae7d-ae47-43a2-8e2e-48d181056355) 
`

### Current vs. Expected behavior

I have just not changed any default value during app creation like shown in screenshot 
it should spin up dev server without error. which it dose but after within seconds error pop out. 
![install](https://github.com/user-attachments/assets/37af0273-c78b-41d1-bc6f-789bd01022f1)

### Provide environment information

```bash
test
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

When i step down to version 14 its working fine with 14.2.15 ` npx create-next-app@14 test-project`

**Comment by FKAJerry** [comment]
v15 stable has this bug it's  CRAZY!

Is anyone in the next.js community actually reviewing code?

**Comment by Sayakie** [comment]
Looks like this started appearing in `next@15.0.0-canary.180` on Windows platform.

* #70353

**Comment by darthmaim** [comment]
What node.js version are you using (please fill out the entire issue template next time)? There was a bug in some recent Node.js versions recently that had some similar symptoms, you should try upgrading,

**Comment by kdy1** [comment]
I think we should not inline the path into the string, or we should replace `\` with `\\` on windows. cc @devjiwonchoi

**Comment by faisalrehmanlums** [comment]
> What node.js version are you using (please fill out the entire issue template next time)? There was a bug in some recent Node.js versions recently (mainly 22.7.0) that had some similar symptoms, you should try upgrading if you are using that version.

I'm using node verion `v20.18.0` with npm version `10.9.0`

**Comment by faisalrehmanlums** [comment]
I have installed the canary version but still issue not resolved. Here is my package.json screenshot with error.

![image](https://github.com/user-attachments/assets/75c86926-9436-48e6-8327-adcccaa84af0)

cmd is 

![image](https://github.com/user-attachments/assets/3f936cfa-7749-40a7-baaf-e177a556e9db)

**Comment by Sayakie** [comment]
@devjiwonchoi, I suppose to webpack loader should be fix as well:
https://github.com/vercel/next.js/blob/79bc150e95d904579e6fd608aa2646bf4111ada8/packages/next/src/build/webpack/loaders/next-metadata-route-loader.ts#L108

**Comment by devjiwonchoi** [comment]
@Sayakie Thank you! Could you add the `next info` as well? I wasn't able to reproduce this issue on my VM, which I think it slipped.

**Comment by Sayakie** [comment]
FYI, here is my development environment:
```yaml
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 23855
  Available CPU cores: 12
Binaries:
  Node: 22.9.0
  npm: N/A
  Yarn: N/A
  pnpm: 9.12.0
Relevant Packages:
  next: 15.0.1 // Latest available version is detected (15.0.1).
  eslint-config-next: 14.2.13
  react: 19.0.0-rc-45804af1-20241021
  react-dom: 19.0.0-rc-45804af1-20241021
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

`next dev --turbo` is working healthy but either `next dev` or `next build` throws the same error.
