### ISSUE TITLE
Vercel local build for NextJS and prebuilt deployment throws error with styled-jsx

### ISSUE THREAD

**Issue by realnikitimi** [vercel/next.js#73648]
### Link to the code that reproduces this issue

https://github.com/nikitimi/examiner-monorepo

### To Reproduce

1. Set-up a monorepo using `pnpm`.
2. create catalog with `codemode pnpm/catalog`.
3. create-next-app inside monorepo's packages.
4. create `pnpm-workspace.yaml`.
5. include catalogs in `pnpm-workspace.yaml`:

```yaml
  catalogs:
    next-canary:
      next: 15.0.4-canary.45
      react: 19.0.0-rc.1
      react-dom: 19.0.0-rc.1
    next-stable:
      next: 15.0.4
      react: 19.0.0-rc.1
      react-dom: 19.0.0-rc.1
```
6. Run `vercel build && vercel deploy --prebuilt`.

### Expected:

Deployed in Vercel.

### Current:
![Screenshot 2024-12-08 020246](https://github.com/user-attachments/assets/d8d959ca-8ede-4575-8fc1-bc48c01ae7f4)

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 10 Pro
  Available memory (MB): 8026
  Available CPU cores: 8
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.12.2
Relevant Packages:
  next: 15.0.4 // Latest available version is detected (15.0.4).
  eslint-config-next: N/A
  react: 19.0.0
  react-dom: 19.0.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Developer Experience, Output (export/standalone)

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

I've tested putting env var like stated in [issue #1209](https://github.com/orgs/vercel/discussions/1209) to disable build cache, but it is not working, I also tested passing --force flag, but it is still not working.
