### ISSUE TITLE
Failed communication between Nextjs and internal docker services inside a docker network

### ISSUE THREAD

**Issue by rahulcodepython** [vercel/next.js#76913]
### Link to the code that reproduces this issue

https://github.com/rahulcodepython/Password-Manager-Client.git

### To Reproduce

1. Create a next app with latest version
2. Use ssr in nextjs
3. Create a backend
4. Connect them inside a docker

### Current vs. Expected behavior

I am building a password manager app. Here I am using Next JS as frontend and Django as backend framework. I am deploying the whole thing using docker. There are three services frontend, backend and nginx a proxy server. Now one of my Next JS route needs SSR or (Server Side Rendering). So I am using an async component with fetch API call. The URL I am using is `http://backend:8000/api/v2/` but I am getting an error like

`{"cause":{"errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"backend"}}`

Now I will mention my code snippet below.

### page.tsx file
```ts
const HelloPage = async () => {
    return await fetch(process.env.API_URL!)
        .then(response => response.json())
        .then(data => {
            return <div>
                <h1>API Response</h1>
                <pre>{JSON.stringify(data)}</pre>
            </div>
        })
        .catch(error => {
            return <div>
                <h1>Error</h1>
                <pre>{JSON.stringify(error)}</pre>
            </div>
        });
};

export default HelloPage;
```
### next.config.ts
```ts
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
    /* config options here */
    output: "standalone",
    env: {
        API_URL: process.env.API_URL
    }
};

export default nextConfig;
```
### environment variable
```
API_URL='http://backend:8000/api/v2/'
```

### dockerfile
```
# syntax=docker.io/docker/dockerfile:1

FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
    else echo "Lockfile not found." && exit 1; \
    fi


# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED=1

RUN \
    if [ -f yarn.lock ]; then yarn run build; \
    elif [ -f package-lock.json ]; then npm run build; \
    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
    else echo "Lockfile not found." && exit 1; \
    fi

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
```

### docker-compose.yml file
```
version: "3"

networks:
    app_network:
        name: app_network
        driver: bridge

services:
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
            tags:
                - password-manager-backend-app

        container_name: password-manager-backend-app

        restart: always

        volumes:
            - staticfiles:/app/staticfiles

        ports:
            - "8000:8000"

        networks:
            - app_network

        command:
            # ["gunicorn", "--bind", "0.0.0.0:8000", "server.wsgi:application"]
            ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    frontend:
        # build: ./client
        image: password-manager-frontend-app

        container_name: password-manager-frontend-app

        restart: always

        networks:
            - app_network

        ports:
            - "3000:3000"

        depends_on:
            - backend

        command: ["node", "server.js"]

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
            tags:
                - password-manager-nginx-app

        container_name: password-manager-nginx-app

        ports:
            - 80:80

        networks:
            - app_network

        volumes:
            - staticfiles:/app/static

        depends_on:
            - backend
            - frontend

volumes:
    staticfiles:
```

Now as I am using Django as backend so I would like to mention the `ALLOWED_HOSTS` and `CORS_ALLOWED_ORIGINS` below 

`ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1", "backend"]`

```py
CORS_ALLOWED_ORIGINS = [
    "http://frontend:3000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:80",
    "http://localhost",
]
```

I can also ensure that from my frontend service executable shell, I can able to access the service running on `http://backend:8000/api/v2/`, as I have used curl to justify this.

I have tried multiple ways and also read many articles but none of these helped me.

### Provide environment information

```bash
"@radix-ui/react-dialog": "^1.1.6",
    "@radix-ui/react-label": "^2.1.2",
    "@radix-ui/react-slot": "^1.1.2",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "cookies-next": "^5.1.0",
    "lucide-react": "^0.477.0",
    "next": "15.2.0",
    "next-themes": "^0.4.4",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-hook-form": "^7.54.2",
    "sonner": "^2.0.1",
    "tailwind-merge": "^3.0.2",
    "tailwindcss-animate": "^1.0.7"
```

### Which area(s) are affected? (Select all that apply)

Webpack, Output

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

### Additional context

I am hosting via docker with recommended `output: "standalone"` option. My current nextjs version is 15.2.0
