### ISSUE TITLE
Open graph image generation cannot load static image from path

### ISSUE THREAD

**Issue by vojtechmares** [vercel/next.js#77699]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/white-forest-zd8n9h

### To Reproduce

1. deploy the app to Vercel using the Vercel CLI (`vercel build ... && vercel deploy --prebuilt ...`)
2. try opening the opengraph image
3. See error 500 and in logs error that the `/var/task/public/images/people/vojtech-mares.png` image was not found

### Current vs. Expected behavior

Current: OG image endpoint returns error 500 after it fails to locate the image in the built version. I've checked the output source and the image file exists.

Expected: an image is returned for the OG including the static image of myself in the generated OG picture

The issue is only present in Vercel deployment, everything works locally just fine.

### Provide environment information

```bash
/bin/sh: yarn: command not found

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:16 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 22.14.0
  npm: 10.9.2
  Yarn: N/A
  pnpm: 9.12.2
Relevant Packages:
  next: 15.2.4 // Latest available version is detected (15.2.4).
  eslint-config-next: 15.2.4
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.8.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

Vercel (Deployed)

### Additional context

I tested the latest version.

I do not have a Git repository connected since the source is on my private GitLab instance and I am using GitLab CI to deploy the application with Vercel CLI.

The deployment job looks like this:

```yaml
# ...
deploy:production:
  stage: deploy
  script:
    - vercel pull --yes --environment=production --token=${VERCEL_TOKEN}
    - vercel build --prod --token=${VERCEL_TOKEN}
    - vercel deploy --prod --prebuilt --token=${VERCEL_TOKEN}
  environment:
    name: production
    url: https://www.mares.cz
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
```
