### ISSUE TITLE
Next 15.3 breaks scroll anumations

### ISSUE THREAD

**Issue by IvanKalinin** [vercel/next.js#78046]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/lgl5ty

### To Reproduce

https://codesandbox.io/p/devbox/lgl5ty

1. Start the application with NextJS 15.3.x
2. Add CSS scroll animation
E.g.
```css
@keyframes parallax {
  from {
    transform: translateX(var(--transition-from));
  }
  to {
    transform: translateX(var(--transition-to));
  }
}

@supports (animation-timeline: view()) {
  [data-part="image"] {
    animation: parallax linear;
    animation-timeline: view();

    --transition-from: -50%;
    --transition-to: -100%;
  }
}
```
3. See, the animation does not work.
bundler generate this code
```css
@supports (animation-timeline: view()) {
    [data-part="image"] {
        --transition-from: -50%;
        --transition-to: -100%;
        animation: linear parallax view();
    }
}
```

<img width="317" alt="Image" src="https://github.com/user-attachments/assets/984b2a51-53c5-4b30-b9ee-2b6f70431efa" />

### Current vs. Expected behavior

It works fine with 15.2
https://codesandbox.io/p/devbox/whd6nm

it generates this CSS
```css
@supports (animation-timeline: view()) {
    [data-part="image"] {
        --transition-from: -50%;
        --transition-to: -100%;
        animation: auto linear 0s 1 normal none running parallax normal normal;
    }
}
```

<img width="316" alt="Image" src="https://github.com/user-attachments/assets/b879a6a5-07bd-4ba3-adda-d7450750e4d6" />

### Provide environment information

```bash
Next.JS 15.3.0
```

### Which area(s) are affected? (Select all that apply)

CSS

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)
